### ISSUE TITLE
https://pub.dev/

### ISSUE THREAD

**Issue by washpan** [dart-lang/pub#2936] opened 2021-03-25 02:27 UTC
https://pub.dev/ Your server return 502 error at 3-25-2021.

**Comment by Levi-Lesches** [comment] 2021-03-25 02:31
Getting this error too. isitdownrightnow.com is reporting it's been like that for 45 minutes

**Comment by chrissxYT** [comment] 2021-03-25 02:55
yea i have been experiencing it for the last hour, too

**Comment by Levi-Lesches** [comment] 2021-03-25 02:57
It was acknowledged here: https://github.com/dart-lang/pub-dev/issues/4663

No ETA as of yet.

**Comment by mingyouzhu** [comment] 2021-03-25 03:26
pub is down,,,haha

**Comment by yubaokang** [comment] 2021-03-25 03:37
挂球了

**Comment by 2dxgujun** [comment] 2021-03-25 04:03
+1

**Comment by bhtri** [comment] 2021-03-25 04:12
+1

**Comment by Levi-Lesches** [comment] 2021-03-25 04:14
Guys, please stop spamming this issue with "+1" and "me too" (and don't do it on dart-lang/pub-dev#4663 either). It sends an annoying message to everyone, every time. Just press the subscribe button if you want to get notifications. You can press the thumbs up to let people know this is a popular issue, but the team is already working on it. Just be patient and wait for an update.

**Comment by chrissxYT** [comment] 2021-03-25 07:44
@washpan pub is back

**Comment by sigurdm** [comment] 2021-03-29 08:10
Closing as duplicate of https://github.com/dart-lang/pub-dev/issues/4663

**Closed by sigurdm** 2021-03-29 08:10 UTC
