### ISSUE TITLE
external package installation error

### ISSUE THREAD

**Issue by rohitmourya40901** [dart-lang/pub#3043] opened 2021-07-05 12:16 UTC
PS E:\flutter_project\xylophone_flutter> flutter pub add audioplayers
Resolving dependencies...
  async 2.6.1 (2.7.0 available)
+ audioplayers 0.19.1
  charcode 1.2.0 (1.3.1 available)
+ crypto 3.0.1
+ ffi 1.1.2
+ file 6.1.2
+ flutter_web_plugins 0.0.0 from sdk flutter
+ http 0.13.3
+ http_parser 4.0.0
+ js 0.6.3
  meta 1.3.0 (2.0.0 available)
+ path_provider 2.0.2
+ path_provider_linux 2.0.0
+ path_provider_macos 2.0.0
+ path_provider_platform_interface 2.0.1
+ path_provider_windows 2.0.1
+ pedantic 1.11.1
+ platform 3.0.0
+ plugin_platform_interface 2.0.0
+ process 4.2.1
  test_api 0.3.0 (0.4.1 available)
+ uuid 3.0.4
+ win32 2.2.4
+ xdg_directories 0.2.0
Downloading audioplayers 0.19.1...
Downloading path_provider 2.0.2...
Downloading pedantic 1.11.1...
Downloading ffi 1.1.2...
Downloading file 6.1.2...
Downloading win32 2.2.4...
Bad state: Could not find 7zip.
package:pub/src/io.dart 885:3             _pathTo7zip.<fn>
package:pub/src/io.dart 886:3             _pathTo7zip
package:pub/src/io.dart                   _pathTo7zip
package:pub/src/io.dart 827:22            extractTarGz.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 773:12            withTempDir
===== asynchronous gap ===========================
package:pub/src/io.dart 818:25            extractTarGz
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 531:5  BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 381:7  BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 436:35    Entrypoint._get.<fn>
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 431:12    Entrypoint._get
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 265:7     Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/add.dart 152:7    AddCommand.runProtected
This is an unexpected error. Please run

    dart pub --trace add audioplayers

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub finished with exit code 1

**Comment by sigurdm** [comment] 2021-09-16 08:49
I think this is a duplicate of: https://github.com/dart-lang/pub/issues/3068 .

**Closed by sigurdm** 2021-09-16 08:49 UTC
