### ISSUE TITLE
Error (255): Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (6 tries left)

### ISSUE THREAD

**Issue by baidya07** [dart-lang/pub#3448] opened 2022-06-06 05:35 UTC
![image](https://user-images.githubusercontent.com/85629481/172100519-2d1d015d-12d6-4562-af6f-2d07718f7ce0.png)

This is happening when I am using fvm to install new  or old version. It doesn't upgrade when I try to install new version or old version.
When I try to go to the location of pub_log.txt, there is no log folder so I cannot open the file to see the full log and details.

**Comment by sigurdm** [comment] 2022-06-09 08:57
Try removing pubspec.lock and trying again. Seems it is broken.

Similar to: https://github.com/dart-lang/pub/issues/3398

We need to look at our lockfile parsing code.

**Comment by sigurdm** [comment] 2023-09-14 11:37
Just looking at this again, and I was mistaken. This error is not in the lockfile parsing.

I think this is a duplicate of https://github.com/dart-lang/pub/issues/3463 (that has been fixed).

**Closed by sigurdm** 2023-09-14 11:37 UTC
Labels: type-bug
