### ISSUE TITLE
`pub build` tries to build all dependencies

### ISSUE THREAD

**Issue by emilniklas** [dart-lang/pub#1341] opened 2015-10-09 07:20 UTC
It seems that `pub build` always pre-compiles every dependency in pubspec. But since some projects has both a front and back end, some dependencies can't be built (i.e. native-ext, I believe is the issue).

I want to build `web/main.dart` with no imports, but since my server side depends on the package `libffi6_extension`, I get the following error message:

```
[Error from Dart2JS]:
file:///Users/emilpersson/.pub-cache/hosted/pub.dartlang.org/libffi6_extension-0.0.6/lib/src/web/main.dart: Exception: Cannot read file:///Users/emilpersson/.pub-cache/hosted/pub.dartlang.org/libffi6_extension-0.0.6/lib/src/web/main.dart because it is outside of the build environment.
[Info from Dart2JS]:
Took 0:00:01.636863 to compile app|web/main.dart.
Build failed.
```

I don't think this is a problem with `libffi6_extension`, but I might be wrong.

**Comment by zoechi** [comment] 2015-10-09 07:32
https://www.dartlang.org/tools/pub/assets-and-transformers.html#excluding-assets

**Comment by emilniklas** [comment] 2015-10-09 07:43
@zoechi How would I use that to exclude a dependency? This does nothing:

```yaml
transformers:
  - $dart2js:
      $exclude: packages/libffi6_extension
```

**Comment by emilniklas** [comment] 2015-10-09 07:54
Got it! I had to do:

```yaml
transformers:
  - $dart2js
      $include: '**/*.dart'
```

**Comment by emilniklas** [comment] 2015-10-09 08:05
Actually, no. It didn't work. It did like once, and now it fails again.. Strange!

**Comment by zoechi** [comment] 2015-10-09 08:11
Where is the entry point of your "server side"?

Try

```yaml
- $dart2js:
    $exclude: bin
```

**Comment by emilniklas** [comment] 2015-10-09 08:18
Even when having this:

```yaml
transformers:
- $dart2js:
    $exclude:
    - config
    - storage
    - tool
    - lib/app
    - lib/main
    - lib/service_providers
    - lib/templates
    - lib/app.dart
    - lib/migrations.dart
    - lib/services.dart
    $include:
    - web/main.dart
    - lib/client.dart
    - lib/app_client
    - lib/app_shared
```

Excluding everything not client specific and including everything client specific, it still tries to incorporate the `libffi6_extension` somehow. Oh, and main.dart looks like this:

```dart
main() {}
```

**Comment by zoechi** [comment] 2015-10-09 08:28
Where is your server entry point. It is usually in `bin`? You haven't excluded `bin`.

**Comment by emilniklas** [comment] 2015-10-09 08:32
There is no bin folder. My entry point is a file in root called `bridge`. Including that doesn't help either

**Comment by zoechi** [comment] 2015-10-09 08:53
Is this a typo? I thought you want to **exclude** it or is `bridge` not your server side entry point?. 
> entry point in root called "bridge"
  
is weird. Is it a Dart file? Server entry points have to be in `bin` by `pub` convention.

**Comment by emilniklas** [comment] 2015-10-09 09:05
I'm sorry, I was unclear.

The real server side entry point is in a package, so to start the server and such we just need a startup file. For aesthetical reasons (it's nice to write `dart bridge`), this file doesn't have an extension. In production, the startup file would be something like `bin/server.dart`. 

And "Including that doesn't help either" was my bad, I meant "Including that file in `$exclude` doesn't help either"

**Comment by emilniklas** [comment] 2015-10-09 09:08
And, before you ask: If I change `bridge` to `bin/bridge.dart` and `$exclude` `bin`, it still doesn't work

**Comment by zoechi** [comment] 2015-10-09 09:13
Ok, I'm almost out of questions ;-) but one: Can you provide a github repo with a project that allows to reproduce the problem.

**Comment by emilniklas** [comment] 2015-10-09 09:14
Already did ;)

https://github.com/dart-bridge/bridge

**Comment by emilniklas** [comment] 2015-10-09 09:45
@zoechi You'll have to clone the `develop` branch, btw

**Comment by zoechi** [comment] 2015-10-09 10:22
It's the default branch anyway.
What does
> I want to build web/main.dart **with no imports**

actually mean?
Does your code in `web/main.dart` actually import the `libffi*` stuff (transitively) but you want `pub build` to ignore these imports?

I don't get any error when I run `pub build`

>  (develop) $ pub build
Loading source assets... 
Loading libffi6_extension and unsafe_extension transformers... 
Building app... Setup libffi6_extension.so.
Already installed binary 'compiled/X86_64/linux/libffi6_extension.so'
The setup successful.
Building app... Setup libunsafe_extension.so.
Already installed binary 'compiled/X86_64/linux/libunsafe_extension.so'
The setup successful.
Building app... (1.6s) 
Built 39 files to "build".

There also is no `index.html` in the `web` directory. How is that supposed to work?

**Comment by emilniklas** [comment] 2015-10-09 10:36
> What does "I want to build web/main.dart with no imports" actually mean?

Of course I want main.dart to have imports at some point, but just to make sure that the file _didn't_ import the extension (transitively or otherwise), i made a completely empty file (except for a main method).

> I don't get any error when I run `pub build`

I just now created a temporary fix for this issue, so the pubspec now excludes all dart files:

```yaml
# Temporary (https://github.com/dart-lang/pub/issues/1341)
transformers:
- $dart2js:
    $exclude: web/**.dart
```

Just remove that piece of code and rerun `pub build` and you'll see the issue, I'm sure.

> There also is no `index.html` in the `web` directory. How is that supposed to work?

The HTML is being generated on the server side.

**Comment by emilniklas** [comment] 2015-10-09 10:45
Side note: dart2js works, still:

```
dart2js -o build/web/main.dart.js web/main.dart
```

**Comment by zoechi** [comment] 2015-10-09 11:06
Could be related to https://github.com/mezoni/libffi6_extension/blob/master/lib/transformer.dart#L55
otherwise I give up :-/

**Comment by mezoni** [comment] 2015-10-10 19:17
I am author of the problematic software `libffi6_extension`.

It is not a problematic software, but all the problems come from the fact that the authors of this software for years (read: at the outset) ignores the issues about self-installable packages (by eg. native extension).

This is one of the reasons why I stopped to respect programmers from Google.

Another reasons why I stopped to respect programmers from Google is that the these programmers loves to make promises and then forget what they promised.

You can tell me - hey, man, that kind of nonsense are you talking about?

But I can answer - I am talking about that they are promised to solve problem with self-installable packages, but as I know now they will never solve this.

All the problems come only from authors of this software...

**Comment by emilniklas** [comment] 2015-10-10 19:26
I think this is somewhat besides the point here. The software Dart, as well as the libffi package work fine, it's just that Pub handles dependencies poorly on the specific command `pub build` – or I might have missed something. But that's why this issue was filed!

**Comment by mezoni** [comment] 2015-10-10 19:46
@emilniklas 

You do not know problem.
Problem is more deeply.
Problem are in `pub` and in `barback`.
There is no room in these to cover all Dart features.
They very limit usage of Dart becuase only these two software responsible for correct installation of user specified Dart software (packages and their dependencies of differnt kinds) .

I have long experience is it the hard way to corretly install cross-platform binaries with different bitneess through the pub and barback.

This is only possible with the use of unsafe tricks.

And I can say that all the problems come from the fact that the authors of this software not want solve for years these problems (correctness installations of cross-platform binaries).

**Comment by mezoni** [comment] 2015-10-10 19:55
>> This is only possible with the use of unsafe tricks.

These unsafe tricks with `pub` and `barback` will sooner or later manifest itself with a bad hand.

Ask authors packages with binary packaes (if you can find those) how they to solve these problems?
And they are (if you can find any) will answer - `in no way`.
Because this is not supported.
The only idiot who is trying to do something in this direction, that's me.

But I'm tired being an idiot.

**Comment by mezoni** [comment] 2015-10-10 20:11
>> nex3 added enhancement pub build labels a day ago

When maintainer added this label then he (she) even does not understands the problem.
Only Günter Zöchbauer understands the problem when he point at the problematic code.
But problem was even not in this code.
Problem was (and exists) in the way on how to performed this trick.

Unsafe tricks are the following (missing in `pub` and `barback`):
- Run some code non-simultaneously with similar code
- Change current directory (and restore it) within the code which executes concurrently (but should have possibility to run non-simultaneously with similar code)

Here is result of these tricks as you reported.

file:///Users/emilpersson/.pub-cache/hosted/pub.dartlang.org/libffi6_extension-0.0.6/lib/src/web/main.dart: Exception: Cannot read file:///Users/emilpersson/.pub-cache/hosted/pub.dartlang.org/libffi6_extension-0.0.6/lib/src/web/main.dart because it is outside of the build environment.

**Comment by mezoni** [comment] 2015-10-11 16:42
@emilniklas

Your issue have at least one benefit.
After reading it I came to the conclusion that the way of installing binaries (that I am using) does not support package resolution configuration.
Now it supports them:

[var context = PackageContext.findAll(_workingDirectory);](https://github.com/mezoni/libffi6_extension/blob/8101a98a71ebed158e841a016c2b3c6909e95dec/lib/transformer.dart#L55)

Next time, when you will have a problem with `binary.dart` software, please, contact me directly.
I always responsible to solving any problems and find solution (if this have a reason).

**Comment by emilniklas** [comment] 2015-10-14 20:30
@mezoni has succeeded in working around this issue, and since I don't know what exactly was/is the problem, I won't close this issue. However if anyone else judges this issue to be solved, please feel free to close it.

**Comment by jodinathan** [comment] 2016-11-04 22:03
Hi,

I am having an issue but I am not sure if related.
I need to remove this class structure from the js file

["", "package:raoni_global/src/annotations.dart",, V, {
    "^": "",
    Default: {
      "^": "Object;value>"
    }

this doesn't seem to work:

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    - 'package:angular2/common.dart#FORM_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
    resolved_identifiers:
        BrowserClient: 'package:http/browser_client.dart'
        Client: 'package:http/http.dart'
- dart_to_js_script_rewriter:
    $exclude: "package:raoni_global/src/annotations.dart"

**Comment by zoechi** [comment] 2016-11-05 10:11
Where does "this class structure" come from? 
I'm pretty sure `dart_to_js_script_rewriter` doesn't help here (it just changes script tags).
I guess you meant `$dart2js`.
If you want to remove code from a code file you probably need to write custom a transformer.
or just remove it from the source manually ;-)

**Comment by matanlurey** [comment] 2018-03-24 18:12
We are no longer supporting transformers or `pub serve/build` going forward (this tooling has moved elsewhere into the https://github.com/dart-lang/build repository and https://github.com/dart-lang/webdev CLI) so a fix for this is not planned. 

We'll be updating the tooling section of the Dart website in the coming weeks with more formal documentation on how to get started.

**Closed by matanlurey** 2018-03-24 18:12 UTC
Labels: enhancement, not planned, pub build
