### ISSUE TITLE
pub upgrade, pub build fails with transformers on latest 1.14 dev build

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub#1379] opened 2016-01-13 21:59 UTC
_From @kevmoo on January 13, 2016 18:58_

Dart VM version: 1.14.0-dev.7.0

Also on bleeding edge - 5c2125c9af35e5f198631483a20caa39634d660f

Mac

Repo:
* sync https://github.com/dart-lang/polymer-dart
* `pub upgrade` or `pub build test`

```
Precompiling dependencies...
Loading source assets...
Loading observe and smoke/src/default_transformer transformers...
Unable to spawn isolate: Unhandled exception:
Load Error for "file:///b/build/slave/dart-sdk-mac-dev/build/sdk/third_party/pkg/pub/bin/pub.dart": Error loading file:///b/build/slave/dart-sdk-mac-dev/build/sdk/third_party/pkg/pub/bin/pub.dart:
  FileSystemException: Cannot open file, path = '/b/build/slave/dart-sdk-mac-dev/build/sdk/third_party/pkg/pub/bin/pub.dart' (OS Error: No such file or directory, errno = 2)
#0      _asyncLoadErrorCallback (dart:_builtin:155)
#1      _asyncLoadError (dart:_builtin:566)
#2      _handleLoaderReply (dart:_builtin:383)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

_Copied from original issue: dart-lang/sdk#25423_

**Comment by kevmoo** [comment] 2016-01-13 22:37
Also seeing it on Linux - Dart VM version: 1.14.0-dev.7.0

https://travis-ci.org/angular/angular/jobs/102216130#L521

**Comment by nex3** [comment] 2016-01-13 23:16
I haven't finished investigating this, but at first blush I don't believe it's a pub bug. It works fine with dart-lang/sdk@80702cb2722f70906d4f2c5a32b0e2a14ad8aa20 and breaks with dart-lang/sdk@5c2125c9af35e5f198631483a20caa39634d660f. [Between those two revisions](https://github.com/dart-lang/sdk/compare/80702cb2722f70906d4f2c5a32b0e2a14ad8aa20...5c2125c9af35e5f198631483a20caa39634d660f), there are no changes to the revision from which pub was pulled—and thus no changes to pub. I think this has something to do with package resolution changing in a backwards-incompatible way.

**Comment by nex3** [comment] 2016-01-13 23:33
I can reproduce a different error, but I can't reproduce the one printed here. Is it sufficient to just run `git clone https://github.com/dart-lang/polymer-dart`, `cd polymer-dart`, and `pub get` with Dart 1.14.0-edge.5c2125c9af35e5f198631483a20caa39634d660f?

**Comment by kevmoo** [comment] 2016-01-13 23:36
This is `pub get` at Dart VM version: 1.14.0-edge.5c2125c9af35e5f198631483a20caa39634d660f

Against polymer-dart 9bbad6686ecb1b702a61d581a1d1b3d2c52f9b56

```
Unable to spawn isolate: Unhandled exception:
Load Error for "package:pub/src/command_runner.dart": Could not resolve a package location for base at file:///Users/kevmoo/source/github/dart/sdk/third_party/pkg/pub/bin/pub.dart
#0      _asyncLoadErrorCallback (dart:_builtin:155)
#1      _asyncLoadError (dart:_builtin:566)
#2      _loadPackage (dart:_builtin:605)
#3      _loadPackage.<anonymous closure> (dart:_builtin:621)
#4      _handlePackagesReply (dart:_builtin:464)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by kevmoo** [comment] 2016-01-13 23:38
with --trace

```
ERR : Unable to spawn isolate: Unhandled exception:
    | Load Error for "package:pub/src/command_runner.dart": Could not resolve a package location for base at file:///Users/kevmoo/source/github/dart/sdk/third_party/pkg/pub/bin/pub.dart
    | #0      _asyncLoadErrorCallback (dart:_builtin:155)
    | #1      _asyncLoadError (dart:_builtin:566)
    | #2      _loadPackage (dart:_builtin:605)
    | #3      _loadPackage.<anonymous closure> (dart:_builtin:621)
    | #4      _handlePackagesReply (dart:_builtin:464)
    | #5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
FINE: Exception type: IsolateSpawnException
FINE: dart:isolate                                           Isolate.spawn
    | package:pub/src/dart.dart 181                          runInIsolate.<async>.<fn>.<async>
    | ===== asynchronous gap ===========================
    | package:pub                                            runInIsolate.<async>.<fn>
    | package:pub/src/io.dart 852                            withTempDir.<fn>.<fn>
    | dart:async                                             Future.Future.sync
    | package:pub/src/io.dart 852                            withTempDir.<fn>
    | dart:async                                             Future.Future.sync
    | package:pub/src/io.dart 850                            withTempDir
    | package:pub/src/dart.dart 177                          runInIsolate.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                             Future.Future.microtask
    | package:pub/src/dart.dart                              runInIsolate
    | package:pub/src/barback/transformer_isolate.dart 78    TransformerIsolate.spawn.<fn>
    | ===== asynchronous gap ===========================
    | dart:async                                             _Future.then
    | package:pub/src/barback/transformer_isolate.dart 57    TransformerIsolate.spawn
    | package:pub/src/barback/transformer_loader.dart 57     TransformerLoader.load.<async>.<fn>
    | package:pub/src/log.dart 393                           progress
    | package:pub/src/barback/transformer_loader.dart 56     TransformerLoader.load.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                             Future.Future.microtask
    | package:pub/src/barback/transformer_loader.dart        TransformerLoader.load
    | package:pub/src/barback/load_all_transformers.dart 87  loadAllTransformers.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                             Future.Future.microtask
    | package:pub/src/barback/load_all_transformers.dart     loadAllTransformers
    | package:pub/src/barback/asset_environment.dart 513     AssetEnvironment._load.<fn>.<async>.<fn>.<async>.<fn>.<async>
    | ===== asynchronous gap ===========================
    | package:pub                                            AssetEnvironment._load.<fn>.<async>.<fn>.<async>.<fn>
    | package:pub/src/log.dart 393                           progress
    | package:pub/src/barback/asset_environment.dart 512     AssetEnvironment._load.<fn>.<async>.<fn>.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                             Future.Future.sync
    | package:pub/src/barback/asset_environment.dart 672     AssetEnvironment._withStreamErrors
    | package:pub/src/barback/asset_environment.dart 511     AssetEnvironment._load.<fn>.<async>
    | dart:async                                             _SyncCompleter.complete
    | package:pub/src/barback/asset_environment.dart 673     AssetEnvironment._withStreamErrors.<fn>
    | dart:async                                             _SyncCompleter.complete
    | package:pub/src/barback/asset_environment.dart 532     AssetEnvironment._provideSources.<async>
    | dart:async                                             _SyncCompleter.complete
    | package:pub/src/barback/asset_environment.dart 531     AssetEnvironment._provideSources.<async>.<fn>.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                             _asyncThenWrapperHelper
    | package:pub/src/barback/asset_environment.dart         AssetEnvironment._load.<fn>
    | package:pub/src/log.dart 393                           progress
    | package:pub/src/barback/asset_environment.dart 460     AssetEnvironment._load
    | package:pub/src/barback/asset_environment.dart 84      AssetEnvironment.create.<fn>.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                             Future.Future.microtask
    | package:pub/src/barback/asset_environment.dart         AssetEnvironment.create.<fn>
    | package:pub/src/log.dart 393                           progress
    | package:pub/src/barback/asset_environment.dart 76      AssetEnvironment.create
    | package:pub/src/command/build.dart 64                  BuildCommand.onRunTransformerCommand.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                             Future.Future.microtask
    | package:pub/src/command/build.dart                     BuildCommand.onRunTransformerCommand
    | package:pub/src/command/barback.dart 58                BarbackCommand.run
    | package:args/command_runner.dart 178                   CommandRunner.runCommand.<fn>
    | dart:async                                             Future.Future.sync
    | package:args/command_runner.dart 131                   CommandRunner.runCommand
    | package:pub/src/command_runner.dart 130                PubCommandRunner.runCommand.<async>.<fn>
    | dart:async                                             Future.Future.sync
    | package:pub/src/utils.dart 111                         captureErrors.<fn>
    | package:stack_trace                                    Chain.capture
    | package:pub/src/utils.dart 125                         captureErrors
    | package:pub/src/command_runner.dart 130                PubCommandRunner.runCommand.<async>
    | dart:async                                             _SyncCompleter.complete
    | package:pub/src/command_runner.dart 216                PubCommandRunner._validatePlatform.<async>
---- End log transcript ----
```

**Comment by nex3** [comment] 2016-01-13 23:43
That's a different error than you posted before, and also a different error than the one I'm seeing. Do you know what changed between your first report and the error you're seeing now? Can you still reproduce the first error?

**Comment by nex3** [comment] 2016-01-13 23:58
Bisecting indicates that the error—at least the one I'm seeing—originated in dart-lang/sdk@6d066c7e53f82b70c3a5bfc4916d8a0c9a26a6f4. I suspect that some isolate API got changed in a backwards-incompatible way as part of that change.

**Comment by nex3** [comment] 2016-01-14 00:38
Okay, I've found three issues (linked above) that seem to be causing the various errors we've seen. Since I've confirmed that this is not a bug in pub, I'm closing out this issue.

**Closed by nex3** 2016-01-14 00:38 UTC
Labels: CRITICAL
