### ISSUE TITLE
Publishing a package with default description should be illegal

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/pub#1992] opened 2018-10-18 14:55 UTC
Many flutter packages published on pub have the description "A new flutter package project.". That's probably because that's the default description in the pubspec as generated by flutter create. There should be some kind of a way to remind users to change that to something more useful.

Maybe pub publish can warn if nothing meaningful has been provided?

(From https://github.com/flutter/flutter/issues/23240)

**Comment by sigurdm** [comment] 2023-01-17 14:50
This is a duplicate of https://github.com/dart-lang/pub-dev/issues/5512 .

**Closed by sigurdm** 2023-01-17 14:50 UTC
