### ISSUE TITLE
pub publish fails with 'The method 'toList' was called on null.'

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/pub#1921] opened 2018-06-14 08:12 UTC
Publishing this repo: https://github.com/MikeMitterer/dart-console_log_handler
showed me the error message from above

Dart VM version: 2.0.0-dev.62.0 (Wed Jun 13 16:50:22 2018 +0200) on "macos_x64"

```bash
 pub --trace publish
Publishing console_log_handler 1.0.5 to https://pub.dartlang.org:
|-- .analysis_options.yaml
|-- .gitignore
|-- CHANGELOG.md
|-- LICENSE
|-- README.md
|-- build.jenkins
|-- dart_test.yaml
|-- doc
|   '-- _resources
|       |-- screenshot_browser.png
|       '-- screenshot_console.png
|-- example
|   |-- browser
|   |   |-- pubspec.yaml
|   |   '-- web
|   |       |-- favicon.png
|   |       |-- index.html
|   |       '-- main.dart
|   '-- console
|       |-- .gitignore
|       |-- LICENSE
|       |-- analysis_options.yaml
|       |-- bin
|       |   '-- main.dart
|       '-- pubspec.yaml
|-- lib
|   |-- console_log_handler.dart
|   |-- print_log_handler.dart
|   '-- shared
|       '-- log_handler.dart
|-- pubspec.yaml
|-- test
|   '-- unit
|       |-- logging
|       |   |-- ConsoleLogging_test.dart
|       |   '-- PrintLogging_test.dart
|       '-- simple
|           '-- JsonPrettyPrint_test.dart
'-- tool
    '-- grind.dart
The method 'toList' was called on null.
Receiver: null
Tried calling: toList()
dart:core                                                 Object.noSuchMethod
package:analyzer/src/dart/analysis/file_state.dart 875    FileSystemState.getFilesForPath
package:analyzer/src/dart/analysis/file_tracker.dart 220  FileTracker.verifyApiSignature.<fn>
package:front_end/src/base/performance_logger.dart 34     PerformanceLog.run
package:analyzer/src/dart/analysis/file_tracker.dart 218  FileTracker.verifyApiSignature
package:analyzer/src/dart/analysis/driver.dart 906        AnalysisDriver.parseFileSync
package:analyzer/src/dart/analysis/session.dart 120       AnalysisSessionImpl.getParsedAstSync
package:pub/src/dart.dart 129                             AnalysisContextManager.parse
package:pub/src/dart.dart 144                             AnalysisContextManager.parseImportsAndExports
package:pub/src/validator/strict_dependencies.dart 40     StrictDependenciesValidator._findPackages
dart:core                                                 _SyncIterator.moveNext
package:pub/src/validator/strict_dependencies.dart 86     StrictDependenciesValidator._validateLibBin
package:pub/src/validator/strict_dependencies.dart 76     StrictDependenciesValidator.validate
===== asynchronous gap ===========================
dart:async                                                _AsyncAwaitCompleter.completeError
package:pub/src/validator/strict_dependencies.dart        StrictDependenciesValidator.validate
---- Log transcript ----
FINE: Pub 2.0.0-dev.62.0
IO  : Spawning "git --version" in /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler/.
IO  : Finished git. Exit code 0.
    | stdout:
    | | git version 2.17.0
    | Nothing output on stderr.
FINE: Determined git command null.
IO  : Spawning "git check-ignore --quiet ." in /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler/.
IO  : Finished git. Exit code 1.
    | Nothing output on stdout.
    | Nothing output on stderr.
IO  : Spawning "git ls-files --cached --others --exclude-standard" in /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler/.
IO  : Finished git. Exit code 0.
    | stdout:
    | | .analysis_options.yaml
    | | .gitignore
    | | CHANGELOG.md
    | | LICENSE
    | | README.md
    | | build.jenkins
    | | dart_test.yaml
    | | doc/_resources/screenshot_browser.png
    | | doc/_resources/screenshot_console.png
    | | example/browser/pubspec.yaml
    | | example/browser/web/favicon.png
    | | example/browser/web/index.html
    | | example/browser/web/main.dart
    | | example/console/.gitignore
    | | example/console/LICENSE
    | | example/console/analysis_options.yaml
    | | example/console/bin/main.dart
    | | example/console/pubspec.yaml
    | | lib/console_log_handler.dart
    | | lib/print_log_handler.dart
    | | lib/shared/log_handler.dart
    | | pubspec.yaml
    | | test/unit/logging/ConsoleLogging_test.dart
    | | test/unit/logging/PrintLogging_test.dart
    | | test/unit/simple/JsonPrettyPrint_test.dart
    | | tool/grind.dart
    | Nothing output on stderr.
FINE: Archiving and publishing console_log_handler 1.0.5 (.).
MSG : Publishing console_log_handler 1.0.5 to https://pub.dartlang.org:
    | |-- .analysis_options.yaml
    | |-- .gitignore
    | |-- CHANGELOG.md
    | |-- LICENSE
    | |-- README.md
    | |-- build.jenkins
    | |-- dart_test.yaml
    | |-- doc
    | |   '-- _resources
    | |       |-- screenshot_browser.png
    | |       '-- screenshot_console.png
    | |-- example
    | |   |-- browser
    | |   |   |-- pubspec.yaml
    | |   |   '-- web
    | |   |       |-- favicon.png
    | |   |       |-- index.html
    | |   |       '-- main.dart
    | |   '-- console
    | |       |-- .gitignore
    | |       |-- LICENSE
    | |       |-- analysis_options.yaml
    | |       |-- bin
    | |       |   '-- main.dart
    | |       '-- pubspec.yaml
    | |-- lib
    | |   |-- console_log_handler.dart
    | |   |-- print_log_handler.dart
    | |   '-- shared
    | |       '-- log_handler.dart
    | |-- pubspec.yaml
    | |-- test
    | |   '-- unit
    | |       |-- logging
    | |       |   |-- ConsoleLogging_test.dart
    | |       |   '-- PrintLogging_test.dart
    | |       '-- simple
    | |           '-- JsonPrettyPrint_test.dart
    | '-- tool
    |     '-- grind.dart
FINE: Creating .tar.gz stream containing:
    | ./.analysis_options.yaml
    | ./.gitignore
    | ./CHANGELOG.md
    | ./LICENSE
    | ./README.md
    | ./build.jenkins
    | ./dart_test.yaml
    | ./doc/_resources/screenshot_browser.png
    | ./doc/_resources/screenshot_console.png
    | ./example/browser/pubspec.yaml
    | ./example/browser/web/favicon.png
    | ./example/browser/web/index.html
    | ./example/browser/web/main.dart
    | ./example/console/.gitignore
    | ./example/console/LICENSE
    | ./example/console/analysis_options.yaml
    | ./example/console/bin/main.dart
    | ./example/console/pubspec.yaml
    | ./lib/console_log_handler.dart
    | ./lib/print_log_handler.dart
    | ./lib/shared/log_handler.dart
    | ./pubspec.yaml
    | ./test/unit/logging/ConsoleLogging_test.dart
    | ./test/unit/logging/PrintLogging_test.dart
    | ./test/unit/simple/JsonPrettyPrint_test.dart
    | ./tool/grind.dart
IO  : Spawning "git ls-files --cached --others --exclude-standard" in /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler/.
IO  : Finished git. Exit code 0.
    | stdout:
    | | .analysis_options.yaml
    | | .gitignore
    | | CHANGELOG.md
    | | LICENSE
    | | README.md
    | | build.jenkins
    | | dart_test.yaml
    | | doc/_resources/screenshot_browser.png
    | | doc/_resources/screenshot_console.png
    | | example/browser/pubspec.yaml
    | | example/browser/web/favicon.png
    | | example/browser/web/index.html
    | | example/browser/web/main.dart
    | | example/console/.gitignore
    | | example/console/LICENSE
    | | example/console/analysis_options.yaml
    | | example/console/bin/main.dart
    | | example/console/pubspec.yaml
    | | lib/console_log_handler.dart
    | | lib/print_log_handler.dart
    | | lib/shared/log_handler.dart
    | | pubspec.yaml
    | | test/unit/logging/ConsoleLogging_test.dart
    | | test/unit/logging/PrintLogging_test.dart
    | | test/unit/simple/JsonPrettyPrint_test.dart
    | | tool/grind.dart
    | Nothing output on stderr.
IO  : Spawning "git ls-files --cached --others --exclude-standard" in /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler/.
IO  : Finished git. Exit code 0.
    | stdout:
    | | .analysis_options.yaml
    | | .gitignore
    | | CHANGELOG.md
    | | LICENSE
    | | README.md
    | | build.jenkins
    | | dart_test.yaml
    | | doc/_resources/screenshot_browser.png
    | | doc/_resources/screenshot_console.png
    | | example/browser/pubspec.yaml
    | | example/browser/web/favicon.png
    | | example/browser/web/index.html
    | | example/browser/web/main.dart
    | | example/console/.gitignore
    | | example/console/LICENSE
    | | example/console/analysis_options.yaml
    | | example/console/bin/main.dart
    | | example/console/pubspec.yaml
    | | lib/console_log_handler.dart
    | | lib/print_log_handler.dart
    | | lib/shared/log_handler.dart
    | | pubspec.yaml
    | | test/unit/logging/ConsoleLogging_test.dart
    | | test/unit/logging/PrintLogging_test.dart
    | | test/unit/simple/JsonPrettyPrint_test.dart
    | | tool/grind.dart
    | Nothing output on stderr.
IO  : Spawning "git ls-files --cached --others --exclude-standard" in /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler/.
IO  : Finished git. Exit code 0.
    | stdout:
    | | .analysis_options.yaml
    | | .gitignore
    | | CHANGELOG.md
    | | LICENSE
    | | README.md
    | | build.jenkins
    | | dart_test.yaml
    | | doc/_resources/screenshot_browser.png
    | | doc/_resources/screenshot_console.png
    | | example/browser/pubspec.yaml
    | | example/browser/web/favicon.png
    | | example/browser/web/index.html
    | | example/browser/web/main.dart
    | | example/console/.gitignore
    | | example/console/LICENSE
    | | example/console/analysis_options.yaml
    | | example/console/bin/main.dart
    | | example/console/pubspec.yaml
    | | lib/console_log_handler.dart
    | | lib/print_log_handler.dart
    | | lib/shared/log_handler.dart
    | | pubspec.yaml
    | | test/unit/logging/ConsoleLogging_test.dart
    | | test/unit/logging/PrintLogging_test.dart
    | | test/unit/simple/JsonPrettyPrint_test.dart
    | | tool/grind.dart
    | Nothing output on stderr.
IO  : Spawning "git ls-files --cached --others --exclude-standard" in /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler/.
IO  : Finished git. Exit code 0.
    | stdout:
    | | .analysis_options.yaml
    | | .gitignore
    | | CHANGELOG.md
    | | LICENSE
    | | README.md
    | | build.jenkins
    | | dart_test.yaml
    | | doc/_resources/screenshot_browser.png
    | | doc/_resources/screenshot_console.png
    | | example/browser/pubspec.yaml
    | | example/browser/web/favicon.png
    | | example/browser/web/index.html
    | | example/browser/web/main.dart
    | | example/console/.gitignore
    | | example/console/LICENSE
    | | example/console/analysis_options.yaml
    | | example/console/bin/main.dart
    | | example/console/pubspec.yaml
    | | lib/console_log_handler.dart
    | | lib/print_log_handler.dart
    | | lib/shared/log_handler.dart
    | | pubspec.yaml
    | | test/unit/logging/ConsoleLogging_test.dart
    | | test/unit/logging/PrintLogging_test.dart
    | | test/unit/simple/JsonPrettyPrint_test.dart
    | | tool/grind.dart
    | Nothing output on stderr.
IO  : Reading binary file ./README.md.
IO  : Read 1772 bytes from ./README.md.
IO  : Spawning "tar --format=ustar --create --gzip --directory /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler/. @/dev/stdin" in /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler/.
ERR : The method 'toList' was called on null.
    | Receiver: null
    | Tried calling: toList()
FINE: Exception type: NoSuchMethodError
ERR : dart:core                                                 Object.noSuchMethod
    | package:analyzer/src/dart/analysis/file_state.dart 875    FileSystemState.getFilesForPath
    | package:analyzer/src/dart/analysis/file_tracker.dart 220  FileTracker.verifyApiSignature.<fn>
    | package:front_end/src/base/performance_logger.dart 34     PerformanceLog.run
    | package:analyzer/src/dart/analysis/file_tracker.dart 218  FileTracker.verifyApiSignature
    | package:analyzer/src/dart/analysis/driver.dart 906        AnalysisDriver.parseFileSync
    | package:analyzer/src/dart/analysis/session.dart 120       AnalysisSessionImpl.getParsedAstSync
    | package:pub/src/dart.dart 129                             AnalysisContextManager.parse
    | package:pub/src/dart.dart 144                             AnalysisContextManager.parseImportsAndExports
    | package:pub/src/validator/strict_dependencies.dart 40     StrictDependenciesValidator._findPackages
    | dart:core                                                 _SyncIterator.moveNext
    | package:pub/src/validator/strict_dependencies.dart 86     StrictDependenciesValidator._validateLibBin
    | package:pub/src/validator/strict_dependencies.dart 76     StrictDependenciesValidator.validate
    | ===== asynchronous gap ===========================
    | dart:async                                                _AsyncAwaitCompleter.completeError
    | package:pub/src/validator/strict_dependencies.dart        StrictDependenciesValidator.validate
---- End log transcript ----
```

**Comment by natebosch** [comment] 2018-06-14 17:05
Duplicate of #1919 

This should be fixed in the next release of the SDK, unfortunately for now the best workaround is to revert to the dev.61 SDK.

**Closed by natebosch** 2018-06-14 17:05 UTC
