### ISSUE TITLE
`pub downgrade` not able to resolve

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub#1285] opened 2015-06-15 20:29 UTC
The dependencies of my package https://github.com/bwu-dart/bwu_utils are quite narrow but I wasn't able to figure out how to make `pub downgrade` complete.
I have the suspicion it is related to the pre-release version in the dependency `^0.1.0-dev.12` (just a hunch)
`pub upgrade` works fine though.

**Comment by nex3** [comment] 2015-06-15 23:19
This isn't too surprising. In general, the set of oldest versions you support are going to have more diverse sets of dependencies than the set of newest versions you support, since they're more likely to have been released at diverse points in time. This means that the naïve solution is likely to be further from correct, making the version solver do more work to get to something valid, even for a relatively small number of packages.

The logic for downgrading is the same as for upgrading, so I'm going to mark this as a duplicate of #912.

**Closed by nex3** 2015-06-15 23:19 UTC

**Comment by zoechi** [comment] 2015-06-17 09:24
This seems unlikely because the constraints are quite narrow. Some support to find the cause is helpful anyway.

**Comment by nex3** [comment] 2015-06-17 20:24
Narrow helps, but it's not going to be enough sometimes. The algorithm is fundamentally exponential, which means that in a bad case even a very small number of inputs can produce a very large runtime.

**Comment by zoechi** [comment] 2015-06-17 20:37
You are right, I investigated further and couldn't reduce to a single dependency, removing a random one helps.
