### ISSUE TITLE
What is the reason for this error? Has anyone ever encountered it

### ISSUE THREAD

**Issue by asijack** [dart-lang/pub#3549] opened 2022-09-06 03:19 UTC
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Running "flutter pub get" in b__module...
Bad state: No element
dart:core                                           List.first
package:pub/src/source/git.dart 574:18              BoundGitSource._firstRevision
===== asynchronous gap ===========================
package:pub/src/source/git.dart 463:7               BoundGitSource._ensureRevision
===== asynchronous gap ===========================
package:pub/src/source/git.dart 301:5               BoundGitSource._describeUncached
===== asynchronous gap ===========================
package:pool/pool.dart 127:14                       Pool.withResource
===== asynchronous gap ===========================
package:pub/src/source/cached.dart 39:12            CachedSource.doDescribe
===== asynchronous gap ===========================
package:pub/src/source.dart 240:15                  BoundSource.describe
===== asynchronous gap ===========================
package:pub/src/solver/package_lister.dart 191:11   PackageLister.incompatibilitiesFor
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 372:12   VersionSolver._choosePackageVersion
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 98:18    VersionSolver.solve.<fn>
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 956:14           BoundHostedSource.withPrefetching.<fn>
===== asynchronous gap ===========================
package:pub/src/rate_limited_scheduler.dart 110:14  RateLimitedScheduler.withPrescheduling
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 955:12           BoundHostedSource.withPrefetching
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 94:14    VersionSolver.solve
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 252:16              Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 52:5               GetCommand.runProtected
This is an unexpected error. Please run

    dart pub --trace get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub get failed (1; and include the logs in an issue on https://github.com/dart-lang/pub/issues/new)

**Comment by sigurdm** [comment] 2022-09-06 07:29
Closing this as a duplicate of https://github.com/dart-lang/pub/issues/3040

You are referencing a git revision that doesn't exist. We need to give better error reporting here.

**Closed by sigurdm** 2022-09-06 07:29 UTC
