### ISSUE TITLE
Faster dev loop for polymer apps when running in a real server

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub#1329] opened 2015-09-02 14:44 UTC
_From @DartBot on June 6, 2014 1:16_

*This issue was originally filed by @Andersmholmgren*
_____
Pub serve gives a reasonably fast dev loop in the editor. However, it runs it's own server.

There are times where you need to run in a real server (shelf in my case). For example I am building a polymer ui that runs in an iframe and relies on comms with the host frame to function. I can't think of a way to get this to work with pub serve.

But manually running pub build (which is taking 17s for a small app on a fast mac pro) is killing my dev loop.

Would be great if pub supported incrementally updating the build/web dir

_Copied from original issue: dart-lang/sdk#19264_

**Comment by mit-mit** [comment] 2015-09-02 14:44
_From @kevmoo on June 6, 2014 5:27_

Nathan and I discussed today building a shelf_pub_serve (or similar) package/handler that proxies to `pub serve` from shelf.

I'm going to leave this open as a request for pub/barback: allow programatic access/instantiation of barback
______
 cc @nex3.
*Removed [Type-Defect](../labels/Type-Defect) label.*
*Added [Type-Enhancement](../labels/Type-Enhancement), [Pub-Serve](../labels/Pub-Serve), [Triaged](../labels/Triaged) labels.*

**Comment by nex3** [comment] 2015-09-02 18:09
Duplicate of #948.

**Closed by nex3** 2015-09-02 18:09 UTC
Labels: enhancement, pub serve
