### ISSUE TITLE
"Publish" workflow analyzes `.pubignore`d files

### ISSUE THREAD

**Issue by osa1** [dart-lang/pub#4035] opened 2023-10-27 07:23 UTC
In https://github.com/google/protobuf.dart we use `dart-lang/ecosystem/.github/workflows/publish.yaml` workflow to perform publishing checks.

Currently this workflow fails in `dart analyze` step because `dart analyze` analyzes tests, and tests need a build step to run (`make protos`).

This behavior makes sense when working on the package, however when doing publication validation, we need to either

1. Run the build step `make protos` before `dart analyze`, which currently the workflow does not support
    - Note that the git repo has two packages, and we only want to do this in one of them

2. Or, make it `.pubignore`-aware

I feel like (2) makes sense in general as analyzing with non-published files can actually hide problems, for example if I accidentally add a file to `.pubignore` that's actually needed by the package.

(https://github.com/google/protobuf.dart/pull/894 adds the tests to `.pubignore`)

**Comment by mosuem** [comment] 2023-10-27 08:55
Transferred as this is mainly a feature request to `dart pub publish`

**Comment by sigurdm** [comment] 2023-10-30 15:41
Yeah - we need a good way to remove those files from analysis.

Duplicate of: https://github.com/dart-lang/pub/issues/3696

**Closed by sigurdm** 2023-10-30 15:41 UTC
