### ISSUE TITLE
Log file not created

### ISSUE THREAD

**Issue by DickVG** [dart-lang/pub#3481] opened 2022-07-02 13:04 UTC
[.pub-cache\hosted\pub.dartlang.org\video_player_web-2.0.7] flutter pub get
Running "flutter pub get" in video_player_web-2.0.7...          
Null check operator used on a null value
package:pub/src/entrypoint.dart 157:60                           Entrypoint.lockFilePath
package:pub/src/entrypoint.dart 100:21                           Entrypoint._loadLockFile
package:pub/src/entrypoint.dart 97:42                            Entrypoint.lockFile
package:pub/src/entrypoint.dart 286:21                           Entrypoint.acquireDependencies.<fn>
package:pub/src/entrypoint.dart 280:68                           Entrypoint.acquireDependencies.<fn>
package:pub/src/log.dart 428:18                                  progress
package:pub/src/entrypoint.dart 280:26                           Entrypoint.acquireDependencies
package:pub/src/command/get.dart 52:22                           GetCommand.runProtected
package:pub/src/command.dart 183:45                              PubCommand.run.<fn>
package:pub/src/command.dart 183:33                              PubCommand.run.<fn>
dart:async                                                       new Future.sync
package:pub/src/utils.dart 109:12                                captureErrors.wrappedCallback
dart:async                                                       runZonedGuarded
package:pub/src/utils.dart 126:5                                 captureErrors
package:pub/src/command.dart 183:13                              PubCommand.run
package:args/command_runner.dart 209:27                          CommandRunner.runCommand
package:pub/src/command_runner.dart 174:24                       PubCommandRunner.runCommand
package:pub/src/command_runner.dart 159:20                       PubCommandRunner.run
package:dartdev/dartdev.dart 45:56                               runDartdev
C:\b\s\w\ir\cache\builder\sdk\pkg\dartdev\bin\dartdev.dart 11:9  main
This is an unexpected error. The full log and other details are collected in:

    C:\scr\flutter\.pub-cache\log\pub_log.txt

Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.

![Capture](https://user-images.githubusercontent.com/66368297/177002007-5d649a36-6de1-4f0e-a7a5-71f81f619bc6.PNG)

**Comment by YowFung** [comment] 2022-07-06 06:54
Same issue.

**Comment by sigurdm** [comment] 2022-07-07 09:35
Duplicate of https://github.com/dart-lang/pub/issues/3463 - there is a pending fix to give a better error message. Pub get is not supposed to run from inside the pub-cache.

**Closed** 2022-07-07 09:36 UTC
