### ISSUE TITLE
Can't add and error Dio dependencies

### ISSUE THREAD

**Issue by daniahnaf22** [dart-lang/pub#3871] opened 2023-04-12 03:55 UTC
flutter pub add dio
Resolving dependencies...
Invalid hexadecimal code unit U+0000. (at offset 0)
package:convert/src/utils.dart 34:3          digitForCodeUnit  
package:convert/src/hex/decoder.dart 173:22  _decode
package:convert/src/hex/decoder.dart 31:5    HexDecoder.convert
dart:convert                                 Codec.decode
package:pub/src/utils.dart 335:43            hexDecode
package:pub/src/source/hosted.dart 852:14    HostedSource.sha256FromCache
package:pub/src/source/hosted.dart 764:29    HostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/system_cache.dart 230:20     SystemCache.downloadPackage
===== asynchronous gap ===========================
package:pub/src/solver/result.dart 70:20     SolveResult.downloadCachedPackages.<fn>.<fn>
===== asynchronous gap ===========================
package:pub/src/solver/result.dart 68:18     SolveResult.downloadCachedPackages.<fn>
===== asynchronous gap ===========================
package:pub/src/solver/result.dart 65:32     SolveResult.downloadCachedPackages
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 372:25       Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/add.dart 242:7       AddCommand.runProtected
This is an unexpected error. The full log and other details are collected in:

    C:\Users\Dani Ahnaf\AppData\Local\Pub\Cache\log\pub_log.txt

Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.
pub finished with exit code 65
![Capture](https://user-images.githubusercontent.com/84891242/231345279-14584178-3045-4cb7-95e4-783e82c226b1.PNG)

**Comment by sigurdm** [comment] 2023-04-12 07:59
Closing this as duplicate of https://github.com/dart-lang/pub/issues/3867

**Closed by sigurdm** 2023-04-12 07:59 UTC
