### ISSUE TITLE
(1.24.3) pub get spins forever on a mix of dart_style, http, and test

### ISSUE THREAD

**Issue by jakobr-google** [dart-lang/pub#1825] opened 2018-03-14 10:53 UTC
Steps to reproduce:

1. Create `pubspec.yaml` with these contents:

```yaml
name: publoop

dependencies:
  dart_style: '>=1.0.7 <2.0.0'
  http: '>=0.11.1 <0.12.0'

dev_dependencies:
  test: '^0.12.0'
```

2. Run `pub get`.

Expected result: Success, dependencies resolved.

Actual result: 

```
jakobr@jakobr-goobuntu:~/tmp/publoop$ pub --version
Pub 1.24.3
jakobr@jakobr-goobuntu:~/tmp/publoop$ pub get
Resolving dependencies... (1:03.7s)^C
jakobr@jakobr-goobuntu:~/tmp/publoop$ 
```

(yeah, I have tried letting it run longer than 1 minute. Travis killed it after waiting for about 50 minutes in dart-lang/discoveryapis_generator#185).

Workaround:

Change the `dart_style` dependency to `>=1.0.7 <=1.0.9+1`. The issue seems to be caused by dart_style 1.0.10 depending on analyzer 0.31.2-alpha.0, which requires SDK >=2.0.0-dev. Which 1.24.3 isn't, but for some reason, pub still tries to go with it.

Removing any one of the dependencies in `pubspec.yaml` also makes the bug disappear. All 3 are needed to cause the loop.

**Comment by nex3** [comment] 2018-03-14 20:21
Duplicate of #912. This isn't actually spinning *forever*, it's just going exponential due to flaws in pub's old algorithm. The new version solver will fix cases like this (although note that it won't be in 1.24, since there are no new 1.x releases being cut).

**Closed by nex3** 2018-03-14 20:21 UTC
