### ISSUE TITLE
dependency overrides not work

### ISSUE THREAD

**Issue by TechComet** [dart-lang/pub#3343] opened 2022-03-17 16:02 UTC
Hi,

It's not override `dart_vlc_ffi` package

```
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  dart_vlc:
    git:
      url: https://github.com/alexmercerind/dart_vlc.git
      path: .
      ref: master


dependency_overrides:
  dart_vlc_ffi:
    git:
      url: https://github.com/alexmercerind/dart_vlc.git
      path: ffi
      ref: master
```

---
flutter --version
```
Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (2 weeks ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2
```

I tested this before some months ago(with old flutter version), It was working

but now show error message
```
Error on line 16, column 11: Invalid description in the "dart_vlc" pubspec on the "dart_vlc_ffi" dependency: "./ffi" is a relative path, but this isn't a local pubspec.
   ╷
16 │     path: ./ffi
   │           ^^^^^
   ╵
pub get failed (65;    ╵)
```

**Comment by sigurdm** [comment] 2022-03-22 11:52
I was not able to reproduce with an even newer flutter.
```yaml
# pubspec.yaml
name: test

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  dart_vlc:
    git:
      url: https://github.com/alexmercerind/dart_vlc.git
      path: .
      ref: master


dependency_overrides:
  dart_vlc_ffi:
    git:
      url: https://github.com/alexmercerind/dart_vlc.git
      path: ffi
      ref: master
```
```
> flutter --version
Flutter 2.11.0-0.0.pre.771 • channel use_package_config_in_build_info • https://github.com/sigurdm/flutter
Framework • revision 4847d81eed (2 weeks ago) • 2022-03-08 11:26:15 +0000
Engine • revision 14b1f3fbc5
Tools • Dart 2.17.0 (build 2.17.0-169.0.dev) • DevTools 2.11.1
> flutter pub get
Warning: You are using these overridden dependencies:
! dart_vlc_ffi 0.1.5+1 from git https://github.com/alexmercerind/dart_vlc.git at 58cbc3 in ffi
Running "flutter pub get" in blah...                             1,762ms
```

It looks like you somehow had a path-dependency in the dart_vlc_ffi `pubspec.yaml` when you ran the command.
But that is not the case now at current master...

**Comment by sigurdm** [comment] 2022-03-22 11:52
Can you make a simple reproduction?

**Comment by mirland** [comment] 2023-01-31 00:28
> I was not able to reproduce with an even newer flutter.

@sigurdm have you tried cleaning the cache? (`flutter pub cache clean`) Because if you have downloaded the dependency before, the error is not happening.

More information [here](https://github.com/felangel/bloc/issues/151#issuecomment-1385978523)
I tested and it's true

**Comment by sigurdm** [comment] 2023-01-31 12:55
@mirland - I looked at your reproduction, and this has nothing to do with dependency_overrides working or not working. This  is the fact that a git-dependency cannot have path dependencies - that is covered by https://github.com/dart-lang/pub/issues/449.

The overridden package in
https://github.com/mirland/floor/commit/64f1eb1e934038f6fc612e8032ea0e5b4dfdfb8b#diff-d3baa3a2182506237b7a481bef5b22b1c0e6d857ccdcbf3a2e5bc9ffdff707bdR16

has a pubspec.yaml with a path-dependency.

**Comment by sigurdm** [comment] 2023-01-31 14:34
Closing this as cannot reproduce.

**Closed by sigurdm** 2023-01-31 14:34 UTC
Labels: needs info

**Comment by dcharkes** [comment] 2023-07-06 16:06
> @mirland - I looked at your reproduction, and this has nothing to do with dependency_overrides working or not working. This is the fact that a git-dependency cannot have path dependencies - that is covered by #449.
> 
> The overridden package in [mirland/floor@64f1eb1#diff-d3baa3a2182506237b7a481bef5b22b1c0e6d857ccdcbf3a2e5bc9ffdff707bdR16](https://github.com/mirland/floor/commit/64f1eb1e934038f6fc612e8032ea0e5b4dfdfb8b#diff-d3baa3a2182506237b7a481bef5b22b1c0e6d857ccdcbf3a2e5bc9ffdff707bdR16)
> 
> has a pubspec.yaml with a path-dependency.

I just ran into the same thing, I have path dependencies within https://github.com/dart-lang/native, and tried to override these path dependencies in my local copy of flutter_tools.

I expected the dependency override to git to override the path dependency.

If this is not a supported workflow, that means I have to add git dependencies instead (which cannot have the packages on the same mono-repo point to the last commit on main).
