### ISSUE TITLE
HTTP error 424: Failed Dependency

### ISSUE THREAD

**Issue by chenmurong** [dart-lang/pub#1906] opened 2018-05-23 07:04 UTC
when i update package,  meet with follow error

Running "flutter packages get" in test3...
HTTP error 424: Failed Dependency
package:pub/src/http.dart 220                                                                  _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33                                                    ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 304                                                         BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 199                                                         BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 372                                                            Entrypoint._get.<fn>
===== asynchronous gap ===========================
package:pub/src/http.dart 274                                                                  withDependencyType
package:pub/src/entrypoint.dart 367                                                            Entrypoint._get
package:pub/src/entrypoint.dart 229                                                            Entrypoint.acquireDependencies.<fn>
dart:async                                                                                     Future.wait
package:pub/src/entrypoint.dart 229                                                            Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 38                                                            GetCommand.run
package:args/command_runner.dart 194                                                           CommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 168                                                        PubCommandRunner.runCommand.<fn>
dart:async                                                                                     new Future.sync
package:pub/src/utils.dart 115                                                                 captureErrors.<fn>
dart:async                                                                                     runZoned
package:pub/src/utils.dart 134                                                                 captureErrors
package:pub/src/command_runner.dart 168                                                        PubCommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 117                                                        PubCommandRunner.run
===== asynchronous gap ===========================
E:\b\build\slave\Windows_Engine\build\src\third_party\dart\third_party\pkg\pub\bin\pub.dart 8  main
This is an unexpected error. Please run

    pub --trace --verbosity=warning get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub get failed (69) -- attempting retry 1 in 1 second...
HTTP error 424: Failed Dependency
package:pub/src/http.dart 220                                                                  _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33                                                    ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 304                                                         BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 199                                                         BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 372                                                            Entrypoint._get.<fn>
===== asynchronous gap ===========================
package:pub/src/http.dart 274                                                                  withDependencyType
package:pub/src/entrypoint.dart 367                                                            Entrypoint._get
package:pub/src/entrypoint.dart 229                                                            Entrypoint.acquireDependencies.<fn>
dart:async                                                                                     Future.wait
package:pub/src/entrypoint.dart 229                                                            Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 38                                                            GetCommand.run
package:args/command_runner.dart 194                                                           CommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 168                                                        PubCommandRunner.runCommand.<fn>
dart:async                                                                                     new Future.sync
package:pub/src/utils.dart 115                                                                 captureErrors.<fn>
dart:async                                                                                     runZoned
package:pub/src/utils.dart 134                                                                 captureErrors
package:pub/src/command_runner.dart 168                                                        PubCommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 117                                                        PubCommandRunner.run
===== asynchronous gap ===========================
E:\b\build\slave\Windows_Engine\build\src\third_party\dart\third_party\pkg\pub\bin\pub.dart 8  main
This is an unexpected error. Please run

    pub --trace --verbosity=warning get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub get failed (69) -- attempting retry 2 in 2 seconds...
HTTP error 424: Failed Dependency
package:pub/src/http.dart 220                                                                  _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33                                                    ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 304                                                         BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 199                                                         BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 372                                                            Entrypoint._get.<fn>
===== asynchronous gap ===========================
package:pub/src/http.dart 274                                                                  withDependencyType
package:pub/src/entrypoint.dart 367                                                            Entrypoint._get
package:pub/src/entrypoint.dart 229                                                            Entrypoint.acquireDependencies.<fn>
dart:async                                                                                     Future.wait
package:pub/src/entrypoint.dart 229                                                            Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 38                                                            GetCommand.run
package:args/command_runner.dart 194                                                           CommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 168                                                        PubCommandRunner.runCommand.<fn>
dart:async                                                                                     new Future.sync
package:pub/src/utils.dart 115                                                                 captureErrors.<fn>
dart:async                                                                                     runZoned
package:pub/src/utils.dart 134                                                                 captureErrors
package:pub/src/command_runner.dart 168                                                        PubCommandRunner.runCommand
===== asynchronous gap ===========================
package:pub/src/command_runner.dart 117                                                        PubCommandRunner.run
===== asynchronous gap ===========================
E:\b\build\slave\Windows_Engine\build\src\third_party\dart\third_party\pkg\pub\bin\pub.dart 8  main
This is an unexpected error. Please run

    pub --trace --verbosity=warning get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub get failed (69) -- attempting retry 3 in 4 seconds...

**Comment by yhzhan1002** [comment] 2019-02-24 14:09
HTTP error 424: Failed Dependency
package:pub/src/http.dart 218:5                 _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 301:37       BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 196:13       BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 371:48          Entrypoint._get.<fn>
===== asynchronous gap ===========================
package:pub/src/http.dart 271:51                withDependencyType
package:pub/src/entrypoint.dart 367:12          Entrypoint._get
dart:async                                      Future.wait
package:pub/src/entrypoint.dart 228:18          Entrypoint.acquireDependencies
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver.solve
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver._result
This is an unexpected error. Please run

    pub --trace --verbosity=warning get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

**Comment by iusn** [comment] 2019-02-26 05:35
I have the same issue


HTTP error 424: Failed Dependency
package:pub/src/http.dart 218:5                 _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 301:37       BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 196:13       BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 371:48          Entrypoint._get.<fn>
===== asynchronous gap ===========================
package:pub/src/http.dart 271:51                withDependencyType
package:pub/src/entrypoint.dart 367:12          Entrypoint._get
dart:async                                      Future.wait
package:pub/src/entrypoint.dart 228:18          Entrypoint.acquireDependencies
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver.solve
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver._result
This is an unexpected error. Please run

    pub --trace --verbosity=warning get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new


=============================================================

[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.3 18D109, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.31.1)
[✓] Connected device (1 available)

• No issues found!

**Comment by Qimin-Qiu** [comment] 2019-02-26 07:11
When I get the path_provider 0.5.0+1 or 0.5.0, this issue will show up.

**Comment by douyanlin** [comment] 2019-02-26 08:31
i have the same issue. anyone solve this problem?

**Comment by ibabyblue** [comment] 2019-02-26 08:46
I have the same issue
HTTP error 424: Failed Dependency
package:pub/src/http.dart 218:5                 _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 301:37       BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 196:13       BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 371:48          Entrypoint._get.<fn>
===== asynchronous gap ===========================
package:pub/src/http.dart 271:51                withDependencyType
package:pub/src/entrypoint.dart 367:12          Entrypoint._get
dart:async                                      Future.wait
package:pub/src/entrypoint.dart 228:18          Entrypoint.acquireDependencies
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver.solve
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver._result
This is an unexpected error. Please run

    pub --trace --verbosity=warning get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub get failed (69) -- attempting retry 1 in 1 second...

**Comment by mah93** [comment] 2019-02-26 08:58
All is ok in morning，but I have the same issue now.
anyone solve this problem?

**Comment by dawangraoming** [comment] 2019-02-26 09:43
When I removed the `PUB_HOSTED_URL ` and `FLUTTER_STORAGE_BASE_URL ` environment variables and used the US proxy,

this problem was solved,

maybe some problems with the mirror site.

**Comment by mah93** [comment] 2019-02-26 09:52
> When I removed the `PUB_HOSTED_URL ` and `FLUTTER_STORAGE_BASE_URL ` environment variables and used the US proxy,
> 
> this problem was solved,
> 
> maybe some problems with the mirror site.

it not work😢

**Comment by zoechi** [comment] 2019-02-26 10:07
Possible duplicate of https://github.com/flutter/flutter/issues/28498

**Comment by chenglu** [comment] 2019-02-26 14:43
It has been fixed, see my comments on [#28498](https://github.com/flutter/flutter/issues/28498#issuecomment-467462967) for more information.

**Closed** 2019-03-04 20:09 UTC
