### ISSUE TITLE
pub update fails with 'source_gen has no versions that match...' if I include sass_builder

### ISSUE THREAD

**Issue by MikeMitterer** [dart-lang/pub#1761] opened 2017-12-13 14:36 UTC
If I include `sass_builder:  "^1.1.0"` in one of my projects it hangs in IntelliJ forever and if I `pub update` on the cmdline it fails with 

``` 
Package source_gen has no versions that match >=0.4.0 <0.5.0 derived from:
- zengen 0.3.2 depends on version ^0.4.0
```
**I have no idea how to solve this problem**
pub deps doesn't work - it wants me to `pub get` but this doesn't work... 

The result from `pub --trace update 2> pub-dep.error.txt`
[pub-dep.error.txt](https://github.com/dart-lang/pub/files/1555811/pub-dep.error.txt)

My dependency-tree without sass_builder:
```
mobiad_rest_ui_mdl_mmui_jobedit_inplace_sample 0.0.1
|-- git_version 0.1.17
|   |-- barback 0.15.2+13
|   |   |-- collection...
|   |   |-- path...
|   |   |-- stack_trace...
|   |   |-- async 1.13.3
|   |   |   '-- collection...
|   |   |-- pool 1.3.3
|   |   |   |-- async...
|   |   |   '-- stack_trace...
|   |   '-- source_span 1.4.0
|   |       |-- charcode...
|   |       '-- path...
|   |-- console_log_handler 0.5.7
|   |   |-- browser...
|   |   |-- intl...
|   |   |-- logging...
|   |   |-- ansicolor 0.0.9
|   |   '-- supports_color 0.1.1
|   |-- logging 0.11.3+1
|   '-- where 1.1.0
|       |-- args...
|       |-- path...
|       '-- meta 1.1.2
'-- mobiad_rest_ui_mdl 0.0.0
    |-- archive 1.0.32
    |   |-- crypto...
    |   |-- path...
    |   '-- args 0.13.7
    |-- beanvalidator 0.2.5
    |   |-- browser...
    |   |-- logging...
    |   |-- matcher...
    |   |-- validate...
    |   |-- l10n 1.2.9
    |   |   |-- args...
    |   |   |-- browser...
    |   |   |-- console_log_handler...
    |   |   |-- dice...
    |   |   |-- intl...
    |   |   |-- logging...
    |   |   |-- optional...
    |   |   |-- validate...
    |   |   |-- which 0.1.3
    |   |   |   |-- path...
    |   |   |   '-- when 0.2.0
    |   |   '-- yaml 2.1.13
    |   |       |-- charcode...
    |   |       |-- collection...
    |   |       |-- source_span...
    |   |       '-- string_scanner...
    |   '-- reflectable 1.0.3
    |       |-- barback...
    |       |-- logging...
    |       |-- path...
    |       |-- source_span...
    |       |-- analyzer 0.27.6
    |       |   |-- args...
    |       |   |-- charcode...
    |       |   |-- crypto...
    |       |   |-- glob...
    |       |   |-- html...
    |       |   |-- path...
    |       |   |-- yaml...
    |       |   |-- isolate 0.2.3
    |       |   |-- package_config 1.0.3
    |       |   |   |-- charcode...
    |       |   |   '-- path...
    |       |   |-- plugin 0.2.0+2
    |       |   '-- watcher 0.9.7+4
    |       |       |-- async...
    |       |       '-- path...
    |       |-- code_transformers 0.4.2+3
    |       |   |-- analyzer...
    |       |   |-- barback...
    |       |   |-- path...
    |       |   |-- source_span...
    |       |   |-- cli_util 0.0.1+2
    |       |   |   |-- path...
    |       |   |   '-- which...
    |       |   '-- source_maps 0.10.4
    |       |       '-- source_span...
    |       |-- dart_style 0.2.11+1
    |       |   |-- analyzer...
    |       |   |-- args...
    |       |   |-- path...
    |       |   '-- source_span...
    |       '-- glob 1.1.5
    |           |-- async...
    |           |-- collection...
    |           |-- path...
    |           '-- string_scanner 1.0.2
    |               |-- charcode...
    |               '-- source_span...
    |-- chartjs 0.3.2
    |   |-- func 0.1.1
    |   '-- js 0.6.1
    |-- collection 1.14.3
    |-- crypto 2.0.2+1
    |   |-- collection...
    |   |-- convert 2.0.1
    |   |   |-- typed_data...
    |   |   '-- charcode 1.1.1
    |   '-- typed_data 1.1.5
    |-- dart_to_js_script_rewriter 0.1.0+4
    |   |-- barback...
    |   '-- html 0.12.2+2
    |       |-- source_span...
    |       |-- csslib 0.13.7+1
    |       |   |-- args...
    |       |   |-- logging...
    |       |   |-- path...
    |       |   '-- source_span...
    |       '-- utf 0.9.0+3
    |-- dice 1.7.0
    |   '-- logging...
    |-- google_maps 2.0.7
    |   '-- js_wrapping 0.1.2
    |-- http_utils 1.5.4
    |   '-- intl...
    |-- intl 0.15.2
    |   '-- path...
    |-- latlong 0.4.5
    |   |-- browser...
    |   |-- console_log_handler...
    |   |-- logging...
    |   '-- validate...
    |-- mime 0.9.5
    |-- optional 1.2.3+1
    |-- plotly 0.7.3
    |-- quiver 0.21.4
    |   '-- matcher 0.12.1+4
    |       '-- stack_trace...
    |-- servicefile 0.1.0
    |   |-- browser...
    |   |-- console_log_handler...
    |   |-- logging...
    |   |-- restrequest 1.0.0
    |   |   |-- browser...
    |   |   |-- console_log_handler...
    |   |   |-- cryptoutils...
    |   |   |-- dice...
    |   |   |-- http_utils...
    |   |   |-- intl...
    |   |   |-- logging...
    |   |   |-- optional...
    |   |   |-- path...
    |   |   |-- validate...
    |   |   |-- webapp_base_signer...
    |   |   |-- http 0.11.3+16
    |   |   |   |-- async...
    |   |   |   |-- collection...
    |   |   |   |-- path...
    |   |   |   '-- http_parser 3.1.1
    |   |   |       |-- charcode...
    |   |   |       |-- collection...
    |   |   |       |-- source_span...
    |   |   |       |-- string_scanner...
    |   |   |       '-- typed_data...
    |   |   |-- javainterop 1.0.0
    |   |   '-- json 0.10.0
    |   '-- validate 1.6.0
    |       |-- browser...
    |       |-- logging...
    |       '-- logging_handlers 0.8.0
    |           |-- intl...
    |           '-- logging...
    |-- stack_trace 1.9.1
    |   '-- path 1.5.1
    |-- webapp_base_signer 1.1.0
    |   |-- browser...
    |   |-- console_log_handler...
    |   |-- crypto...
    |   |-- cryptoutils...
    |   |-- http_utils...
    |   |-- logging...
    |   |-- restrequest...
    |   |-- validate...
    |   |-- quiver_hashcode 1.0.0
    |   '-- uuid 0.5.3
    |       |-- convert...
    |       '-- crypto...
    '-- webapp_base_ui_mdl 0.1.0
        |-- dice...
        |-- google_maps...
        |-- browser 0.10.0+2
        |-- cryptoutils 0.2.1
        |   |-- collection...
        |   |-- bignum 0.1.0
        |   |   '-- fixnum 0.10.6
        |   '-- zengen 0.3.2
        |       |-- quiver...
        |       '-- source_gen 0.4.8
        |           |-- analyzer...
        |           |-- args...
        |           |-- cli_util...
        |           |-- dart_style...
        |           '-- path...
        |-- mdl 2.1.4
        |   |-- barback...
        |   |-- browser...
        |   |-- console_log_handler...
        |   |-- dice...
        |   |-- intl...
        |   |-- l10n...
        |   |-- logging...
        |   |-- path...
        |   |-- validate...
        |   |-- browser_detect 1.0.4
        |   |-- dnd 0.3.6
        |   |   '-- browser...
        |   |-- mustache 0.2.5+1
        |   '-- route_hierarchical 0.7.0
        |       '-- logging...
        '-- webapp_base_ui 0.9.0
            |-- cryptoutils...
            |-- restrequest...
            |-- lawndart 0.9.0
            '-- webapp_base_dart 0.9.2
                |-- browser...
                |-- console_log_handler...
                |-- cryptoutils...
                |-- dice...
                |-- http...
                |-- http_utils...
                |-- intl...
                |-- javainterop...
                |-- json...
                |-- logging...
                |-- optional...
                |-- path...
                |-- restrequest...
                |-- validate...
                '-- webapp_base_signer...
```

**Comment by zoechi** [comment] 2017-12-13 18:03
https://pub.dartlang.org/packages/pub_mediator might help until the new resolver algorithm becomes available

**Comment by MikeMitterer** [comment] 2017-12-14 07:34
Thanks @zoechi - I tried it but it crashed mediator :-)) Anyway - thanks for the hint.

**Comment by zoechi** [comment] 2017-12-14 15:46
Then I'm afraid you'll need to manually investigate what causes the conflict.
A better resolution algorithm with better error messages is work in progress as far as I know.

**Comment by nex3** [comment] 2017-12-15 21:24
Duplicate of #912.

**Closed by nex3** 2017-12-15 21:24 UTC
