### ISSUE TITLE
Brand New Project in WebStorm Pub Get Error

### ISSUE THREAD

**Issue by tmudd** [dart-lang/pub#1737] opened 2017-11-06 21:20 UTC
Created a new project in a branch and tried to do a pub get on a fresh auto generated pubspec.yaml file.
`Process finished with exit code 65`

Was instructed to do a
`pub --trace get`
and attach log.
[pubgetlog.txt](https://github.com/dart-lang/pub/files/1447834/pubgetlog.txt)

**Comment by nex3** [comment] 2017-11-06 21:26
Duplicate of #1735.

**Closed by nex3** 2017-11-06 21:26 UTC
