### ISSUE TITLE
Pub serve : be able to define the output direcory

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub#1328] opened 2015-09-02 14:41 UTC
_From @DartBot on August 8, 2014 20:35_

*This issue was originally filed by gex.du.web...&#064;gmail.com*
_____
What steps will clearly show the need for enhancement?

When I develop (not in deployment mode)

1. My client is in Dart on workspace/foo_client
2. My server is another platform in workspace/foo_server, this platform serve static assets from workspace/foo_server/public. This platform can reload on live changing assets.
3. It would be useful to call &quot;pub serve --out workspace/foo_server/public&quot; to have a nice development experience : i'm working on workspace/foo_client and it's automatically deployed by my adhoc server platform

Gérald Reinhart 

_Copied from original issue: dart-lang/sdk#20432_

**Comment by mit-mit** [comment] 2015-09-02 14:41
_From @sgjesse on August 11, 2014 7:15_

This would require 'pub serve' to eagerly generate all assets each time there are changes to the client files.

Another option is to have the server proxy to 'pub serve' during development and then use 'pub build' and serving from files for deployment.

Here is some 'simple pub' serve proxy code we have used elsewhere, pubServeUrl contains the URL to the running 'pub serve':

&nbsp;&nbsp;Future proxyToPub(HttpRequest request, String path) {
&nbsp;&nbsp;&nbsp;&nbsp;const RESPONSE_HEADERS = const [
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;HttpHeaders.CONTENT_LENGTH,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;HttpHeaders.CONTENT_TYPE ];

&nbsp;&nbsp;&nbsp;&nbsp;var uri = pubServeUrl.resolve(path);
&nbsp;&nbsp;&nbsp;&nbsp;return client.openUrl(request.method, uri)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.then((proxyRequest) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;proxyRequest.headers.removeAll(HttpHeaders.ACCEPT_ENCODING);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return proxyRequest.close();
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;})
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.then((proxyResponse) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;proxyResponse.headers.forEach((name, values) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if (RESPONSE_HEADERS.contains(name)) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;request.response.headers.set(name, values);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;});
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;request.response.statusCode = proxyResponse.statusCode;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;request.response.reasonPhrase = proxyResponse.reasonPhrase;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return proxyResponse.pipe(request.response);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;})
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.catchError((e) {
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print("Unable to connect to 'pub serve' for '${request.uri}': $e");
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var error = new AssetError(
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"Unable to connect to 'pub serve' for '${request.uri}': $e");
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return new Future.error(error);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;});
&nbsp;&nbsp;}

______
*Added [Pub-Serve](../labels/Pub-Serve), [Triaged](../labels/Triaged) labels.*

**Comment by nex3** [comment] 2015-09-02 18:09
Duplicate of #1261.

**Closed by nex3** 2015-09-02 18:09 UTC
Labels: enhancement, pub serve
