### ISSUE TITLE
window10 flutter packages get fail

### ISSUE THREAD

**Issue by faxinter** [dart-lang/pub#2113] opened 2019-03-30 10:08 UTC
[        ] Extracting  doc\api\dart-core\Map\length.html
[        ] file doc\api\dart-core\Map\map.html
[        ] already exists. Overwrite with 
[        ] doc\api\dart-core\Map\map.html?
[        ] (Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit? 
[        ] ERROR: Can't allocate required memory!
[   +2 ms] package:pub/src/io.dart 944:7              _extractTarGzWindows.<fn>
[   +1 ms] ===== asynchronous gap ===========================
[        ] dart:async                                 _AsyncAwaitCompleter.completeError
[        ] package:pub/src/io.dart                    _extractTarGzWindows.<fn>
[        ] ===== asynchronous gap ===========================
[        ] dart:async                                 _asyncThenWrapperHelper
[        ] package:pub/src/io.dart                    _extractTarGzWindows.<fn>
[        ] package:pub/src/io.dart 821:20             withTempDir
[        ] ===== asynchronous gap ===========================
[        ] dart:async                                 _asyncThenWrapperHelper
[        ] package:pub/src/source/hosted.dart         BoundHostedSource._download
[        ] package:pub/src/source/hosted.dart 196:13  BoundHostedSource.downloadToSystemCache
[        ] ===== asynchronous gap ===========================
[        ] dart:async                                 _asyncThenWrapperHelper
[        ] package:pub/src/entrypoint.dart            Entrypoint.acquireDependencies
[   +1 ms] package:pub/src/command/get.dart 41:23     GetCommand.run
[        ] package:args/command_runner.dart 194:27    CommandRunner.runCommand
[        ] This is an unexpected error. Please run
[        ]     pub --trace --verbosity=warning --verbose get --no-precompile
[        ] and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
[  +10 ms] Running "flutter packages get" in flutter_xcjj... (completed in 22.6s)
[   +7 ms] "flutter get" took 22,656ms.
[   +6 ms] "flutter get" took 22,656ms.
pub get failed (1)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      pub (package:flutter_tools/src/dart/pub.dart:170:5)
<asynchronous suspension>
#2      pubGet (package:flutter_tools/src/dart/pub.dart:104:13)
<asynchronous suspension>
#3      PackagesGetCommand._runPubGet (package:flutter_tools/src/commands/packages.dart:59:11)
<asynchronous suspension>
#4      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:82:11)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#12     Future._complete (dart:async/future_impl.dart:473:7)
#13     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#14     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#20     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

**Comment by natebosch** [comment] 2019-04-02 22:10
`Extracting doc\api\dart-core\Map\length.html`

It looks like maybe some package was published with the SDK API docs inside it?

`file doc\api\dart-core\Map\map.html already exists.` - I'm not sure what could be happening there. Shouldn't we be unpacking to a distinct location?

`ERROR: Can't allocate required memory!`

Looks like the root cause - plausibly because the package is really big due to bundling in SDK docs? It would be nice if we could figure out what package this was...

**Comment by jonasfj** [comment] 2019-04-03 10:49
That's nicely spotted... it could be related to https://github.com/dart-lang/pub/issues/2091
We only recently updated the server to forbid files that contains duplicate names (when compared case insensitie).

@faxinter, what packages were you trying to get?

> It looks like maybe some package was published with the SDK API docs inside it?

A) yeah, some people manage to publish packages with `doc/api/...` in the package.
B) `dartdoc` has an issue where it generates SDK API docs for flutter packages (maybe it's being called wrong).

Probably #2095 would mitigate this by discouraging users from publishing `doc/api/index.html`.

**Comment by sigurdm** [comment] 2023-01-20 14:44
Not sure we can do more here.

@faxinter never returned.

Closing as irreproducible. Please open a new issue if this still happens

**Closed by sigurdm** 2023-01-20 14:44 UTC
