### ISSUE TITLE
When installing flutter, i get this error when i run 'flutter doctor'

### ISSUE THREAD

**Issue by rahul-vignesh-r** [dart-lang/pub#3867] opened 2023-04-08 14:19 UTC
FINE: Resolving dependencies in packages\flutter_tools finished (3.7s).
![Capture](https://user-images.githubusercontent.com/93032983/230726058-70dc996e-01cc-4972-8144-269052b304bd.PNG)
ERR : Invalid hexadecimal code unit U+0000. (at offset 0)
FINE: Exception type: FormatException
ERR : package:convert/src/utils.dart 34:3          digitForCodeUnit
    | package:convert/src/hex/decoder.dart 173:22  _decode
    | package:convert/src/hex/decoder.dart 31:5    HexDecoder.convert
    | dart:convert                                 Codec.decode
    | package:pub/src/utils.dart 335:43            hexDecode
    | package:pub/src/source/hosted.dart 852:14    HostedSource.sha256FromCache
    | package:pub/src/source/hosted.dart 764:29    HostedSource.downloadToSystemCache
    | ===== asynchronous gap ===========================
    | package:pub/src/system_cache.dart 230:20     SystemCache.downloadPackage
    | ===== asynchronous gap ===========================
    | package:pub/src/solver/result.dart 70:20     SolveResult.downloadCachedPackages.<fn>.<fn>
    | ===== asynchronous gap ===========================
    | package:pub/src/solver/result.dart 68:18     SolveResult.downloadCachedPackages.<fn>
    | ===== asynchronous gap ===========================
    | package:pub/src/solver/result.dart 65:32     SolveResult.downloadCachedPackages
    | ===== asynchronous gap ===========================
    | package:pub/src/entrypoint.dart 372:25       Entrypoint.acquireDependencies
    | ===== asynchronous gap ===========================
    | package:pub/src/command/get.dart 60:5        GetCommand.runProtected
ERR : This is an unexpected error. The full log and other details are collected in:
    | 
    |   {user}\AppData\Local\Pub\Cache\log\pub_log.txt
    | 
    | Consider creating an issue on https://github.com/dart-lang/pub/issues/new
    | and attaching the relevant parts of that log file.

**Comment by sigurdm** [comment] 2023-04-12 08:07
Realizing we have fixed this already. It is a duplicate of https://github.com/dart-lang/pub/issues/3816.

**Closed by sigurdm** 2023-04-12 08:07 UTC
Labels: bug
