### ISSUE TITLE
Paths constantly toggle formats in pubspec.lock between Windows and macOS

### ISSUE THREAD

**Issue by anaisbetts** [dart-lang/pub#2122] opened 2019-04-16 08:36 UTC
Related to #950, to repro:

1. On macOS, clone https://github.com/anaisbetts/sirene
1. `git submodule update --init --recursive`
1. `./flutterw packages pub get`
1. Note that in pubspec.lock, the reference is to `vendor/mlkit`
1. Go to a Windows computer, follow steps 1-3 again
1. Note that in pubspec.lock, the reference is now `vendor\\mlkit`

In either Step 4 or Step 6 (depending on the current state of the repo), `git status` will be dirty, and every contributor who touches the project will end up inadvertently changing this line depending on their operating system. This makes using relative path pub packages really annoying to use - while I know that pub itself can use git references, I'd rather use submodules because it's easier to work on a subproject this way.

**Comment by jonasfj** [comment] 2019-04-16 10:37
So the problem is exclusively with path dependencies, right?

**Comment by paulcbetts** [comment] 2019-04-16 16:05
@jonasfj I'm not sure, I'm very much new to Pub. It does seem like that's the only place where you'd use a relative path

**Comment by koraxis** [comment] 2019-07-03 12:32
Have the same issue here, any possibility of a fix in the near future?

**Comment by jonasfj** [comment] 2019-07-05 13:50
I don't think is high priority, but if anyone wants to work on it, I'll be happy to do the review.

It makes sense to me that the `pubspec.lock` should use forward slash only.

**Comment by kinex** [comment] 2019-12-03 08:32
This is a major issue for example if you develop Android version of a Flutter app in Windows and iOS version in Mac as I am trying to do. You have to mess with the slashes/backslashes daily, totally waste of time.

**Comment by sigurdm** [comment] 2020-05-11 07:38
This was fixed by https://github.com/dart-lang/pub/pull/2299

**Closed by sigurdm** 2020-05-11 07:38 UTC
Labels: bug
