### ISSUE TITLE
Pub get failed with exit code 65

### ISSUE THREAD

**Issue by Inzimam786** [dart-lang/pub#3883] opened 2023-04-19 00:01 UTC
C:\flutter\bin\flutter.bat --no-color pub get
Running "flutter pub get" in inzimam...
Resolving dependencies...
Invalid hexadecimal code unit U+0000. (at offset 0)
package:convert/src/utils.dart 34:3          digitForCodeUnit
package:convert/src/hex/decoder.dart 173:22  _decode
package:convert/src/hex/decoder.dart 31:5    HexDecoder.convert
dart:convert                                 Codec.decode
package:pub/src/utils.dart 335:43            hexDecode
package:pub/src/source/hosted.dart 852:14    HostedSource.sha256FromCache
package:pub/src/source/hosted.dart 764:29    HostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/system_cache.dart 230:20     SystemCache.downloadPackage
===== asynchronous gap ===========================
package:pub/src/solver/result.dart 70:20     SolveResult.downloadCachedPackages.<fn>.<fn>
===== asynchronous gap ===========================
package:pub/src/solver/result.dart 68:18     SolveResult.downloadCachedPackages.<fn>
===== asynchronous gap ===========================
package:pub/src/solver/result.dart 65:32     SolveResult.downloadCachedPackages
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 372:25       Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 60:5        GetCommand.runProtected
This is an unexpected error. The full log and other details are collected in:

    C:\Users\HP\AppData\Local\Pub\Cache\log\pub_log.txt

Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.
pub get failed
command: "C:\flutter\bin\cache\dart-sdk\bin\dart __deprecated_pub --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "C:\flutter",
  "PUB_ENVIRONMENT": "flutter_cli:get",
  "PUB_CACHE": "C:\Users\HP\AppData\Local\Pub\Cache",
}
exit code: 65

process finished with exit code 65

**Comment by sigurdm** [comment] 2023-04-20 07:28
Duplicate of https://github.com/dart-lang/pub/issues/3816

**Closed by sigurdm** 2023-04-20 07:28 UTC
