### ISSUE TITLE
 Unable to 'pub upgrade' flutter tool. Retrying in five seconds...

### ISSUE THREAD

**Issue by xuanInitial** [dart-lang/pub#2064] opened 2019-02-25 02:34 UTC
➜  Flutter git clone -b dev https://github.com/flutter/flutter.git
Cloning into 'flutter'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 157625 (delta 2), reused 7 (delta 1), pack-reused 157610
Receiving objects: 100% (157625/157625), 54.73 MiB | 91.00 KiB/s, done.
Resolving deltas: 100% (119942/119942), done.
➜  Flutter flutter doctor
zsh: command not found: flutter
➜  Flutter export PATH=$PATH:/Users/initial/Desktop/fun/Flutter/flutter/bin
➜  Flutter flutter doctor
Downloading Dart SDK from Flutter engine f1f19bba8f0089490962316867bd222727510ac5...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 71.3M  100 71.3M    0     0  12.0M      0  0:00:05  0:00:05 --:--:-- 15.3M
Building flutter tool...
HTTP error 424: Failed Dependency
package:pub/src/http.dart 218:5                 _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 301:37       BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 196:13       BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 371:48          Entrypoint._get.<fn>
===== asynchronous gap ===========================
dart:async                                      runZoned
package:pub/src/http.dart 272:10                withDependencyType
package:pub/src/entrypoint.dart 367:12          Entrypoint._get
dart:async                                      Future.wait
package:pub/src/entrypoint.dart 228:18          Entrypoint.acquireDependencies
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver.solve
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver._result
This is an unexpected error. Please run

    pub --trace upgrade --verbosity=error

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)
HTTP error 424: Failed Dependency
package:pub/src/http.dart 218:5                 _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 301:37       BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 196:13       BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 371:48          Entrypoint._get.<fn>
===== asynchronous gap ===========================
dart:async                                      runZoned
package:pub/src/http.dart 272:10                withDependencyType
package:pub/src/entrypoint.dart 367:12          Entrypoint._get
dart:async                                      Future.wait
package:pub/src/entrypoint.dart 228:18          Entrypoint.acquireDependencies
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver.solve
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver._result
This is an unexpected error. Please run

    pub --trace upgrade --verbosity=error

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (8 tries left)
HTTP error 424: Failed Dependency
package:pub/src/http.dart 218:5                 _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 301:37       BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 196:13       BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 371:48          Entrypoint._get.<fn>
===== asynchronous gap ===========================
dart:async                                      runZoned
package:pub/src/http.dart 272:10                withDependencyType
package:pub/src/entrypoint.dart 367:12          Entrypoint._get
dart:async                                      Future.wait
package:pub/src/entrypoint.dart 228:18          Entrypoint.acquireDependencies
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver.solve
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver._result
This is an unexpected error. Please run

    pub --trace upgrade --verbosity=error

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (7 tries left)
HTTP error 424: Failed Dependency
package:pub/src/http.dart 218:5                 _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 301:37       BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 196:13       BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 371:48          Entrypoint._get.<fn>
===== asynchronous gap ===========================
dart:async                                      runZoned
package:pub/src/http.dart 272:10                withDependencyType
package:pub/src/entrypoint.dart 367:12          Entrypoint._get
dart:async                                      Future.wait
package:pub/src/entrypoint.dart 228:18          Entrypoint.acquireDependencies
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver.solve
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver._result
This is an unexpected error. Please run

    pub --trace upgrade --verbosity=error

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (6 tries left)
HTTP error 424: Failed Dependency
package:pub/src/http.dart 218:5                 _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 301:37       BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 196:13       BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 371:48          Entrypoint._get.<fn>
===== asynchronous gap ===========================
dart:async                                      runZoned
package:pub/src/http.dart 272:10                withDependencyType
package:pub/src/entrypoint.dart 367:12          Entrypoint._get
dart:async                                      Future.wait
package:pub/src/entrypoint.dart 228:18          Entrypoint.acquireDependencies
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver.solve
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver._result
This is an unexpected error. Please run

    pub --trace upgrade --verbosity=error

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (5 tries left)
HTTP error 404: Not Found
package:pub/src/http.dart 218:5                 _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 301:37       BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 196:13       BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 371:48          Entrypoint._get.<fn>
===== asynchronous gap ===========================
dart:async                                      runZoned
package:pub/src/http.dart 272:10                withDependencyType
package:pub/src/entrypoint.dart 367:12          Entrypoint._get
dart:async                                      Future.wait
package:pub/src/entrypoint.dart 228:18          Entrypoint.acquireDependencies
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver.solve
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver._result
This is an unexpected error. Please run

    pub --trace upgrade --verbosity=error

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (4 tries left)
HTTP error 404: Not Found
package:pub/src/http.dart 218:5                 _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 301:37       BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 196:13       BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 371:48          Entrypoint._get.<fn>
===== asynchronous gap ===========================
dart:async                                      runZoned
package:pub/src/http.dart 272:10                withDependencyType
package:pub/src/entrypoint.dart 367:12          Entrypoint._get
dart:async                                      Future.wait
package:pub/src/entrypoint.dart 228:18          Entrypoint.acquireDependencies
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver.solve
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver._result
This is an unexpected error. Please run

    pub --trace upgrade --verbosity=error

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (3 tries left)

Perform flutter upgrade to report an error with the above problem

Then my solution was to remove the SDK and reinstall it

Same error

Ask for help

**Comment by zoechi** [comment] 2019-02-25 09:32
Might be https://flutter.dev/community/china

**Comment by zoechi** [comment] 2019-02-26 10:20
Possible duplicate of https://github.com/flutter/flutter/issues/28498

**Comment by chenglu** [comment] 2019-02-26 14:44
It has been fixed, see my comments on [#28498](https://github.com/flutter/flutter/issues/28498#issuecomment-467462967) for more information, sorry about that.

**Closed** 2019-03-04 20:07 UTC
