### ISSUE TITLE
pub add should support multiple dependencies 

### ISSUE THREAD

**Issue by tusharojha** [dart-lang/pub#3235] opened 2021-11-21 21:14 UTC
## Description

As of now, pub add command supports to install just one dependency at at time but it would be great if we can use the add command to install multiple dependencies in one go.

Some usage examples:
```dart
dart pub add bloc:^8.0.1 web_scraper
```

```dart
dart pub add bloc:^8.0.1 web_scraper:^0.1.4
```

```dart
dart pub add bloc web_scraper
```

**Comment by sigurdm** [comment] 2021-11-22 07:53
Duplicate of https://github.com/dart-lang/pub/issues/3213 we closed that as wontfix.

Best suggestion is to just write several lines of `pub add`.

**Closed by sigurdm** 2021-11-22 07:53 UTC
