### ISSUE TITLE
Null check operator used on a null value package:pub/src/source/hosted.dart 760:33

### ISSUE THREAD

**Issue by MobinAssari** [dart-lang/pub#4312] opened 2024-06-19 13:53 UTC
when i build my project i get this error

Downloading packages...
Null check operator used on a null value
package:pub/src/source/hosted.dart 760:33              HostedSource._getAdvisories.readAdvisoriesFromCache
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 778:12              HostedSource._getAdvisories
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 1066:24             HostedSource.getAdvisoriesForPackageVersion
===== asynchronous gap ===========================
package:pub/src/solver/report.dart 414:26              SolveReport._reportPackage
===== asynchronous gap ===========================
package:pub/src/solver/report.dart 218:18              SolveReport._reportChanges
===== asynchronous gap ===========================
package:pub/src/solver/report.dart 73:21               SolveReport.show
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 568:5                  Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 77:5                  GetCommand.runProtected
===== asynchronous gap ===========================
package:pub/src/command.dart 196:7                     PubCommand.run
===== asynchronous gap ===========================
package:args/command_runner.dart 212:13                CommandRunner.runCommand
===== asynchronous gap ===========================
package:dartdev/dartdev.dart 232:18                    DartdevRunner.runCommand
===== asynchronous gap ===========================
package:dartdev/dartdev.dart 46:16                     runDartdev
===== asynchronous gap ===========================
C:\b\s\w\ir\x\w\sdk\pkg\dartdev\bin\dartdev.dart 13:5  main
This is an unexpected error. The full log and other details are collected in:

    C:\Users\mobin\AppData\Local\Pub\Cache\log\pub_log.txt

Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.
Process finished with exit code 1

and this is my flutter doctor 

[√] Flutter (Channel stable, 3.22.2, on Microsoft Windows [Version 10.0.22621.3737], locale en-US)
    • Flutter version 3.22.2 on channel stable at D:\src\flutter_windows_3.22.2-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (2 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\mobin\AppData\Local\Android\sdk
    • Platform android-34, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.4.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Enterprise
    • Visual Studio Enterprise 2022 version 17.4.33213.308
    • Windows 10 SDK version 10.0.22000.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] IntelliJ IDEA Community Edition (version 2023.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code, 64-bit edition (version 1.74.3)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.60.0

[√] Connected device (4 available)
    • sdk gphone x86 64 (mobile) • emulator-5554 • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)          • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.3737]
    • Chrome (web)               • chrome        • web-javascript • Google Chrome 125.0.6422.176
    • Edge (web)                 • edge          • web-javascript • Microsoft Edge 126.0.2592.56

[!] Network resources
    X A cryptographic error occurred while checking "https://storage.googleapis.com/": Connection terminated during handshake
      You may be experiencing a man-in-the-middle attack, your network may be compromised, or you may have malware installed on your computer.
    X A network error occurred while checking "https://cocoapods.org/": The semaphore timeout period has expired.

**Comment by sigurdm** [comment] 2024-06-20 07:30
What dart sdk version are you on?

I believe this is a duplicate of https://github.com/dart-lang/pub/issues/4269

This should be fixed in 3.4.4 https://github.com/dart-lang/sdk/blob/stable/CHANGELOG.md#344---2024-06-12

**Closed** 2024-06-20 07:30 UTC

**Comment by maulikchak** [comment] 2024-11-28 06:26
i follow this step and error gone
user this command
1. flutter downgrade
2. flutter upgrade
3. flutter pub get
