### ISSUE TITLE
Extract a pubspec package

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/pub#1676] opened 2017-07-29 00:16 UTC
Enough tools want to handle a pubspec, it might make sense to pull out this logic – like `pub_semver`

**Comment by kevmoo** [comment] 2017-07-29 00:16
CC @matanlurey

**Comment by matanlurey** [comment] 2017-07-29 00:26
Yes please. In the process, it would be really really nice if we had a pkg/yaml that supported writing (not just reading) so we could have tooling automatically update pubspecs.

/cc @natebosch @grouma

**Comment by natebosch** [comment] 2017-07-29 00:39
writing yaml is pretty challenging - especially if you want to try to make a minimal diff against existing yaml.

It would be awesome to be able to flesh out a package to do that, but I'm not sure if we have the bandwidth.

**Comment by matanlurey** [comment] 2017-07-29 01:10
What specifically about YAML makes it harder to write than JSON? The comments and whitespace?

**Comment by natebosch** [comment] 2017-07-29 01:23
It's mostly difficult because there is a lot of subjectivity in how to write it. For any given piece you can choose to write it in 'yaml' style or 'json' style, since yaml is a superset of json.

For instance:

```yaml
foo: ['some', things']
```

vs

```yaml
foo:
  - some
  - things
```

Comments are another piece that don't round trip well.

We could probably come up with reasonable defaults or heuristics for most of the decisions. The problem is that 1 - we'd have to spend time deciding those defaults an heuristics for a reasonable UX, 2 - adopting the tool would most likely mean also letting it own these decisions entirely or risk having a nasty diff each time you try to use it.

This doesn't even touch on the fact that `pubspec.yaml` in particular has a loose structure and once we round-trip through the internal data structures we'd have to make a decision between:

```yaml
dependencies:
  some_package:
    git: git://github.com/foo/foo.git
```

vs

```yaml
dependencies:
  some_package:
    git:
      url: git://github.com/foo/foo.git
```

**Comment by natebosch** [comment] 2017-07-29 01:24
An ideal solution might look like tracking source spans and being able to output everything in exactly the format it was read in, except for the sub-keys that we are changing. That poses it's own  challenges but would probably give the best UX. Since the current parser doesn't track this we'd have to extend parsing functionality too.

**Comment by matanlurey** [comment] 2017-07-29 01:28
Honestly I'd be willing to take a shot. I think the biggest bang for the buck would be just trying to add/modify/remove keys and items on an existing YAML document, versus writing one from scratch.

**Comment by natebosch** [comment] 2017-07-29 01:51
It would be awesome to have :)

**Comment by kevmoo** [comment] 2017-07-29 03:44
Just looked through https://github.com/dart-lang/pub/blob/master/lib/src/pubspec.dart – there are a lot of hooks into little things in pub. source_registry seems like the biggest concern...

**Comment by nex3** [comment] 2017-09-19 22:38
This would be very difficult to do gracefully, which is why we haven't done it yet. Pub's `Pubspec` object parses the pubspec into various pub-internal types, all of which would have to be exposed somehow. In addition, as Kevin points out, some of those types necessarily refer to pub's internal representation of package sources, which would *also* need to be exposed.

Basically, this wouldn't be possible without exposing all of pub's internals, so I'm closing it as a duplicate of #1154.

**Closed by nex3** 2017-09-19 22:38 UTC

**Comment by natebosch** [comment] 2018-07-27 20:52
https://pub.dartlang.org/packages/pubspec_parse covers parsing, not round tripping, and is not used by pub itself, but it does at least centralize some of the stuff that multiple packages need.
