### ISSUE TITLE
pub install/upgrade not creating link for Git repo on Linux

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/pub#1325] opened 2015-09-02 14:36 UTC
_From @halverneus on June 26, 2015 16:45_

The repository clones as expected and exists in .pub-cache/git/, but the link is never created within the project itself. Project is on same partition as .pub-cache.

Pubspec for project as follows:

```yaml
name: project
description: project 2.0
dependencies:
  got:
    git:
      url: https://stash.metro.ad.company.com/scm/got/got.git
      ref: release/initial
  browser: any
  intl: any
```

Pubspec for library as follows:

```yaml
name: got
version: 0.0.1
description: Graphical objects toolkit.
dependencies:
  browser: any
```

```
pub install --trace --verbosity=all       
FINE: Pub 1.10.0
MSG : Resolving dependencies...
SLVR: Solving dependencies:
    | - got any from git ({ref: release/initial, url: https://stash.metro.ad.company.com/scm/got/got.git}) (locked to 0.0.1)
    | - intl any from hosted (intl) (locked to 0.12.4)
    | - browser any from hosted (browser) (locked to 0.10.0+2)
SLVR: | got 0.0.1 from git is locked
SLVR: * select got 0.0.1 from git
SLVR: | browser 0.10.0+2 from hosted is locked
SLVR: | * select browser 0.10.0+2 from hosted
SLVR: | | intl 0.12.4 from hosted is locked
SLVR: | | * select intl 0.12.4 from hosted
IO  : Spawning "git --version" in /home/xxx/Remote/Development/go/src/team-gui/dart/.
IO  : Finished git. Exit code 0.
    | stdout:
    | | git version 1.9.1
    | Nothing output on stderr.
FINE: Determined git command null.
IO  : Spawning "git rev-list --max-count=1 46f356bf32a657ca66e78998b744510f1ff23bbb" in /home/xxx/.pub-cache/git/cache/got-7cb20b5f8edae1686ea5349fec6bb52a3853196b
IO  : Finished git. Exit code 0.
    | stdout:
    | | 46f356bf32a657ca66e78998b744510f1ff23bbb
    | Nothing output on stderr.
SLVR: | | | analyzer 0.25.0+1 from hosted is locked
SLVR: | | | * select analyzer 0.25.0+1 from hosted
SLVR: | | | | args 0.13.2 from hosted is locked
SLVR: | | | | * select args 0.13.2 from hosted
SLVR: | | | | | path 1.3.5 from hosted is locked
SLVR: | | | | | * select path 1.3.5 from hosted
SLVR: | | | | | | petitparser 1.4.3 from hosted is locked
SLVR: | | | | | | * select petitparser 1.4.3 from hosted
SLVR: | | | | | | | watcher 0.9.6 from hosted is locked
SLVR: | | | | | | | * select watcher 0.9.6 from hosted
IO  : Spawning "git rev-list --max-count=1 46f356bf32a657ca66e78998b744510f1ff23bbb" in /home/xxx/.pub-cache/git/cache/got-7cb20b5f8edae1686ea5349fec6bb52a3853196b
IO  : Finished git. Exit code 0.
    | stdout:
    | | 46f356bf32a657ca66e78998b744510f1ff23bbb
    | Nothing output on stderr.
SLVR: BacktrackingSolver took 0:00:00.186847 seconds.
    | - Requested 0 version lists
    | - Looked up 0 cached version lists
    | - Requested 8 pubspecs
    | - Looked up 1 cached pubspecs
    | 
FINE: Resolving dependencies finished (0.198s).
IO  : Deleting directory /home/xxx/Remote/Development/go/src/team-gui/dart/packages.
IO  : Spawning "git rev-list --max-count=1 46f356bf32a657ca66e78998b744510f1ff23bbb" in /home/xxx/.pub-cache/git/cache/got-7cb20b5f8edae1686ea5349fec6bb52a3853196b
FINE: Creating link for package 'browser'.
FINE: Creating /home/xxx/Remote/Development/go/src/team-gui/dart/packages/browser pointing to /home/xxx/.pub-cache/hosted/pub.dartlang.org/browser-0.10.0+2/lib
FINE: Creating link for package 'intl'.
FINE: Creating /home/xxx/Remote/Development/go/src/team-gui/dart/packages/intl pointing to /home/xxx/.pub-cache/hosted/pub.dartlang.org/intl-0.12.4/lib
FINE: Creating link for package 'analyzer'.
FINE: Creating /home/xxx/Remote/Development/go/src/team-gui/dart/packages/analyzer pointing to /home/xxx/.pub-cache/hosted/pub.dartlang.org/analyzer-0.25.0+1/lib
FINE: Creating link for package 'args'.
FINE: Creating /home/xxx/Remote/Development/go/src/team-gui/dart/packages/args pointing to /home/xxx/.pub-cache/hosted/pub.dartlang.org/args-0.13.2/lib
FINE: Creating link for package 'path'.
FINE: Creating /home/xxx/Remote/Development/go/src/team-gui/dart/packages/path pointing to /home/xxx/.pub-cache/hosted/pub.dartlang.org/path-1.3.5/lib
FINE: Creating link for package 'petitparser'.
FINE: Creating /home/xxx/Remote/Development/go/src/team-gui/dart/packages/petitparser pointing to /home/xxx/.pub-cache/hosted/pub.dartlang.org/petitparser-1.4.3/lib
FINE: Creating link for package 'watcher'.
FINE: Creating /home/xxx/Remote/Development/go/src/team-gui/dart/packages/watcher pointing to /home/xxx/.pub-cache/hosted/pub.dartlang.org/watcher-0.9.6/lib
IO  : Finished git. Exit code 0.
    | stdout:
    | | 46f356bf32a657ca66e78998b744510f1ff23bbb
    | Nothing output on stderr.
IO  : Spawning "git rev-list --max-count=1 46f356bf32a657ca66e78998b744510f1ff23bbb" in /home/xxx/.pub-cache/git/cache/got-7cb20b5f8edae1686ea5349fec6bb52a3853196b
IO  : Finished git. Exit code 0.
    | stdout:
    | | 46f356bf32a657ca66e78998b744510f1ff23bbb
    | Nothing output on stderr.
IO  : Spawning "git checkout 46f356bf32a657ca66e78998b744510f1ff23bbb" in /home/xxx/.pub-cache/git/got-46f356bf32a657ca66e78998b744510f1ff23bbb
IO  : Finished git. Exit code 0.
    | Nothing output on stdout.
    | stderr:
    | | HEAD is now at 46f356b... Removed currently unused dependency in pubspec.yaml.
IO  : Spawning "git rev-list --max-count=1 46f356bf32a657ca66e78998b744510f1ff23bbb" in /home/xxx/.pub-cache/git/cache/got-7cb20b5f8edae1686ea5349fec6bb52a3853196b
IO  : Finished git. Exit code 0.
    | stdout:
    | | 46f356bf32a657ca66e78998b744510f1ff23bbb
    | Nothing output on stderr.
IO  : Writing 837 characters to text file /home/xxx/Remote/Development/go/src/team-gui/dart/pubspec.lock.
FINE: Contents:
    | # Generated by pub
    | # See http://pub.dartlang.org/doc/glossary.html#lockfile
    | packages:
    |   analyzer:
    |     description: analyzer
    |     source: hosted
    |     version: "0.25.0+1"
    |   args:
    |     description: args
    |     source: hosted
    |     version: "0.13.2"
    |   got:
    |     description:
    |       ref: "release/initial"
    |       resolved-ref: "46f356bf32a657ca66e78998b744510f1ff23bbb"
    |       url: "https://stash.metro.ad.company.com/scm/got/got.git"
    |     source: git
    |     version: "0.0.1"
    |   browser:
    |     description: browser
    |     source: hosted
    |     version: "0.10.0+2"
    |   intl:
    |     description: intl
    |     source: hosted
    |     version: "0.12.4"
    |   path:
    |     description: path
    |     source: hosted
    |     version: "1.3.5"
    |   petitparser:
    |     description: petitparser
    |     source: hosted
    |     version: "1.4.3"
    |   watcher:
    |     description: watcher
    |     source: hosted
    |     version: "0.9.6"
FINE: Creating selflink for package 'TEAM'.
FINE: Creating /home/xxx/Remote/Development/go/src/team-gui/dart/packages/TEAM pointing to ../lib
IO  : Deleting link /home/xxx/Remote/Development/go/src/team-gui/dart/web/packages.
FINE: Creating /home/xxx/Remote/Development/go/src/team-gui/dart/web/packages pointing to ../packages
IO  : Deleting link /home/xxx/Remote/Development/go/src/team-gui/dart/web/img/packages.
FINE: Creating /home/xxx/Remote/Development/go/src/team-gui/dart/web/img/packages pointing to ../../packages
IO  : Deleting link /home/xxx/Remote/Development/go/src/team-gui/dart/web/css/packages.
FINE: Creating /home/xxx/Remote/Development/go/src/team-gui/dart/web/css/packages pointing to ../../packages
MSG : Got dependencies!
FINE: Loading package graph...
IO  : Spawning "git rev-list --max-count=1 46f356bf32a657ca66e78998b744510f1ff23bbb" in /home/xxx/.pub-cache/git/cache/got-7cb20b5f8edae1686ea5349fec6bb52a3853196b
IO  : Finished git. Exit code 0.
    | stdout:
    | | 46f356bf32a657ca66e78998b744510f1ff23bbb
    | Nothing output on stderr.
FINE: Loading package graph finished (0.010s).
```

_Copied from original issue: dart-lang/sdk#23727_

**Comment by nex3** [comment] 2015-09-02 18:00
@halverneus Can you still reproduce this with Pub 1.12.0?

**Comment by halverneus** [comment] 2015-09-02 19:05
Still having the issue...

With 1.12.0 on Ubuntu 14.04, I am seeing an entry added into the .packages file (see 'bluex'):

analyzer:file:///home/jerostre/.pub-cache/hosted/pub.dartlang.org/analyzer-0.26.1+3/lib/
args:file:///home/jerostre/.pub-cache/hosted/pub.dartlang.org/args-0.13.2/lib/
bluex:file:///home/jerostre/.pub-cache/git/bluex-46f356bf32a657ca66e78998b744510f1ff23bbb/lib/
browser:file:///home/jerostre/.pub-cache/hosted/pub.dartlang.org/browser-0.10.0+2/lib/
charcode:file:///home/jerostre/.pub-cache/hosted/pub.dartlang.org/charcode-1.1.0/lib/
collection:file:///home/jerostre/.pub-cache/hosted/pub.dartlang.org/collection-1.1.2/lib/
csslib:file:///home/jerostre/.pub-cache/hosted/pub.dartlang.org/csslib-0.12.1/lib/
glob:file:///home/jerostre/.pub-cache/hosted/pub.dartlang.org/glob-1.0.5/lib/
html:file:///home/jerostre/.pub-cache/hosted/pub.dartlang.org/html-0.12.2/lib/
intl:file:///home/jerostre/.pub-cache/hosted/pub.dartlang.org/intl-0.12.4+2/lib/
logging:file:///home/jerostre/.pub-cache/hosted/pub.dartlang.org/logging-0.11.1+1/lib/
package_config:file:///home/jerostre/.pub-cache/hosted/pub.dartlang.org/package_config-0.1.3/lib/
path:file:///home/jerostre/.pub-cache/hosted/pub.dartlang.org/path-1.3.6/lib/
petitparser:file:///home/jerostre/.pub-cache/hosted/pub.dartlang.org/petitparser-1.4.3/lib/
plugin:file:///home/jerostre/.pub-cache/hosted/pub.dartlang.org/plugin-0.1.0/lib/
source_span:file:///home/jerostre/.pub-cache/hosted/pub.dartlang.org/source_span-1.1.6/lib/
string_scanner:file:///home/jerostre/.pub-cache/hosted/pub.dartlang.org/string_scanner-0.1.4/lib/
utf:file:///home/jerostre/.pub-cache/hosted/pub.dartlang.org/utf-0.9.0+2/lib/
watcher:file:///home/jerostre/.pub-cache/hosted/pub.dartlang.org/watcher-0.9.7/lib/
yaml:file:///home/jerostre/.pub-cache/hosted/pub.dartlang.org/yaml-2.1.3/lib/
TEAM:lib/

But I am not seeing seeing it appear in the packages directory (result of ls -la):

analyzer -> /home/jerostre/.pub-cache/hosted/pub.dartlang.org/analyzer-0.26.1+3/lib
args -> /home/jerostre/.pub-cache/hosted/pub.dartlang.org/args-0.13.2/lib
browser -> /home/jerostre/.pub-cache/hosted/pub.dartlang.org/browser-0.10.0+2/lib
charcode -> /home/jerostre/.pub-cache/hosted/pub.dartlang.org/charcode-1.1.0/lib
collection -> /home/jerostre/.pub-cache/hosted/pub.dartlang.org/collection-1.1.2/lib
csslib -> /home/jerostre/.pub-cache/hosted/pub.dartlang.org/csslib-0.12.1/lib
glob -> /home/jerostre/.pub-cache/hosted/pub.dartlang.org/glob-1.0.5/lib
html -> /home/jerostre/.pub-cache/hosted/pub.dartlang.org/html-0.12.2/lib
intl -> /home/jerostre/.pub-cache/hosted/pub.dartlang.org/intl-0.12.4+2/lib
logging -> /home/jerostre/.pub-cache/hosted/pub.dartlang.org/logging-0.11.1+1/lib
package_config -> /home/jerostre/.pub-cache/hosted/pub.dartlang.org/package_config-0.1.3/lib
path -> /home/jerostre/.pub-cache/hosted/pub.dartlang.org/path-1.3.6/lib
petitparser -> /home/jerostre/.pub-cache/hosted/pub.dartlang.org/petitparser-1.4.3/lib
plugin -> /home/jerostre/.pub-cache/hosted/pub.dartlang.org/plugin-0.1.0/lib
source_span -> /home/jerostre/.pub-cache/hosted/pub.dartlang.org/source_span-1.1.6/lib
string_scanner -> /home/jerostre/.pub-cache/hosted/pub.dartlang.org/string_scanner-0.1.4/lib
TEAM -> ../lib
utf -> /home/jerostre/.pub-cache/hosted/pub.dartlang.org/utf-0.9.0+2/lib
watcher -> /home/jerostre/.pub-cache/hosted/pub.dartlang.org/watcher-0.9.7/lib
yaml -> /home/jerostre/.pub-cache/hosted/pub.dartlang.org/yaml-2.1.3/lib

I have cleared any existing data from .pub-cache/git, removed the 'packages' directory and have tried pub install and pub upgrade. Is there any more information I can provide or suggestions to try? As a note, I do have to entry a username and password for the Git repo, which takes me several seconds.

Thanks!

**Comment by halverneus** [comment] 2015-09-02 19:13
If it helps, running with --trace --verbosity=all, when it reaches  the point where links are created:

FINE: Creating link for package 'browser'.
FINE: Creating ./packages/browser pointing to /home/jerostre/.pub-cache/hosted/pub.dartlang.org/browser-0.10.0+2/lib

There is no entry for bluex, as well as no error. There is this immediately before the link creations:

IO  : Deleting directory ./packages.
IO  : Spawning "git rev-list --max-count=1 46f356bf32a657ca66e78998b744510f1ff23bbb" in /home/jerostre/.pub-cache/git/cache/bluex-7cb20b5f8edae1686ea5349fec6bb52a3853196b

And this immediately after the last link creation:

IO  : Finished git. Exit code 0.
    | stdout:
    | | 46f356bf32a657ca66e78998b744510f1ff23bbb
    | Nothing output on stderr.
IO  : Spawning "git rev-list --max-count=1 46f356bf32a657ca66e78998b744510f1ff23bbb" in /home/jerostre/.pub-cache/git/cache/bluex-7cb20b5f8edae1686ea5349fec6bb52a3853196b
IO  : Finished git. Exit code 0.
    | stdout:
    | | 46f356bf32a657ca66e78998b744510f1ff23bbb
    | Nothing output on stderr.
IO  : Spawning "git checkout 46f356bf32a657ca66e78998b744510f1ff23bbb" in /home/jerostre/.pub-cache/git/bluex-46f356bf32a657ca66e78998b744510f1ff23bbb
IO  : Finished git. Exit code 0.
    | Nothing output on stdout.
    | stderr:
    | | HEAD is now at 46f356b... Removed currently unused dependency in pubspec.yaml.
IO  : Spawning "git rev-list --max-count=1 46f356bf32a657ca66e78998b744510f1ff23bbb" in /home/jerostre/.pub-cache/git/cache/bluex-7cb20b5f8edae1686ea5349fec6bb52a3853196b
IO  : Finished git. Exit code 0.
    | stdout:
    | | 46f356bf32a657ca66e78998b744510f1ff23bbb
    | Nothing output on stderr.
IO  : Writing 1797 characters to text file ./pubspec.lock.

**Comment by nex3** [comment] 2015-09-02 20:18
I obviously can't access the repo you're using, but I'm unable to reproduce with a public Git repo. @halverneus, does this happen with any Git repo, or is it unique to `https://stash.metro.ad.company.com/scm/got/got.git`?

**Comment by halverneus** [comment] 2015-09-03 15:25
I'm out of ideas, but it does seem to be something specific to the company's server. I created a public repo and even removed the "ref:" and the "user@". Judging from this output (and knowing nothing about the code), I would guess some kind of race condition, as Git seems to be doing a lot after the links are made that I would guess would occur before they are made ("bluex" as the culprit). The Stash server does sit behind a reverse proxy, but I would expect the SSH to work in that instance.

FINE: Resolving dependencies finished (2.570s).
MSG : * bluex 0.0.1 from git https://stash.metro.ad.company.com/scm/dar/darttest.git at 183f7b (was 0.0.1 from git https://jerostre@stash.metro.ad.company.com/scm/dar/darttest.git at 183f7b)
IO  : Spawning "git rev-list --max-count=1 183f7b7abc35305e6a8500b24218aa94636bfff5" in /home/jerostre/.pub-cache/git/cache/bluex-fc7301fdaf5d58b32a2f75476c0298d6bcdf7e4a
FINE: Creating link for package 'browser'.
FINE: Creating ./packages/browser pointing to /home/jerostre/.pub-cache/hosted/pub.dartlang.org/browser-0.10.0+2/lib
FINE: Creating link for package 'intl'.
FINE: Creating ./packages/intl pointing to /home/jerostre/.pub-cache/hosted/pub.dartlang.org/intl-0.12.4+2/lib
FINE: Creating link for package 'analyzer'.
FINE: Creating ./packages/analyzer pointing to /home/jerostre/.pub-cache/hosted/pub.dartlang.org/analyzer-0.26.1+3/lib
FINE: Creating link for package 'args'.
FINE: Creating ./packages/args pointing to /home/jerostre/.pub-cache/hosted/pub.dartlang.org/args-0.13.2/lib
FINE: Creating link for package 'glob'.
FINE: Creating ./packages/glob pointing to /home/jerostre/.pub-cache/hosted/pub.dartlang.org/glob-1.0.5/lib
FINE: Creating link for package 'collection'.
FINE: Creating ./packages/collection pointing to /home/jerostre/.pub-cache/hosted/pub.dartlang.org/collection-1.1.2/lib
FINE: Creating link for package 'html'.
FINE: Creating ./packages/html pointing to /home/jerostre/.pub-cache/hosted/pub.dartlang.org/html-0.12.2/lib
FINE: Creating link for package 'csslib'.
FINE: Creating ./packages/csslib pointing to /home/jerostre/.pub-cache/hosted/pub.dartlang.org/csslib-0.12.1/lib
FINE: Creating link for package 'logging'.
FINE: Creating ./packages/logging pointing to /home/jerostre/.pub-cache/hosted/pub.dartlang.org/logging-0.11.1+1/lib
FINE: Creating link for package 'package_config'.
FINE: Creating ./packages/package_config pointing to /home/jerostre/.pub-cache/hosted/pub.dartlang.org/package_config-0.1.3/lib
FINE: Creating link for package 'charcode'.
FINE: Creating ./packages/charcode pointing to /home/jerostre/.pub-cache/hosted/pub.dartlang.org/charcode-1.1.0/lib
FINE: Creating link for package 'path'.
FINE: Creating ./packages/path pointing to /home/jerostre/.pub-cache/hosted/pub.dartlang.org/path-1.3.6/lib
FINE: Creating link for package 'petitparser'.
FINE: Creating ./packages/petitparser pointing to /home/jerostre/.pub-cache/hosted/pub.dartlang.org/petitparser-1.4.3/lib
FINE: Creating link for package 'plugin'.
FINE: Creating ./packages/plugin pointing to /home/jerostre/.pub-cache/hosted/pub.dartlang.org/plugin-0.1.0/lib
FINE: Creating link for package 'source_span'.
FINE: Creating ./packages/source_span pointing to /home/jerostre/.pub-cache/hosted/pub.dartlang.org/source_span-1.1.6/lib
FINE: Creating link for package 'string_scanner'.
FINE: Creating ./packages/string_scanner pointing to /home/jerostre/.pub-cache/hosted/pub.dartlang.org/string_scanner-0.1.4/lib
FINE: Creating link for package 'utf'.
FINE: Creating ./packages/utf pointing to /home/jerostre/.pub-cache/hosted/pub.dartlang.org/utf-0.9.0+2/lib
FINE: Creating link for package 'watcher'.
FINE: Creating ./packages/watcher pointing to /home/jerostre/.pub-cache/hosted/pub.dartlang.org/watcher-0.9.7/lib
FINE: Creating link for package 'yaml'.
FINE: Creating ./packages/yaml pointing to /home/jerostre/.pub-cache/hosted/pub.dartlang.org/yaml-2.1.3/lib
IO  : Finished git. Exit code 0.
    | stdout:
    | | 183f7b7abc35305e6a8500b24218aa94636bfff5
    | Nothing output on stderr.
IO  : Spawning "git rev-list --max-count=1 183f7b7abc35305e6a8500b24218aa94636bfff5" in /home/jerostre/.pub-cache/git/cache/bluex-fc7301fdaf5d58b32a2f75476c0298d6bcdf7e4a
IO  : Finished git. Exit code 0.
    | stdout:
    | | 183f7b7abc35305e6a8500b24218aa94636bfff5
    | Nothing output on stderr.
IO  : Spawning "git checkout 183f7b7abc35305e6a8500b24218aa94636bfff5" in /home/jerostre/.pub-cache/git/bluex-183f7b7abc35305e6a8500b24218aa94636bfff5
IO  : Finished git. Exit code 0.
    | Nothing output on stdout.
    | stderr:
    | | Note: checking out '183f7b7abc35305e6a8500b24218aa94636bfff5'.
    | | 
    | | You are in 'detached HEAD' state. You can look around, make experimental
    | | changes and commit them, and you can discard any commits you make in this
    | | state without impacting any branches by performing another checkout.
    | | 
    | | If you want to create a new branch to retain commits you create, you may
    | | do so (now or later) by using -b with the checkout command again. Example:
    | | 
    | |   git checkout -b new_branch_name
    | | 
    | | HEAD is now at 183f7b7... Testing
IO  : Spawning "git rev-list --max-count=1 183f7b7abc35305e6a8500b24218aa94636bfff5" in /home/jerostre/.pub-cache/git/cache/bluex-fc7301fdaf5d58b32a2f75476c0298d6bcdf7e4a
IO  : Finished git. Exit code 0.
    | stdout:
    | | 183f7b7abc35305e6a8500b24218aa94636bfff5
    | Nothing output on stderr.
IO  : Writing 1763 characters to text file ./pubspec.lock.
FINE: Contents:
    | # Generated by pub
    | # See http://pub.dartlang.org/doc/glossary.html#lockfile
    | packages:
    |   analyzer:
    |     description: analyzer
    |     source: hosted
    |     version: "0.26.1+3"
    |   args:
    |     description: args
    |     source: hosted
    |     version: "0.13.2"
    |   bluex:
    |     description:
    |       ref: null
    |       resolved-ref: "183f7b7abc35305e6a8500b24218aa94636bfff5"
    |       url: "https://stash.metro.ad.company.com/scm/dar/darttest.git"
    |     source: git
    |     version: "0.0.1"

**Comment by halverneus** [comment] 2015-09-03 15:33
Forgot to mention, it does work as expected if I grab from GitHub.

**Comment by nex3** [comment] 2015-09-08 19:47
And as far as you can tell, the `~/.pub-cache/git` directory looks normal? That's very strange—I can't imagine why pub would be able to resolve the ref well enough to put it in the `.packages` file, but wouldn't create the symlink.

At this point, since I can't reproduce this locally, I think the best course of action is for you to debug it manually by running a local checkout of pub and debugging via observatory or `print()` statements to try to figure out where it's going off the rails. Are you up for that?

Alternately, just rely on the `.packages` file. The `packages/` directory will be gone in a few releases anyway.

**Comment by halverneus** [comment] 2015-09-08 20:38
When I get time, I'll try some debugging (though, if the feature is going away, I might just pass entirely). Just because I haven't completely grasped the implications for the migration to the .packages file (and I might be able to rely completely on that if I can get this question answered), how does one go about serving the library .dart files with what is in the .packages file? Currently, I have my server written in Go and serving the .dart files statically to Dartium during development (of course compiling to JS for release, but that is time consuming to iterate on). Do I need to parse the .packages file to handle the serving of libraries? (if yes, seems like a bit of a regression, but one that I can live with. It does make me worry about initial adoption for newcomers, though.)

**Comment by nex3** [comment] 2015-09-08 21:01
If your server is fully non-Dart, you will need to parse the `.packages` file to serve your app in a way that Dartium will understand it. It's unfortunate, but we strongly believe it's less unfortunate than the manifold agonies that symlinks have caused.

If you have Dart involved in your server at all, we'll be providing a `shelf` handler that does this for you.

**Comment by halverneus** [comment] 2015-09-08 21:26
Thanks!

**Comment by nex3** [comment] 2015-12-08 23:50
I'm closing this since there's not much I can do about it without more information.

**Closed by nex3** 2015-12-08 23:50 UTC
Labels: bug, needs info
