### ISSUE TITLE
Unable to run tests on Windows with special chars in folder name

### ISSUE THREAD

**Issue by d-markey** [dart-lang/pub#3181] opened 2021-10-17 09:28 UTC
Hello,

I can't get dart test to work correctly in my environment. Test code will run happily with `dart run` and on Github Actions, but not from a PS terminal in VS Code.

I get the output:

```
PS C:\#Projects\github\squadron> dart run test
00:00 +0 ~1 -1: [VM] loading test\squadron_vm_worker_pool_test.dart [E]
  Bad state: Unable to find a package config
  package:test_core/src/util/package_config.dart 17:5      packageConfigUri.<fn>
  ===== asynchronous gap ===========================
  package:test_core/src/runner/package_version.dart 19:50  _rootPackageLanguageVersionComment.<fn>   
  ===== asynchronous gap ===========================
  package:test_core/src/runner/vm/test_compiler.dart 52:9  TestCompiler.compile
  ===== asynchronous gap ===========================
  package:test_core/src/runner/vm/platform.dart 148:9      VMPlatform._spawnKernelIsolate
  ===== asynchronous gap ===========================
  package:test_core/src/runner/vm/platform.dart 55:11      VMPlatform.load
  ===== asynchronous gap ===========================
  package:test_core/src/runner/loader.dart 224:25          Loader.loadFile.<fn>
  ===== asynchronous gap ===========================
  package:test_core/src/runner/load_suite.dart 97:21       new LoadSuite.<fn>.<fn>
  
  Failed to load "test\squadron_vm_worker_pool_test.dart": Bad state: Unable to find a package config
  package:test_core/src/util/package_config.dart 17:5      packageConfigUri.<fn>
  ===== asynchronous gap ===========================
  package:test_core/src/runner/package_version.dart 19:50  _rootPackageLanguageVersionComment.<fn>
  ===== asynchronous gap ===========================
  package:test_core/src/runner/vm/test_compiler.dart 52:9  TestCompiler.compile
  ===== asynchronous gap ===========================
  package:test_core/src/runner/vm/platform.dart 148:9      VMPlatform._spawnKernelIsolate
  ===== asynchronous gap ===========================
  package:test_core/src/runner/vm/platform.dart 55:11      VMPlatform.load
  ===== asynchronous gap ===========================
  package:test_core/src/runner/loader.dart 224:25          Loader.loadFile.<fn>
  ===== asynchronous gap ===========================
  package:test_core/src/runner/load_suite.dart 97:21       new LoadSuite.<fn>.<fn>
```

I'm using:

```
test: ^1.18.2
Dart SDK version: 2.14.4 (stable) (Wed Oct 13 11:11:32 2021 +0200) on "windows_x64"
```

Source code (and Github Action results for the Dart Workflow) is available from https://github.com/d-markey/squadron

I'm still able to run tests manually with `dart run` and I implemented a Web page to run tests for JavaScript, but I'd like to be 100% compliant with standard test practices.

Any idea on what I'm missing?

**Comment by jakemac53** [comment] 2021-10-18 16:54
Transferring this issue to pub at least for now, as that seems to be the root cause (although it could be something to do with `dart pub` specifically?

@d-markey can you confirm by trying just `pub run bin/example.dart` as well?

**Comment by d-markey** [comment] 2021-10-18 21:34
Here's some output but `pub run` failed,
I found a `pub.bat` tool and tried with this one.
Don't know if this helps, but I'm running Dart from a Flutter installation.

```
PS C:\#Projects\github\squadron> pub run .\bin\example.dart
pub: The term 'pub' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\#Projects\github\squadron> C:\src\flutter\bin\cache\dart-sdk\bin\pub.bat run .\bin\example.dart
file:///C:/%23Projects/github/squadron/.dart_tool/package_config.json
```

@jakemac53 thanks a lot for your help!

**Comment by sigurdm** [comment] 2024-08-23 13:54
If there is still a problem here, please reopen

**Closed** 2024-08-23 13:53 UTC
Labels: type-bug
