### ISSUE TITLE
pub get take forever

### ISSUE THREAD

**Issue by Kleak** [dart-lang/pub#1435] opened 2016-07-29 16:43 UTC
here are the dependencies that make pub take forever: 
```yaml
dependencies:
  rpc: 0.5.6+1
  logging: 0.11.3+1
  logging_handlers: 0.8.0
  http_server: 0.9.5+1
  mongo_dart: 0.2.9
  crypto: 1.1.1
  dson: 0.3.4
```

if you comment dson dependencies and launch pub get then un-comment dson dependencies and re-launch pub get everything is working..

Thx

**Comment by nex3** [comment] 2016-08-01 19:19
Duplicate of #912.

**Closed by nex3** 2016-08-01 19:19 UTC
