### ISSUE TITLE
Cannot have `docs/` directory at the root of project

### ISSUE THREAD

**Issue by imaNNeoFighT** [dart-lang/pub#3326] opened 2022-03-03 20:36 UTC
# Environment

- `pub version` or `flutter pub version`: **Pub 2.16.1**
- OS version: **macOS Big Sur version 11.4 (20F71)**
- Are you using the Chinese community mirror or a corporate firewall? **No**

# Problem
I need to have a directory called `docs` at the root of my project (because I want to use [docs.page](https://docs.page/homepage) service to generate documentation pages). 
When I run `flutter pub publish --dry-run` it fails with the error below:
```
Package validation found the following potential issue:
* Rename the top-level "docs" directory to "doc".
  The Pub layout convention is to use singular directory names.
  Plural names won't be correctly identified by Pub and other tools.
```

Although I tried to put `docs/` in my .pubignore file, it didn't work.

You can check [this failing workflow](https://github.com/imaNNeoFighT/fl_chart/runs/5413219360?check_suite_focus=true) for more details.

There is a similar closed issue here: #2976 
I couldn't find any solution there.

**Comment by sigurdm** [comment] 2022-03-04 09:15
First this is only a warning. You can publish tot pub.dev anyways.

I think we might have to rethink this if [docs.page](https://docs.page/homepage) becomes a thing.

Anyways the validator is listing files with `listDir(entryPoint.root.dir)` instead of `entryPoint.root.listFiles()` if we change that .pubignores would be respected. But that would still mean the `docs` folder would not get published - that might or might not be what we want.

@jonasfj WDYT?

**Comment by jonasfj** [comment] 2022-03-04 09:46
I think it's fine to respect `.pubignore` in the validators. That makes sense, and would be a possible workaround.

But this is just a **warning** it can be ignored, see:
https://github.com/dart-lang/pub/blob/b93bf88f3195003c3411a8047df240598de377ff/lib/src/validator/directory.dart#L35

You get this warning because you're package is violating: https://dart.dev/tools/pub/package-layout

Closing this as working as intended.

**Closed by jonasfj** 2022-03-04 09:46 UTC

**Comment by jonasfj** [comment] 2022-03-04 09:50
Filed:
 * https://github.com/dart-lang/pub/issues/3327
 * https://github.com/dart-lang/pub/issues/3328

**Comment by imaNNeoFighT** [comment] 2022-03-04 11:39
> `ocs` folder would not get publish

I think we don't need to publish `docs` directory.
It only needs to exist in the repository.

**Comment by imaNNeoFighT** [comment] 2022-03-04 11:44
I use [this Github Action](https://github.com/sakebook/actions-flutter-pub-publisher) to publish my package in CI.
I don't understand how I can configure it to ignore that specific warning.
