### ISSUE TITLE
flutter doctor fail

### ISSUE THREAD

**Issue by muzuro** [dart-lang/pub#1736] opened 2017-11-06 21:07 UTC
I am trying to install flutter on ubuntu accoring to https://flutter.io/setup-linux/#system-requirements. After running `flutter doctor` i receive following error:

```
mzr@qdev:~/flutter$ flutter doctor
Building flutter tool...
Unexpected character (at character 1)
Internal error
^
dart:convert                                              JsonCodec.decode
package:pub/src/source/hosted.dart 143                    BoundHostedSource.doGetVersions
===== asynchronous gap ===========================
package:pub/src/source.dart 165                           BoundSource.getVersions
package:pub/src/solver/version_solver.dart 231            SolverCache.getVersions.<fn>
dart:async                                                runZoned
package:pub/src/http.dart 228                             withDependencyType
package:pub/src/solver/version_solver.dart 230            SolverCache.getVersions
===== asynchronous gap ===========================
package:pub/src/solver/unselected_package_queue.dart 121  UnselectedPackageQueue._getNumVersions
===== asynchronous gap ===========================
package:pub/src/solver/unselected_package_queue.dart 50   UnselectedPackageQueue.add
===== asynchronous gap ===========================
package:pub/src/solver/version_selection.dart 68          VersionSelection.select.<fn>
===== asynchronous gap ===========================
dart:async                                                _completeOnAsyncReturn
package:pub/src/solver/version_selection.dart 70          VersionSelection.select.<fn>
dart:async                                                _completeOnAsyncReturn
package:pub/src/solver/unselected_package_queue.dart 54   UnselectedPackageQueue.add
dart:async                                                _completeOnAsyncReturn
package:pub/src/solver/unselected_package_queue.dart 128  UnselectedPackageQueue._getNumVersions
dart:async                                                _Completer.completeError
package:pub/src/solver/version_solver.dart 254            SolverCache.getVersions
dart:async                                                _Completer.completeError
package:pub/src/source/hosted.dart 153                    BoundHostedSource.doGetVersions
This is an unexpected error. Please run

    pub --trace upgrade --verbosity=error --no-packages-dir

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Error: Unable to pub upgrade flutter tool. Retrying in five seconds...
```

**Comment by nex3** [comment] 2017-11-06 21:09
Duplicate of #1735.

**Closed by nex3** 2017-11-06 21:09 UTC
