### ISSUE TITLE
pub get runs forever

### ISSUE THREAD

**Issue by floitschG** [dart-lang/pub#1445] opened 2016-08-31 13:11 UTC
_From @sigi77 on August 31, 2016 7:47_

Resolving the dependencies doesn't seem to finish. When I remove [google_oauth2_client](https://pub.dartlang.org/packages/google_oauth2_client) it runs quickly. 

pubspec.yaml:

name: intranet_angular2
description: A Dart app that uses Angular 2
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  google_oauth2_client: ^0.4.2
  angular2: 2.0.0-beta.20
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter

_Copied from original issue: dart-lang/sdk#27204_

**Comment by trentgrover-wf** [comment] 2016-08-31 19:03
anecdotally, we've found the most common solution to this problem is to limit the analyzer dependency (we don't use angular though, so not 100% sure that will fix you)

```
dev_dependencies:
  analyzer: ^0.27.3
```

**Comment by nex3** [comment] 2016-08-31 19:44
Duplicate of #912.

**Closed by nex3** 2016-08-31 19:44 UTC
