### ISSUE TITLE
error

### ISSUE THREAD

**Issue by fullmonty04** [dart-lang/pub#4329] opened 2024-07-19 13:46 UTC
Null check operator used on a null value
package:pub/src/source/hosted.dart 760:33              HostedSource._getAdvisories.readAdvisoriesFromCache
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 778:12              HostedSource._getAdvisories
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 1066:24             HostedSource.getAdvisoriesForPackageVersion
===== asynchronous gap ===========================
package:pub/src/solver/report.dart 414:26              SolveReport._reportPackage
===== asynchronous gap ===========================
package:pub/src/solver/report.dart 218:18              SolveReport._reportChanges
===== asynchronous gap ===========================
package:pub/src/solver/report.dart 73:21               SolveReport.show
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 568:5                  Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 77:5                  GetCommand.runProtected
===== asynchronous gap ===========================
package:pub/src/command.dart 196:7                     PubCommand.run
===== asynchronous gap ===========================
package:args/command_runner.dart 212:13                CommandRunner.runCommand
===== asynchronous gap ===========================
package:dartdev/dartdev.dart 232:18                    DartdevRunner.runCommand
===== asynchronous gap ===========================
package:dartdev/dartdev.dart 46:16                     runDartdev
===== asynchronous gap ===========================
C:\b\s\w\ir\x\w\sdk\pkg\dartdev\bin\dartdev.dart 13:5  main
This is an unexpected error. The full log and other details are collected in:

    C:\Users\matha\AppData\Local\Pub\Cache\log\pub_log.txt

Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.

**Comment by sigurdm** [comment] 2024-07-29 11:15
Duplicate of https://github.com/dart-lang/pub/issues/4269

This is be fixed in 3.4.4 https://github.com/dart-lang/sdk/blob/stable/CHANGELOG.md#344---2024-06-12

**Closed by sigurdm** 2024-07-29 11:15 UTC
