### ISSUE TITLE
Misleading error message from `pub get` on unsatisfiable constraint

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/pub#1421] opened 2016-06-06 09:11 UTC
Here is an example:
```
# origin/master is ffe453c751 at this point in time.

$ git clone https://github.com/dart-lang/test
$ pub get
Resolving dependencies... (4.9s) 
Package scheduled_test has no versions that match >=0.12.5 <0.13.0 derived from:
- test depends on version ^0.12.5
$ pub --version
Pub 1.17.0-dev.6.4
```

This message is wrong, because there are versions of `package:scheduled_test` that lie within that range (e.g. 0.12.5+5). 

What is fails to tell is that there is a cyclic dependency between `package:test`  and `package:scheduled_test` (though one of the dependencies is only a dev dependency) and that this cycle is unsatisfiable!

**Comment by nex3** [comment] 2016-06-06 19:39
Duplicate of #912. I really ought to rename that issue.

**Closed by nex3** 2016-06-06 19:39 UTC
