### ISSUE TITLE
"pub get" failing for git repositories when run from Windows with git version 2.5.3.windows.1

### ISSUE THREAD

**Issue by sgerhardt** [dart-lang/pub#1372] opened 2015-12-23 23:53 UTC
Setup:
OS: Windows 8 64 bit
Git: git version 2.5.3.windows.1
Dart SDK: 1.13
IDE: WebStorm 11.0.2

Issue:
"pub get" failing for git repositories when run from Windows with git version 2.5.3.windows.1. This happens when ".git" is not added to the line specifying the git repository location.

Expected Operation:
I believe the expected behavior is for it to work with or without the ".git" at the end of the line specifying the repository.

When I try to do a "pub get" on the following .yaml for example:

    name: unittest_v1
    description: A sample command-line application
    dependencies:
      dartlero:
        git: https://github.com/dzenanr/dartlero
      test: any

I get the following output error, `C:\tools\dart-sdk\bin\pub.bat get
Resolving dependencies...
Git error. Command: git fetch
fatal: Not a git repository (or any of the parent directories): .git
Process finished with exit code 1`

It appears that simply making the git line, "`git: https://github.com/dzenanr/dartlero.git` (adding .git to the end)" fixes the issue. I've run the same command on OS X on yaml without the ".git" with success using a different version of git. 
![image](https://cloud.githubusercontent.com/assets/4251684/11987055/02ebeeee-a99e-11e5-8d54-f403856ae89d.png)

**Comment by Andersmholmgren** [comment] 2015-12-27 05:47
I also get an error on git dependencies but I'm on a mac and the output is different

```
 pub get --trace
Resolving dependencies... 
Error on line 14, column 7 of pubspec.yaml: Invalid description: Illegal scheme character
      url: git@bitbucket.org:andersmholmgren/hateoas_models.git
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
---- Log transcript ----
FINE: Pub 1.14.0-dev.5.0
FINE: Resolving dependencies finished (0.0s).
ERR : Error on line 14, column 7 of pubspec.yaml: Invalid description: Illegal scheme character
    |       url: git@bitbucket.org:andersmholmgren/hateoas_models.git
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FINE: Exception type: PubspecException
FINE: package:pub/src/pubspec.dart 573                     Pubspec._error
    | package:pub/src/pubspec.dart 559                     Pubspec._wrapFormatException
    | package:pub/src/pubspec.dart 499                     Pubspec._parseDependencies.<fn>
    | dart:collection                                      MapView.forEach
    | package:pub/src/pubspec.dart 450                     Pubspec._parseDependencies
    | package:pub/src/pubspec.dart 114                     Pubspec.dependencies
    | package:pub/src/package.dart 53                      Package.dependencies
    | package:pub/src/solver/backtracking_solver.dart 619  BacktrackingSolver._logParameters
    | package:pub/src/solver/backtracking_solver.dart 155  BacktrackingSolver.solve.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           _Completer.completeError
    | package:pub/src/solver/backtracking_solver.dart 201  BacktrackingSolver.solve.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.Future.microtask
    | package:pub/src/solver/backtracking_solver.dart      BacktrackingSolver.solve
    | package:pub/src/solver/version_solver.dart 40        resolveVersions.<fn>
    | package:pub/src/log.dart 393                         progress
    | package:pub/src/solver/version_solver.dart 38        resolveVersions
    | package:pub/src/entrypoint.dart 158                  Entrypoint.acquireDependencies.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.Future.microtask
    | package:pub/src/entrypoint.dart                      Entrypoint.acquireDependencies
    | package:pub/src/command/get.dart 30                  GetCommand.run
    | package:args/command_runner.dart 178                 CommandRunner.runCommand.<fn>
    | dart:async                                           Future.Future.sync
    | package:args/command_runner.dart 131                 CommandRunner.runCommand
    | package:pub/src/command_runner.dart 130              PubCommandRunner.runCommand.<async>.<fn>
    | dart:async                                           Future.Future.sync
    | package:pub/src/utils.dart 111                       captureErrors.<fn>
    | package:stack_trace                                  Chain.capture
    | package:pub/src/utils.dart 125                       captureErrors
    | package:pub/src/command_runner.dart 130              PubCommandRunner.runCommand.<async>
---- End log transcript ----
```

It works with 1.13.1 though

```
description: A library useful for applications or for sharing on pub.dartlang.org.
name: frentity
version: 1.4.7
dependencies: 
  built_collection: '^1.0.0'
  frappe: '^0.4.0+2'
  logging: '>=0.9.2'
  observe: '^0.13.1'
  option: '>=0.3.3 <2.0.0'
  quiver: '^0.21.0'
  uri: '>=0.9.5'
  hateoas_models:
    git: 
      url: git@bitbucket.org:andersmholmgren/hateoas_models.git
      ref: aac65e3b864f64dc62785c12d982ff752c917c0d
  stuff:
    git: 
      url: git@bitbucket.org:andersmholmgren/stuff.git
      ref: 15f054476b69d88fc6a8a2566d30f2b351f98b57
dependency_overrides:
dev_dependencies: 
  guinness: '^0.1.17'
  mockito: '>=0.10.0 <0.11.0'
  test: '^0.12.0'
environment: 
  sdk: '>=1.9.0 <2.0.0'
```

**Comment by travissanderson-wf** [comment] 2015-12-28 22:43
this looks like a duplicate report of https://github.com/dart-lang/pub/issues/1368

**Comment by sgerhardt** [comment] 2015-12-28 22:54
The previous two comments here are issues that may be related to git, but are not producing the same error message that I encountered. Note that my issue is resolved when I append ".git" to the dependency.

**Comment by travissanderson-wf** [comment] 2015-12-28 23:05
Ah, I didn't read your comment closely enough, but it sounds like @Andersmholmgren is hitting the same issue I linked.  Sorry about that!

**Comment by travissanderson-wf** [comment] 2015-12-28 23:06
Now I'm curious, is it expected to work without `.git`?  GitHub puts that in the URL for cloning.

**Comment by Andersmholmgren** [comment] 2015-12-28 23:07
Thanks @travissanderson I added my comment to the wrong issue it seems

**Comment by sgerhardt** [comment] 2015-12-28 23:15
@travissanderson-wf I believe it should work without `.git`. Dzenan Ridjanovic (@dzenanr on github) uses dependencies without `.git` in his book, "Learning Dart Second Edition". Also, as stated in my issue, it seems to work with some versions of git and not others.

**Comment by nex3** [comment] 2016-01-04 21:01
@sgerhardt Please include the full output of `pub get --verbose`. Also, what happens when you run `git clone https://github.com/dzenanr/dartlero` manually from the command line?

**Comment by sgerhardt** [comment] 2016-01-06 23:34
@nex3
When I try to clone I get,

 ```git clone https://github.com/dzenanr/dartlero
Cloning into 'dartlero'...
fatal: unable to access 'https://github.com/dzenanr/dartlero/': Couldn't resolve host 'github.com'```

After seeing this, I suspect this is more a difference/bug with Windows git than an issue with dart. Now it seems like a gray area to me, where would it be best to address this issue - the dart or windows git project?

Also, here's the output from verbose:

```eBundle\B04292_Learning_Dart_2_Chapter 3\code\unittest_v1>pub get --verbose
FINE: Pub 1.13.0
IO  : Spawning "cmd /c ver" in I:\Downloads\LearningDart2ndEdition_CodeBundle_Latest\LearningDart2ndEdition_CodeBundle\B04292_Learning_Dart_2_Chapter 3\code\unittest_v1\.
IO  : Finished ver. Exit code 0.
    | stdout:
    | |
    | | Microsoft Windows [Version 6.1.7601]
    | Nothing output on stderr.
MSG : Resolving dependencies...
SLVR: Solving dependencies:
    | - test any from hosted (test) (locked to 0.12.0)
    | - dartlero any from git (https://github.com/dzenanr/dartlero) (locked to 1.0.5)
SLVR: * start at root
SLVR: | dartlero 1.0.5 from git is locked
IO  : Spawning "cmd /c git --version" in I:\Downloads\LearningDart2ndEdition_CodeBundle_Latest\LearningDart2ndEdition_CodeBundle\B04292_Learning_Dart_2_Chapter 3\code\unittest_v1\.
IO  : Finished git. Exit code 0.
    | stdout:
    | | git version 2.5.3.windows.1
    | Nothing output on stderr.
FINE: Determined git command null.
IO  : Spawning "cmd /c git fetch" in C:\Users\Sean\AppData\Roaming\Pub\Cache\git\cache\dartlero
IO  : Finished git. Exit code 128.
    | Nothing output on stdout.
    | stderr:
    | | fatal: Not a git repository (or any of the parent directories): .git
SLVR: Could not get versions for dartlero from git:
    | Git error. Command: git fetch
    | fatal: Not a git repository (or any of the parent directories): .git
    |
    | package:pub/src/git.dart 56                          run.<fn>
    | ===== asynchronous gap ===========================
    | dart:async                                           _Future.then
    | package:pub/src/git.dart 55                          run
    | package:pub/src/source/git.dart 247                  GitSource._updateRepoCache
    | package:pub/src/source/git.dart 227                  GitSource._ensureRevision.<fn>
    | dart:async                                           Future.Future.sync
    | package:pub/src/source/git.dart 216                  GitSource._ensureRevision
    | package:pub/src/source/git.dart 150                  GitSource.resolveId
    | package:pub/src/source/cached.dart 33                CachedSource.doDescribe.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.Future.microtask
    | package:pub/src/source/cached.dart                   CachedSource.doDescribe
    | package:pub/src/source.dart 91                       Source.describe
    | package:pub/src/source.dart 74                       Source.getVersions.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.Future.microtask
    | package:pub/src/source.dart                          Source.getVersions
    | package:pub/src/solver/version_solver.dart 238       PubspecCache.getVersions.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.Future.microtask
    | package:pub/src/solver/version_solver.dart           PubspecCache.getVersions
    | package:pub/src/solver/backtracking_solver.dart 349  BacktrackingSolver._getAllowedVersions.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.Future.microtask
    | package:pub/src/solver/backtracking_solver.dart      BacktrackingSolver._getAllowedVersions
    | package:pub/src/solver/backtracking_solver.dart 337  BacktrackingSolver._versionQueueFor.<async>.<fn>
    | package:pub/src/solver/version_queue.dart 102        VersionQueue._calculateAllowed.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.Future.microtask
    | package:pub/src/solver/version_queue.dart            VersionQueue._calculateAllowed
    | package:pub/src/solver/version_queue.dart 64         VersionQueue.create.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.Future.microtask
    | package:pub/src/solver/version_queue.dart            VersionQueue.create
    | package:pub/src/solver/backtracking_solver.dart 336  BacktrackingSolver._versionQueueFor.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.Future.microtask
    | package:pub/src/solver/backtracking_solver.dart      BacktrackingSolver._versionQueueFor
    | package:pub/src/solver/backtracking_solver.dart 289  BacktrackingSolver._solve.<async>.<fn>.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.doWhile
    | package:pub/src/solver/backtracking_solver.dart 278  BacktrackingSolver._solve.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.doWhile
    | package:pub/src/solver/backtracking_solver.dart 278  BacktrackingSolver._solve.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.Future.microtask
    | package:pub/src/solver/backtracking_solver.dart      BacktrackingSolver._solve
    | package:pub/src/solver/backtracking_solver.dart 161  BacktrackingSolver.solve.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           _asyncThenWrapperHelper
    | package:pub/src/solver/backtracking_solver.dart      BacktrackingSolver.solve
    | package:pub/src/solver/version_solver.dart 40        resolveVersions.<fn>
    | package:pub/src/log.dart 393                         progress
    | package:pub/src/solver/version_solver.dart 38        resolveVersions
    | package:pub/src/entrypoint.dart 152                  Entrypoint.acquireDependencies.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.Future.microtask
    | package:pub/src/entrypoint.dart                      Entrypoint.acquireDependencies
    | package:pub/src/command/get.dart 30                  GetCommand.run
    | package:args/command_runner.dart 178                 CommandRunner.runCommand.<fn>
    | dart:async                                           Future.Future.sync
    | package:args/command_runner.dart 131                 CommandRunner.runCommand
    | package:pub/src/command_runner.dart 130              PubCommandRunner.runCommand.<async>.<fn>
    | dart:async                                           Future.Future.sync
    | package:pub/src/utils.dart 103                       captureErrors.<fn>
    | package:stack_trace                                  Chain.capture
    | package:pub/src/utils.dart 117                       captureErrors
    | package:pub/src/command_runner.dart 130              PubCommandRunner.runCommand.<async>
SLVR: BacktrackingSolver took 0:00:00.259015 seconds.
    | - Requested 1 version lists
    | - Looked up 0 cached version lists
    | - Requested 0 pubspecs
    | - Looked up 1 cached pubspecs
    |
FINE: Resolving dependencies finished (0.274s).
ERR : Git error. Command: git fetch
    | fatal: Not a git repository (or any of the parent directories): .git
FINE: Exception type: GitException
FINE: package:pub/src/solver/version_solver.dart 246       PubspecCache.getVersions.<async>
    | dart:async                                           _Completer.completeError
    | package:pub/src/source.dart 84                       Source.getVersions.<async>
    | dart:async                                           _Completer.completeError
    | package:pub/src/source/cached.dart 47                CachedSource.doDescribe.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           _Completer.completeError
    | package:pub/src/solver/version_solver.dart 268       PubspecCache.getVersions.<async>
    | dart:async                                           _Completer.completeError
    | package:pub/src/source.dart 84                       Source.getVersions.<async>
    | dart:async                                           _Completer.completeError
    | package:pub/src/source/cached.dart 47                CachedSource.doDescribe.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           _asyncErrorWrapperHelper
    | package:pub/src/solver/version_solver.dart           PubspecCache.getVersions
    | package:pub/src/solver/backtracking_solver.dart 349  BacktrackingSolver._getAllowedVersions.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.Future.microtask
    | package:pub/src/solver/backtracking_solver.dart      BacktrackingSolver._getAllowedVersions
    | package:pub/src/solver/backtracking_solver.dart 337  BacktrackingSolver._versionQueueFor.<async>.<fn>
    | package:pub/src/solver/version_queue.dart 102        VersionQueue._calculateAllowed.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.Future.microtask
    | package:pub/src/solver/version_queue.dart            VersionQueue._calculateAllowed
    | package:pub/src/solver/version_queue.dart 64         VersionQueue.create.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.Future.microtask
    | package:pub/src/solver/version_queue.dart            VersionQueue.create
    | package:pub/src/solver/backtracking_solver.dart 336  BacktrackingSolver._versionQueueFor.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.Future.microtask
    | package:pub/src/solver/backtracking_solver.dart      BacktrackingSolver._versionQueueFor
    | package:pub/src/solver/backtracking_solver.dart 289  BacktrackingSolver._solve.<async>.<fn>.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.doWhile
    | package:pub/src/solver/backtracking_solver.dart 278  BacktrackingSolver._solve.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.doWhile
    | package:pub/src/solver/backtracking_solver.dart 278  BacktrackingSolver._solve.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.Future.microtask
    | package:pub/src/solver/backtracking_solver.dart      BacktrackingSolver._solve
    | package:pub/src/solver/backtracking_solver.dart 161  BacktrackingSolver.solve.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           _asyncThenWrapperHelper
    | package:pub/src/solver/backtracking_solver.dart      BacktrackingSolver.solve
    | package:pub/src/solver/version_solver.dart 40        resolveVersions.<fn>
    | package:pub/src/log.dart 393                         progress
    | package:pub/src/solver/version_solver.dart 38        resolveVersions
    | package:pub/src/entrypoint.dart 152                  Entrypoint.acquireDependencies.<async>
    | ===== asynchronous gap ===========================
    | dart:async                                           Future.Future.microtask
    | package:pub/src/entrypoint.dart                      Entrypoint.acquireDependencies
    | package:pub/src/command/get.dart 30                  GetCommand.run
    | package:args/command_runner.dart 178                 CommandRunner.runCommand.<fn>
    | dart:async                                           Future.Future.sync
    | package:args/command_runner.dart 131                 CommandRunner.runCommand
    | package:pub/src/command_runner.dart 130              PubCommandRunner.runCommand.<async>.<fn>
    | dart:async                                           Future.Future.sync
    | package:pub/src/utils.dart 103                       captureErrors.<fn>
    | package:stack_trace                                  Chain.capture
    | package:pub/src/utils.dart 117                       captureErrors
    | package:pub/src/command_runner.dart 130              PubCommandRunner.runCommand.<async>```

**Comment by nex3** [comment] 2016-01-06 23:47
The underlying issue is definitely something to do with Windows Git, or maybe your network somehow.

For pub's part, it looks like your cache is corrupted—it has a directory for your package, but that directory isn't a valid Git repository (probably because of the underlying issue). Ideally pub would never be able to corrupt your cache, but it's hard to know *a priori* how Git might fail and be ready to handle every eventuality. If I can get a reproduction for creating a broken cache entry, I'll look into that, but for now I'm going to close this issue.

Once you get Git working on its own again, run `pub cache repair` and then you should be good to go.

**Closed by nex3** 2016-01-06 23:47 UTC
Labels: bug, needs info

**Comment by sgerhardt** [comment] 2016-01-07 00:00
@nex3 I've run this on several different networks and still got the same failure. Therefore I'd be very surprised if this issue was related to the network. I've repaired the cache, and ensured that was not causing the issue as well. 

All signs point to git for windows. Looks like I'll have to bring the issue up with them.

**Comment by AkposCodex** [comment] 2019-08-08 12:04
Hey I'm a newbie to git, how exactly do append the .git to the dependencies I can't even seem to be able to find them.

**Comment by jonasfj** [comment] 2019-08-08 13:24
@AkposCodex, this looks it's complaining about SDK constraints, see:
https://dart.dev/tools/pub/pubspec#sdk-constraints

Maybe add:
```yaml
environment:
  sdk: '>=2.0.0 <3.0.0'
```


Side note: to add code snippets see: https://help.github.com/en/articles/creating-and-highlighting-code-blocks

**Comment by AkposCodex** [comment] 2019-08-08 14:31
thanks, but now I have another problem I'm getting an error saying that:
```
package:flutter_web/material.dart

```
does not exist, amongst 25 other problems related to the flutter packages
![Screenshot (30)](https://user-images.githubusercontent.com/38590783/62711794-920b9400-b9f1-11e9-8fb6-be5f20a91841.png)

**Comment by jonasfj** [comment] 2019-08-08 14:50
You're probably better off asking for help on gitter.im or going through
some tutorials.
Clearly you need some dependencies like:
```dart

dependencies:
  flutter:
    sdk: flutter

```

I'm no flutter expert.. I suggest starting from a working sample:
https://github.com/flutter/samples/blob/master/INDEX.md
