### ISSUE TITLE
Pub globaly installed packages run twice on windows

### ISSUE THREAD

**Issue by pavlov-o-a** [dart-lang/pub#3262] opened 2021-12-21 11:40 UTC
When package is installed globally on windows it runs commands twice no matter what.
Probably an issue with bat file generated by pub.
I have this issue using dart 2.14.4 (stable) and [melos package](https://pub.dev/packages/melos) installed globally.
Example is below and also a question related to the issue is raised on [stackoverflow (link)](https://stackoverflow.com/questions/69098958/dart-pub-global-packages-run-twice-on-windows-10).
```
PS C:\Users\Karbit\flutterProjects\app> dart --version
Dart SDK version: 2.14.4 (stable) (Wed Oct 13 11:11:32 2021 +0200) on "windows_x64"
PS C:\Users\Karbit\flutterProjects\app> melos
A CLI tool for managing Dart & Flutter projects with multiple packages.

Usage: melos <command> [arguments]

Global options:
-h, --help       Print this usage information.
    --verbose    Enable verbose logging.
-v, --version    Print the current Melos version.

Available commands:
  bootstrap   Initialize the workspace, link local packages together and install remaining package dependencies. Supports all package
              filtering options.
  clean       Clean this workspace and all packages. This deletes the temporary pub & ide files such as ".packages" &
              ".flutter-plugins". Supports all package filtering options.
  exec        Execute an arbitrary command in each package. Supports all package filtering options.
  list        List local packages in various output formats. Supports all package filtering options.
  publish     Publish any unpublished packages or package versions in your repository to pub.dev. Dry run is on by default.
  run         Run a script by name defined in the workspace melos.yaml config file.
  version     Automatically version and generate changelogs based on the Conventional Commits specification. Supports all package
              filtering options.

Run "melos help <command>" for more information about a command.
A CLI tool for managing Dart & Flutter projects with multiple packages.

Usage: melos <command> [arguments]

Global options:
-h, --help       Print this usage information.
    --verbose    Enable verbose logging.
-v, --version    Print the current Melos version.

Available commands:
  bootstrap   Initialize the workspace, link local packages together and install remaining package dependencies. Supports all package
              filtering options.
  clean       Clean this workspace and all packages. This deletes the temporary pub & ide files such as ".packages" &
              ".flutter-plugins". Supports all package filtering options.
  exec        Execute an arbitrary command in each package. Supports all package filtering options.
  list        List local packages in various output formats. Supports all package filtering options.
  publish     Publish any unpublished packages or package versions in your repository to pub.dev. Dry run is on by default.
  run         Run a script by name defined in the workspace melos.yaml config file.
  version     Automatically version and generate changelogs based on the Conventional Commits specification. Supports all package
              filtering options.

Run "melos help <command>" for more information about a command.
PS C:\Users\Karbit\flutterProjects\app> melos -v
1.0.0
1.0.0
PS C:\Users\Karbit\flutterProjects\app>
```

**Comment by sigurdm** [comment] 2022-01-03 14:49
I believe this is a duplicate of: https://github.com/dart-lang/pub/issues/2934 that has been fixed in https://github.com/dart-lang/pub/pull/3055. Try upgrading to dart 2.15.

Closing as duplicate.

**Closed by sigurdm** 2022-01-03 14:49 UTC
