### ISSUE TITLE
fix(login): type 'String' is not a subtype of type 'Uri'

### ISSUE THREAD

**Issue by jjangga0214** [dart-lang/pub#3083] opened 2021-08-23 08:37 UTC
# Environment

- `pub version` or `flutter pub version`:
`Dart SDK version: 2.13.4 (stable) (Wed Jun 23 13:08:41 2021 +0200) on "linux_x64"`
- OS version: Ubuntu 20.04
- Are you using the Chinese community mirror or a corporate firewall?: No.

# Problem

When I `dart pub login`, an error occurs.

## Expected behavior

It should just work.

## Actual behavior

```shell
➜  ~ (☸ |k3d-ateam:local) dart pub login 
Pub needs your authorization to upload packages on your behalf.
In a web browser, go to https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&response_type=code&client_id=818368855108-8grd2eg9tj9f38os6f1urbcvsq399u8n.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A45885&code_challenge=lHTkJS_rZXv2MfN2gAbNNm6YKdPvBfQsGh9cTOvA57E&code_challenge_method=S256&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email
Then click "Allow access".
```

So I manually visited the website link above. 
After I logged in, the following message is printed on terminal.

```shell
Waiting for your authorization...
Authorization received, processing...
Successfully authorized.
type 'String' is not a subtype of type 'Uri'
package:pub/src/command/login.dart 46:48  LoginCommand.retrieveUserInfo.<fn>
===== asynchronous gap ===========================
package:pub/src/command/login.dart 42:12  LoginCommand.retrieveUserInfo
===== asynchronous gap ===========================
package:pub/src/command/login.dart 28:24  LoginCommand.runProtected
This is an unexpected error. Please run

    dart pub --trace pub login

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
```

**Comment by sigurdm** [comment] 2021-08-24 10:46
duplicate of: https://github.com/dart-lang/pub/issues/3064

This is fixed on the dart dev branch See workaround in the linked issue.

**Closed by sigurdm** 2021-08-24 10:46 UTC
