### ISSUE TITLE
pub makes bogus suggestion about how to depend on package:flutter

### ISSUE THREAD

**Issue by nex3** [dart-lang/pub#1467] opened 2016-11-07 23:42 UTC
_From @abarth on November 7, 2016 23:34_

```
Suggestions:
* Don't depend on "flutter" from the sdk source. Use the hosted source instead. For example:
  
  dependencies:
    flutter: ^0.0.20
  
  Using the hosted source ensures that everyone can download your package's dependencies along with your package.
Sorry, your package is missing some requirements and can't be published yet.
For more information, see: http://pub.dartlang.org/doc/pub-lish.html.
```

_Copied from original issue: dart-lang/sdk#27782_

**Comment by nex3** [comment] 2016-11-07 23:42
_From @abarth on November 7, 2016 23:34_

The proper way to depend on `package:flutter` is from an SDK source.

**Comment by nex3** [comment] 2016-11-07 23:42
_From @abarth on November 7, 2016 23:35_

@nex3 @munificent

**Comment by abarth** [comment] 2017-05-04 18:42
I hit this again today.  It would be nice to remove this warning so that people publishing packages that depend on flutter don't get confused.

**Comment by munificent** [comment] 2017-05-04 20:46
This is still an issue? I thought it was resolved with #1560. Are you using an older version of pub?

**Comment by abarth** [comment] 2017-05-04 20:53
I'm using Pub 1.23.0-dev.11.11.

**Comment by abarth** [comment] 2017-05-04 20:53
It's a dupe of that issue.

**Comment by abarth** [comment] 2017-05-04 20:54
I'm not sure how to tell if 69be47ed84c3ced304047aaa885c8f8f48dad4e6 is in that pub version.

**Comment by munificent** [comment] 2017-05-10 17:36
I don't believe it is. I brought that pub fix into the Dart repo in https://github.com/dart-lang/sdk/commit/8abc899c0a63d8ec2ae3b4f947e9d9dada190cf7. That commit is tagged 1.24-dev.0.0, so I don't think it will be in any of the 1.23.0 releases.

**Comment by abarth** [comment] 2017-05-10 17:36
Thanks!

**Closed by abarth** 2017-05-10 17:36 UTC
