### ISSUE TITLE
pub fails to grab package 'convert' at 2.0.1

### ISSUE THREAD

**Issue by zanderso** [dart-lang/pub#1784] opened 2018-01-18 21:31 UTC
```
zra@zach:~/dart/pub_bug$ cat pubspec.yaml 
name: importer
dependencies:
  convert: 2.0.1
zra@zach:~/dart/pub_bug$ pub get
Resolving dependencies... 
Package convert has no versions that match 2.0.1 derived from:
- importer depends on version 2.0.1
zra@zach:~/dart/pub_bug$ pub --version
Pub 2.0.0-dev.18.0
```

but 2.0.1 exists: https://pub.dartlang.org/packages/convert#-versions-tab-

**Comment by nex3** [comment] 2018-01-18 22:19
Duplicate of #1781.

**Closed by nex3** 2018-01-18 22:19 UTC
