### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by 825i** [dart-lang/pub#3490] opened 2022-07-12 12:50 UTC
When trying to install flutter on VScode I got this. Using an M1 Macbook Pro.

```
[flutter/.pub-cache/git/scoped_model-cc39449cdea9364f574713009ef6d2c40a7d35a7] flutter pub get
Running "flutter pub get" in scoped_model-cc39449cdea9364f574713009ef6d2c40a7d35a7...     
Null check operator used on a null value
package:pub/src/entrypoint.dart 157:60                 Entrypoint.lockFilePath
package:pub/src/entrypoint.dart 100:21                 Entrypoint._loadLockFile
package:pub/src/entrypoint.dart 97:42                  Entrypoint.lockFile
package:pub/src/entrypoint.dart 286:21                 Entrypoint.acquireDependencies.<fn>
package:pub/src/entrypoint.dart 280:68                 Entrypoint.acquireDependencies.<fn>
package:pub/src/log.dart 428:18                        progress
package:pub/src/entrypoint.dart 280:26                 Entrypoint.acquireDependencies
package:pub/src/command/get.dart 52:22                 GetCommand.runProtected
package:pub/src/command.dart 183:45                    PubCommand.run.<fn>
package:pub/src/command.dart 183:33                    PubCommand.run.<fn>
dart:async                                             new Future.sync
package:pub/src/utils.dart 109:12                      captureErrors.wrappedCallback
dart:async                                             runZonedGuarded
package:pub/src/utils.dart 126:5                       captureErrors
package:pub/src/command.dart 183:13                    PubCommand.run
package:args/command_runner.dart 209:27                CommandRunner.runCommand
package:pub/src/command_runner.dart 174:24             PubCommandRunner.runCommand
package:pub/src/command_runner.dart 159:20             PubCommandRunner.run
package:dartdev/dartdev.dart 45:56                     runDartdev
/opt/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart 11:9  main
This is an unexpected error. The full log and other details are collected in:

    /Users/adminuser/flutter/.pub-cache/log/pub_log.txt

Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.
.
pub get failed (255; .)
exit code 255
```

I have checked the path: /Users/adminuser/flutter/.pub-cache/log/pub_log.txt

But there actually is no log there at all.

**Comment by sigurdm** [comment] 2022-11-03 10:22
This probably happens when you run `dart pub get` inside the pub cache.

I believe this is a duplicate of https://github.com/dart-lang/pub/issues/3463 that has been fixed.

**Closed by sigurdm** 2022-11-03 10:22 UTC
Labels: bug
