### ISSUE TITLE
`pub global activate <package_name>` does not generate script in $PUB_CACHE/bin

### ISSUE THREAD

**Issue by dum3ng** [dart-lang/pub#2296] opened 2020-01-04 03:44 UTC
# Environment

- `pub version`: Pub 2.7.0
- OS version: elementary OS 5.1 Hera
- Are you using the Chinese community mirror or a corporate firewall?
 yes, using PUB_HOSTED_URL="https://mirrors.tuna.tsinghua.edu.cn/dart-pub/"

# Problem

```bash
pub global activate stagehand
```
I have `$PUB_CACHE/bin` in `PATH` environment variable.
## Expected behavior

A exectuble script exists in $PUB_CACHE/bin, and I can run `stagehand` directly in terminal.

## Actual behavior

The folder `$PUB_CACHE/bin` is empty, and I can only run `pub global run stagehand`

## --trace output

```
Resolving dependencies... (13.3s)
+ args 1.5.2
+ async 2.4.0
+ charcode 1.1.2
+ collection 1.14.12
+ http 0.12.0+3
+ http_parser 3.1.3
+ meta 1.1.8
+ path 1.6.4
+ pedantic 1.9.0
+ source_span 1.5.5
+ stagehand 3.3.5
+ string_scanner 1.0.5
+ term_glyph 1.1.0
+ typed_data 1.1.6
+ usage 3.4.1
Precompiling executables... 
Precompiled stagehand:stagehand.
Activated stagehand 3.3.5.

```

**Comment by quiet9929** [comment] 2020-01-06 10:00
Disable PUB_HOSTED_URL mirroring address, and then try again, I also encountered such a problem, it may be a mirroring problem

**Comment by dum3ng** [comment] 2020-01-06 12:14
> Disable PUB_HOSTED_URL mirroring address, and then try again, I also encountered such a problem, it may be a mirroring problem

Yes, this did resolve the issue. Thanks!

**Comment by jonasfj** [comment] 2020-01-06 12:31
If `pub global activate <package>` doesn't work with `PUB_HOSTED_URL` then maybe that's a bug worth fixing.

**Comment by dum3ng** [comment] 2020-03-24 06:25
Hope this issue can be solved.
When I use the mirror site, I can use `pub get` to download packages, but can not activate package globally;
When I do not use the mirror site, the packages just can not be downloaded because I  am in China.

And when I use a vpn, another issue emerged: [HttpClient crashes when using lantern VPN on Ubuntu.](https://github.com/dart-lang/sdk/issues/37808)

**Comment by medz** [comment] 2020-05-19 05:04
@dum3ng I have the same problem😣

**Comment by sigurdm** [comment] 2023-01-17 15:27
I am not able to reproduce :
```
> rm ~/.pub-cache/bin/stagehand
em: cannot remove '~/.pub-cache/bin/stagehand': No such file or directory
> ~/.dvm/darts/2.19.0-81.0.dev/bin/dart pub global activate stagehand
+ args 2.3.1
+ async 2.10.0
+ collection 1.17.0
+ http 0.13.5
+ http_parser 4.0.2
+ meta 1.8.0
+ path 1.8.3
+ pedantic 1.11.1
+ source_span 1.9.1
+ stagehand 4.0.1
+ string_scanner 1.2.0
+ term_glyph 1.2.1
+ typed_data 1.3.1
+ usage 4.1.0
Building package executables... (1.4s)
Built stagehand:stagehand.
Installed executable stagehand.
Activated stagehand 4.0.1.
> ls ~/.pub-cache/bin/stagehand
stagehand
```

**Comment by sigurdm** [comment] 2023-01-26 09:57
Closing, assuming fixed.

**Closed by sigurdm** 2023-01-26 09:57 UTC
Labels: bug, needs info
