### ISSUE TITLE
flutter packages get fails when pigz is installed

### ISSUE THREAD

**Issue by porn** [dart-lang/pub#2126] opened 2019-05-02 14:13 UTC
Hi,

just discovered and "hotfixed" a bug. I'm running Ubuntu 18.04 and couldn't get through installation of a package in the [step 2 of the tutorial](https://flutter.dev/docs/get-started/codelab#step-2-use-an-external-package).

After adding `english_words: ^3.1.0` to my `pubspec.yaml` the following commmand failed:
```
$ flutter packages get
gzip: warning: <stdin>: trailing junk was ignored                       
gzip: warning: <stdin>: trailing junk was ignored                       
tar: Child returned status 1                                            
tar: Error is not recoverable: exiting now                              
tar: Child returned status 1                                            
tar: Error is not recoverable: exiting now                              
gzip: warning: <stdin>: trailing junk was ignored                       
tar: Child returned status 1                                            
tar: Error is not recoverable: exiting now                              
gzip: warning: <stdin>: trailing junk was ignored                       
tar: Child returned status 1                                            
tar: Error is not recoverable: exiting now                              
gzip: warning: <stdin>: trailing junk was ignored                       
tar: Child returned status 1                                            
tar: Error is not recoverable: exiting now                              
Failed to extract .tar.gz stream to /home/ubuntu/Android/flutter_sdk/flutter/.pub-cache/_temp/dirVNBFVY (exit code 2).
package:pub/src/io.dart 874:5               extractTarGz                
===== asynchronous gap ===========================                      
package:pub/src/source/hosted.dart 302:11   BoundHostedSource._download 
===== asynchronous gap ===========================                      
package:pub/src/source/hosted.dart 196:13   BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================                      
package:pub/src/entrypoint.dart 371:48      Entrypoint._get.<fn>        
===== asynchronous gap ===========================                      
package:pub/src/http.dart 271:51            withDependencyType          
package:pub/src/entrypoint.dart 367:12      Entrypoint._get             
dart:async                                  Future.wait                 
package:pub/src/entrypoint.dart 228:18      Entrypoint.acquireDependencies
dart:async                                  _completeOnAsyncReturn      
package:pub/src/solver/version_solver.dart  VersionSolver.solve         
dart:async                                  _completeOnAsyncReturn      
package:pub/src/solver/version_solver.dart  VersionSolver._result       
This is an unexpected error. Please run                                 
                                                                        
    pub --trace --verbosity=warning get --no-precompile                 
                                                                        
and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Running "flutter packages get" in flutter_app...                        
pub get failed (1)
```

It took me a while to discover that the problem is in my machine setup. Some time ago I installed [pigz](https://zlib.net/pigz/) which cannot unzip streams. Removing the `pigz` package "solved" the issue. Though I'd love to use pigz system-wide.

Not sure if you're able to detect, but if so any meaningful message would save me about an hour of useless googling...

Cheers!

OT: flutter looks great, thanks for all the work you've done here so far!

**Comment by jonasfj** [comment] 2019-05-02 15:03
`dart:io` already comes with a gzip implementation, we should simply use that and write a proper tar implementation in dart...

I'm going to close this as a duplicate of #1602.

**Closed by jonasfj** 2019-05-02 15:03 UTC
Labels: bug, help wanted

**Comment by porn** [comment] 2019-05-03 06:14
Thanks for the reaction!

Btw. my feeling is that pigz package came into the system "silently" with docker (docker recommends it). I'm quite surprised I couldn't find anyone running into the same issues...

**Comment by sigurdm** [comment] 2020-01-14 11:40
I just tried with pigz installed via homebrew, and could not reproduce.

How did you install pigz?

**Comment by porn** [comment] 2020-01-14 12:10
> I just tried with pigz installed via homebrew, and could not reproduce.
> 
> How did you install pigz?

I'm on Ubuntu 18.04. Not sure how I installed pigz, my guess is that pigz package came into the system "silently" with docker (docker recommends it).

Maybe just Ubuntu thing, this is how gzip is aliased to pigz in order to make all `gzip` operations use parallelism:
```
$ ls -l `which gzip`
lrwxrwxrwx 1 root root 13 kvě 11  2018 /usr/local/bin/gzip -> /usr/bin/pigz
```

This should probably be fixed by pigz team, but since this was my "into error" to flutter it would be plus for flutter to catch the error and display something meaningful for the user.

**Comment by jonasfj** [comment] 2020-01-16 15:15
Not sure what image you're running.. this seems to not be the case on the default `ubuntu:18.04` image..

It's also rare that distros install anything into `/usr/local/bin/gzip`, that's more likely to be something done by something else you've installed or done.

I think #2186 is still prudent..
