### ISSUE TITLE
Support a nested package structure with git dependencies

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/pub#1627] opened 2017-05-26 17:41 UTC
For example, with the [build package](https://github.com/dart-lang/build):

```yaml
dependencies:
  build_runner:
    git: 
      url: https://github.com/dart-lang/build
      path: build_runner
```

**Comment by nex3** [comment] 2017-05-26 22:44
Duplicate of #1305.

**Closed by nex3** 2017-05-26 22:44 UTC
