### ISSUE TITLE
Launching the Flutter project

### ISSUE THREAD

**Issue by UP006** [dart-lang/pub#4327] opened 2024-07-17 16:56 UTC
Problem Description:
I encountered an error while running flutter pub get in my Flutter project. The error message indicates a Null check operator used on a null value. This occurs in the hosted.dart file at line 760:33.

Error Message:
Resolving dependencies...
Downloading packages...
Null check operator used on a null value
package:pub/src/source/hosted.dart 760:33
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 778:12 HostedSource._getAdvisories
package:pub/src/source/hosted.dart 1066:24 HostedSource.getAdvisoriesForPackageVersion
package:pub/src/solver/report.dart 414:26 SolveReport._reportPackage
package:pub/src/solver/report.dart 218:18 SolveReport._reportChanges
package:pub/src/solver/report.dart 73:21 SolveReport.show
package:pub/src/entrypoint.dart 568:5 Entrypoint.acquireDependencies
package:pub/src/command/get.dart 77:5 GetCommand.runProtected
package:pub/src/command.dart 196:7 PubCommand.run
package:args/command_runner.dart 212:13 CommandRunner.runCommand
package:dartdev/dartdev.dart 232:18 DartdevRunner.runCommand
package:dartdev/dartdev.dart 46:16 runDartdev
C:\b\s\w\ir\xw\sdk\pkg\dartdev\bin\dartdev.dart 13:5 main

This is an unexpected error. The full log and other details are collected in:
    C:\Users\UP006\AppData\Local\Pub\log\pub_log.txt

Steps to Reproduce
Open the terminal in the project directory.
Run flutter pub get.
Environment
Pub version: 3.4.3

Flutter version: Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (6 weeks ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3

Dart version: Dart SDK version: 3.4.3 (stable) (Tue Jun 4 19:51:39 2024 +0000) on "windows_x64"
Operating system: Windows 10 pro

Additional Information:
name: home_services
description: home_services customer app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0+32
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # GET
  get: ^4.6.6
  get_storage: 2.1.1
  # DIO
  dio: ^4.0.0
  dio_http_cache: 0.3.0
  # FONT
  google_fonts: ^4.0.4
  #IMAGES, SLIDERS, LAYOUTS
  cached_network_image: ^3.3.1
  carousel_slider: 4.2.1
  flutter_svg: ^2.0.9
  flutter_staggered_grid_view: ^0.7.0
  image_picker: ^1.1.2
  cupertino_icons: any
  shimmer: ^3.0.0
  intl_phone_field: ^3.2.0
  flutter_slidable: ^3.1.1
  # WEB
  webview_flutter: ^4.8.0
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.3.0
  # FIREBASE
  firebase_messaging: ^15.0.3
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  # GOOGLE MAPS
  google_maps_flutter: ^2.7.0
  google_maps_flutter_web: ^0.5.8
  map_launcher: ^3.3.1
  google_maps_place_picker_mb:
    git:
      url: https://github.com/SmarterVision/google_maps_place_picker_mb.git
      ref: 2.0.0-mb.22
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.18.0

  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - config/
    - assets/img/
    - assets/icon/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

[pub_log.txt](https://github.com/user-attachments/files/16270677/pub_log.txt)

**Comment by sigurdm** [comment] 2024-07-29 11:16
Duplicate of https://github.com/dart-lang/pub/issues/4269

This is fixed in 3.4.4 https://github.com/dart-lang/sdk/blob/stable/CHANGELOG.md#344---2024-06-12

**Closed by sigurdm** 2024-07-29 11:16 UTC
