### ISSUE TITLE
Could not find a file named "pubspec.yaml" in "C:\flutter\bin\cache\dart-sdk\bin"

### ISSUE THREAD

**Issue by vopee** [dart-lang/pub#2076] opened 2019-02-26 08:37 UTC
Could not find a file named "pubspec.yaml" in "C:\flutter\bin\cache\dart-sdk\bin"

**Comment by zoechi** [comment] 2019-02-26 10:20
Possible duplicate of https://github.com/flutter/flutter/issues/28498

**Comment by chenglu** [comment] 2019-02-26 14:45
It has been fixed, see my comments on [#28498](https://github.com/flutter/flutter/issues/28498#issuecomment-467462967) for more information.

**Comment by jonasfj** [comment] 2019-03-04 20:07
Please reopen if this is still a problem...

Maybe include a stack trace, verbose logging or some information on what you're trying to do :)

**Closed by jonasfj** 2019-03-04 20:07 UTC
