### ISSUE TITLE
Cannot parse URI after updating dart version to 2.17.0-266.1.beta 

### ISSUE THREAD

**Issue by edhom** [dart-lang/pub#3390] opened 2022-04-14 10:13 UTC
After updating the dart sdk version, a url dependency including an @ cannot be parsed anymore.

```
Illegal scheme character (at character 4)
git@github.com:simpleclub-extended/flutter_math_fork.git
   ^
dart:core                                  Uri.parse
package:path/src/context.dart 1077:33      _parseUri
package:path/src/context.dart 1052:22      Context.prettyUri
package:path/path.dart 461:34              prettyUri
package:pub/src/source/git.dart 730:23     GitResolvedDescription.format
package:pub/src/solver/report.dart 326:40  SolveReport._writeId
package:pub/src/solver/report.dart 302:5   SolveReport._reportPackage
===== asynchronous gap ===========================
package:pub/src/solver/report.dart 138:9   SolveReport._reportOverrides
===== asynchronous gap ===========================
package:pub/src/solver/report.dart 48:5    SolveReport.show
===== asynchronous gap ===========================
package:pub/src/solver/result.dart 112:5   SolveResult.showReport
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 321:7      Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 52:5      GetCommand.runProtected
This is an unexpected error. The full log and other details are collected in:

    /Library/flutter/.pub-cache/log/pub_log.txt
```

**Comment by edhom** [comment] 2022-04-14 10:42
Seems like it only happens in `dependency_overrides` tho🤔

**Comment by sigurdm** [comment] 2022-04-21 13:05
I believe this is a duplicate of https://github.com/dart-lang/pub/issues/3377 fixed in https://github.com/dart-lang/pub/pull/3381

**Closed by sigurdm** 2022-04-21 13:05 UTC
