### ISSUE TITLE
Error on installing get_it dependency! (injectable)

### ISSUE THREAD

**Issue by Mahdi1270** [dart-lang/pub#3681] opened 2022-12-03 17:21 UTC
I did not know where to publish this but anyway ...
I was trying to install [injectable](https://pub.dev/packages/injectable) dependency and I faced this error!
Can anyone help?

flutter pub add get_it
Resolving dependencies...
  async 2.9.0 (2.10.0 available)
  boolean_selector 2.1.0 (2.1.1 available)
  collection 1.16.0 (1.17.0 available)
  ffi 1.2.1 (2.0.1 available)
+ get_it 7.2.0
+ injectable 2.1.0
  js 0.6.4 (0.6.5 available)
  matcher 0.12.12 (0.12.13 available)
  material_color_utilities 0.1.5 (0.2.0 available)
  path_provider_linux 0.0.1+2 (2.1.7 available)
  path_provider_platform_interface 1.0.4 (2.0.5 available)
  path_provider_windows 0.0.5 (2.1.3 available)
  plugin_platform_interface 1.0.3 (2.1.3 available)
  shared_preferences 0.5.12+4 (2.0.15 available)
  shared_preferences_linux 0.0.2+4 (2.1.1 available)
  shared_preferences_macos 0.0.1+11 (2.0.4 available)
  shared_preferences_platform_interface 1.0.4 (2.1.0 available)
  shared_preferences_web 0.1.2+7 (2.0.4 available)
  shared_preferences_windows 0.0.2+3 (2.1.1 available)
  source_span 1.9.0 (1.9.1 available)
  stack_trace 1.10.0 (1.11.0 available)
  stream_channel 2.1.0 (2.1.1 available)
  string_scanner 1.1.1 (1.2.0 available)
  test_api 0.4.12 (0.4.16 available)
  vector_math 2.1.2 (2.1.4 available)
  win32 2.6.1 (3.1.2 available)
  xdg_directories 0.1.2 (0.2.0+2 available)
Downloading injectable 2.1.0...
Authentication error (403)
package:pub/src/authentication/client.dart 95:5    _AuthenticatedClient._throwAuthException
package:pub/src/authentication/client.dart 60:9    _AuthenticatedClient.send
===== asynchronous gap ===========================
package:pub/src/authentication/client.dart 133:12  withAuthenticatedClient
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 862:22          HostedSource._download.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 886:12                     withTempDir
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 859:5           HostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 669:7           HostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/solver/result.dart 86:9            SolveResult.downloadCachedPackages.<fn>.<fn>
===== asynchronous gap ===========================
package:pub/src/solver/result.dart 85:14           SolveResult.downloadCachedPackages.<fn>
===== asynchronous gap ===========================
package:pub/src/solver/result.dart 82:5            SolveResult.downloadCachedPackages
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 332:7              Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/add.dart 182:7             AddCommand.runProtected
This is an unexpected error. The full log and other details are collected in:

    C:\Program Files\Flutter\.pub-cache\log\pub_log.txt

Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.
pub finished with exit code 1

**Comment by sigurdm** [comment] 2023-01-05 09:57
Are you in a location with restricted internet access?

Consider trying the chinese community mirror: https://docs.flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site

**Comment by sigurdm** [comment] 2023-01-05 10:03
Closing as duplicate of https://github.com/dart-lang/pub/issues/3256

**Closed by sigurdm** 2023-01-05 10:03 UTC
