### ISSUE TITLE
Error white gen files

### ISSUE THREAD

**Issue by ChaserVasya** [dart-lang/pub#3996] opened 2023-08-23 17:26 UTC
When I run 
fvm flutter pub run build_runner build -d
next error is printed

[pub_log.txt](https://github.com/dart-lang/pub/files/12421773/pub_log.txt)

**Comment by sigurdm** [comment] 2023-08-29 14:22
I believe this is a duplicate of https://github.com/dart-lang/pub/issues/3314

**Closed by sigurdm** 2023-08-29 14:22 UTC
