### ISSUE TITLE
Feature: enable running a non-dart script from a package

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub#1313] opened 2015-08-12 00:39 UTC
We've run into two cases where a package contains a python script meant to be run by a consumer of that package.

pub run, normally used to run bin scripts provided by package dependencies, can find and run Dart scripts from a package's bin/ directory.

However, to be best of our knowledge, there isn't a formal and supported way to run a non-Dart script provided by a package's bin/ or tool/ directory. We could be wrong about this, though.

The workaround we've used thus far is to put that script into the lib/ directory, and run it like: `python packages/foo/script.py`

However, when the packages/ dir goes away, that workaround disappears. :)

Anything that pub can do to help connect a user to arbitrary scripts provided by a package, would be greatly appreciated.

**Comment by nex3** [comment] 2015-08-12 01:21
Duplicate of #1266.

**Closed by nex3** 2015-08-12 01:21 UTC
Labels: enhancement
