### ISSUE TITLE
Looking for remote tunnel error

### ISSUE THREAD

**Issue by dajharia** [dart-lang/pub#4447] opened 2024-11-29 02:59 UTC
MY VSCODE couldn't worked due to this issue, 
Information about the latest pub run.

If you believe something is not working right, you can go to
https://github.com/dart-lang/pub/issues/new to post a new issue and attach this file.

Before making this file public, make sure to remove any sensitive information!

Pub version: 3.5.4
Created: 2024-11-29T08:21:07.186545
FLUTTER_ROOT: C:\src\flutter
PUB_HOSTED_URL: <not set>
PUB_CACHE: "<not set>"
Command: dart pub --suppress-analytics get --no-example --directory '.'
Platform: windows

---- C:\dev\testapp\pubspec.yaml ----
name: vedicapp
description: "एक वैदिक उपासना एप"
version: 1.0.0+1
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  scroll_to_index: ^3.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # कस्टम फॉण्ट्स को ऐड करें
  fonts:
    - family: Sanskrit
      fonts:
        - asset: assets/fonts/Sanskrit.otf
    - family: Siddhanta
      fonts:
        - asset: assets/fonts/Siddhanta.ttf

  # Assets
  assets:
    - 'assets/icons/home_icon.svg'
    - 'assets/icons/page1.svg'
    - 'assets/icons/page2.svg'
    - 'assets/icons/page3.svg'
    - 'assets/images/square_image.png'
    - 'assets/images/pic1.webp'
    - 'assets/images/pic2.webp'
    - 'assets/images/achman.webp'
    - 'assets/images/aghmarshan.webp'
    - 'assets/images/gayatri.webp'
    - 'assets/images/manasa.webp'
    - 'assets/images/namaskar.webp'    
    
    
flutter_icons:
  android: true
  image_path: "assets/images/splash.webp"  

---- End pubspec.yaml ----
---- C:\dev\testapp\pubspec.lock ----
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  archive:
    dependency: transitive
    description:
      name: archive
      sha256: cb6a278ef2dbb298455e1a713bda08524a175630ec643a242c399c932a0a1f7d
      url: "https://pub.dev"
    source: hosted
    version: "3.6.1"
  args:
    dependency: transitive
    description:
      name: args
      sha256: bf9f5caeea8d8fe6721a9c358dd8a5c1947b27f1cfaa18b39c301273594919e6
      url: "https://pub.dev"
    source: hosted
    version: "2.6.0"
  async:
    dependency: transitive
    description:
      name: async
      sha256: d2872f9c19731c2e5f10444b14686eb7cc85c76274bd6c16e1816bff9a3bab63
      url: "https://pub.dev"
    source: hosted
    version: "2.12.0"
  characters:
    dependency: transitive
    description:
      name: characters
      sha256: "04a925763edad70e8443c99234dc3328f442e811f1d8fd1a72f1c8ad0f69a605"
      url: "https://pub.dev"
    source: hosted
    version: "1.3.0"
  checked_yaml:
    dependency: transitive
    description:
      name: checked_yaml
      sha256: feb6bed21949061731a7a75fc5d2aa727cf160b91af9a3e464c5e3a32e28b5ff
      url: "https://pub.dev"
    source: hosted
    version: "2.0.3"
  cli_util:
    dependency: transitive
    description:
      name: cli_util
      sha256: ff6785f7e9e3c38ac98b2fb035701789de90154024a75b6cb926445e83197d1c
      url: "https://pub.dev"
    source: hosted
    version: "0.4.2"
  collection:
    dependency: transitive
    description:
      name: collection
      sha256: ee67cb0715911d28db6bf4af1026078bd6f0128b07a5f66fb2ed94ec6783c09a
      url: "https://pub.dev"
    source: hosted
    version: "1.18.0"
  crypto:
    dependency: transitive
    description:
      name: crypto
      sha256: "1e445881f28f22d6140f181e07737b22f1e099a5e1ff94b0af2f9e4a463f4855"
      url: "https://pub.dev"
    source: hosted
    version: "3.0.6"
  cupertino_icons:
    dependency: "direct main"
    description:
      name: cupertino_icons
      sha256: ba631d1c7f7bef6b729a622b7b752645a2d076dba9976925b8f25725a30e1ee6
      url: "https://pub.dev"
    source: hosted
    version: "1.0.8"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_launcher_icons:
    dependency: "direct dev"
    description:
      name: flutter_launcher_icons
      sha256: "619817c4b65b322b5104b6bb6dfe6cda62d9729bd7ad4303ecc8b4e690a67a77"
      url: "https://pub.dev"
    source: hosted
    version: "0.14.1"
  flutter_lin[...]6e7a077e02254531b138a15aec3bd143c1a8b3c"
      url: "https://pub.dev"
    source: hosted
    version: "1.10.0"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      sha256: "556692adab6cfa87322a115640c11f13cb77b3f076ddcc5d6ae3c20242bedcde"
      url: "https://pub.dev"
    source: hosted
    version: "1.2.0"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      sha256: a29248a84fbb7c79282b40b8c72a1209db169a2e0542bce341da992fe1bc7e84
      url: "https://pub.dev"
    source: hosted
    version: "1.2.1"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      sha256: f9049c039ebfeb4cf7a7104a675823cd72dba8297f264b6637062516699fa006
      url: "https://pub.dev"
    source: hosted
    version: "1.4.0"
  vector_graphics:
    dependency: transitive
    description:
      name: vector_graphics
      sha256: "773c9522d66d523e1c7b25dfb95cc91c26a1e17b107039cfe147285e92de7878"
      url: "https://pub.dev"
    source: hosted
    version: "1.1.14"
  vector_graphics_codec:
    dependency: transitive
    description:
      name: vector_graphics_codec
      sha256: "2430b973a4ca3c4dbc9999b62b8c719a160100dcbae5c819bae0cacce32c9cdb"
      url: "https://pub.dev"
    source: hosted
    version: "1.1.12"
  vector_graphics_compiler:
    dependency: transitive
    description:
      name: vector_graphics_compiler
      sha256: ab9ff38fc771e9ee1139320adbe3d18a60327370c218c60752068ebee4b49ab1
      url: "https://pub.dev"
    source: hosted
    version: "1.1.15"
  vector_math:
    dependency: transitive
    description:
      name: vector_math
      sha256: "80b3257d1492ce4d091729e3a67a60407d227c27241d6927be0130c98e741803"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.4"
  web:
    dependency: transitive
    description:
      name: web
      sha256: cd3543bd5798f6ad290ea73d210f423502e71900302dde696f8bff84bf89a1cb
      url: "https://pub.dev"
    source: hosted
    version: "1.1.0"
  xml:
    dependency: transitive
    description:
      name: xml
      sha256: b015a8ad1c488f66851d762d3090a21c600e479dc75e68328c52774040cf9226
      url: "https://pub.dev"
    source: hosted
    version: "6.5.0"
  yaml:
    dependency: transitive
    description:
      name: yaml
      sha256: "75769501ea3489fca56601ff33454fe45507ea3bfb014161abc3b43ae25989d5"
      url: "https://pub.dev"
    source: hosted
    version: "3.1.2"
sdks:
  dart: ">=3.5.4 <4.0.0"
  flutter: ">=3.22.0"

---- End pubspec.lock ----
---- Log transcript ----
FINE: Pub 3.5.4
MSG : Resolving dependencies...
SLVR: fact: vedicapp is 1.0.0+1
SLVR: derived: vedicapp
SLVR: fact: vedicapp depends on flutter from sdk
SLVR: fact: vedicapp depends on flutter_svg ^2.0.4
SLVR: fact: vedicapp depends on provider ^6.0.5
SLVR: fact: vedicapp depends on cupertino_icons ^1.0.8
SLVR: fact: vedicapp depends on scroll_to_index ^3.0.1
SLVR: fact: vedicapp depends on flutter_launcher_icons ^0.14.1
SLVR: fact: vedicapp depends on flutter_lints ^4.0.0
SLVR:   selecting vedicapp
SLVR:   derived: flutter_lints ^4.0.0
SLVR:   derived: flutter_launcher_icons ^0.14.1
SLVR:   derived: scroll_to_index ^3.0.1
SLVR:   derived: cupertino_icons ^1.0.8
SLVR:   derived: provider ^6.0.5
SLVR:   derived: flutter_svg ^2.0.4
SLVR:   derived: flutter from sdk
SLVR:   fact: flutter_lints 4.0.0 depends on lints ^4.0.0
SLVR:     selecting flutter_lints 4.0.0
SLVR:     derived: lints ^4.0.0
SLVR:     fact: flutter_launcher_icons 0.14.1 depends on args ^2.5.0
SLVR:     fact: flutter_launcher_icons 0.14.1 depends on checked_yaml ^2.0.3
SLVR:     fact: flutter_launcher_icons 0.14.1 depends on cli_util ^0.4.1
SLVR:     fact: flutter_launcher_icons 0.14.1 depends on image ^4.2.0
SLVR:     fact: flutter_launcher_icons 0.14.1 depends on json_annotation ^4.9.0
SLVR:     fact: flutter_launcher_icons 0.14.1 depends on path ^1.9.0
SLVR:     fact: flutter_launcher_icons 0.14.1 depends on yaml ^3.1.2
SLVR:       selecting flutter_launcher_icons 0.14.1
SLVR:       derived: yaml ^3.1.2
SLVR:       derived: path ^1.9.0
SLVR:       derived: json_annotation ^4.9.0
SLVR:       derived: image ^4.2.0
SLVR:       derived: cli_util ^0.4.1
SLVR:       derived: checked_yaml ^2.0.3
SLVR:       derived: args ^2.5.0
SLVR:       fact: scroll_to_index 3.0.1 depends on flutter from sdk
SLVR:         selecting scroll_to_index 3.0.1
SLVR:           selecting cupertino_icons 1.0.8
SLVR:           fact: provider 6.1.2 depends on collection ^1.15.0
SLVR:           fact: provider 6.1.2 depends on flutter from sdk
SLVR:           fact: provider 6.1.2 depends on nested ^1.0.0
SLVR:             selecting provider 6.1.2
SLVR:             derived: nested ^1.0.0
SLVR:             derived: collection ^1.15.0
SLVR:             fact: flutter_svg 2.0.14 depends on flutter from sdk
SLVR:             fact: flutter_svg 2.0.14 depends on http ^1.0.0
SLVR:             fact: flutter_svg 2.0.14 depends on vector_graphics ^1.1.13
SLVR:             fact: flutter_svg 2.0.14 depends on vector_graphics_codec ^1.1.11+1
SLVR:             fact: flutter_svg 2.0.14 depends on vector_graphics_compiler ^1.1.14
SLVR:               selecting flutter_svg 2.0.14
SLVR:               derived: vector_graphics_compiler ^1.1.14
SLVR:               derived: vector_graphics_codec ^1.1.11+1
SLVR:               derived: vector_graphics ^1.1.13
SLVR:               derived: http ^1.0.0
SLVR:               fact: flutter 0.0.0 from sdk depends on characters 1.3.0
SLVR:               fact: flutter 0.0.0 from sdk depends on collection 1.18.0
SLVR:               fact: flutter 0.0.0 from sdk depends on material_color_utilities 0.11.1
SLVR:               fact: flutter 0.0.0 from sdk depends on meta 1.15.0
SLVR:               fact: flutter 0.0.0 from sdk depends on vector_math 2.1.4
SLVR:               fact: flutter 0.0.0 from sdk depends on sky_engine from sdk
SLVR:                 selecting flutter 0.0.0 from sdk
SLVR:                 derived: sky_engine from sdk
SLVR:                 derived: vector_math 2.1.4
SLVR:                 derived: meta 1.15.0
SLVR:                 derived: material_color_utilities 0.11.1
SLVR:                 derived: collection 1.18.0
SLVR:                 derived: characters 1.3.0
SLVR:                   selecting lints 4.0.0
SLVR:                   fact: yaml 3.1.2 depends on collection ^1.15.0
SLVR:                   fact: yaml 3.1.2 depends on source_span ^1.8.0
SLVR:                   fact: yaml 3.1.2 depends on string_scanner ^1.1.0
SLVR:                     selecting yaml 3.1.2
SLVR:                     derived: string_scanner ^1.1.0
SLVR:                     derived: source_span ^1.8.0
SLVR:                       selecting path 1.9.0
SLVR:                       fact: json_annotation 4.9.0 depends on meta ^1.4.0
SLVR:                         selecting json_annotation 4.9.0
SLVR:                         fact: image 4.3.0 depends on archive ^3.6.1
SLVR:                         fact: image 4.3.0 depends on meta ^1.3.0
SLVR:                         fact: image 4.3.0 depends on xml ^6.0.1
SLVR:                           selecting image 4.3.0
SLVR:                           derived: xml ^6.0.1
SLVR:                           derived: archive ^3.6.1
SLVR:                           fact: cli_util 0.4.2 depends on meta ^1.7.0
SLVR:                           fact: cli_util 0.4.2 depends on path ^1.8.0
SLVR:                             selecting cli_util 0.4.2
SLVR:                             fact: checked_yaml 2.0.3 depends on json_annotation ^4.3.0
SLVR:                             fact: checked_yaml 2.0.3 depends on source_span ^1.8.0
SLVR:                             fact: checked_yaml 2.0.3 depends on yaml ^3.0.0
SLVR:                               selecting checked_yaml 2.0.3
SLVR:                                 selecting args 2.6.0
SLVR:                                 fact: nested 1.0.0 depends on flutter from sdk
SLVR:                                   selecting nested 1.0.0
SLVR:                                     selecting collection 1.18.0
SLVR:                                     fact: vector_graphics_compiler 1.1.15 depends on args ^2.3.0
SLVR:                                     fact: vector_graphics_compiler 1.1.15 depends on meta ^1.7.0
SLVR:                                     fact: vector_graphics_compiler 1.1.15 depends on path ^1.8.0
SLVR:                                     fact: vector_graphics_compiler 1.1.15 depends on path_parsing ^1.0.1
SLVR:                                     fact: vector_graphics_compiler 1.1.15 depends on vector_graphics_codec ^1.1.11+1
SLVR:                                     fact: vector_graphics_compiler 1.1.15 depends on xml >=6.3.0 <=6.5.0
SLVR:                                       selecting vector_graphics_compiler 1.1.15
SLVR:                                       derived: xml >=6.3.0 <=6.5.0
SLVR:                                       derived: path_parsing ^1.0.1
SLVR:                                         selecting vector_graphics_codec 1.1.12
SLVR:                                         fact: vector_graphics 1.1.14 depends on flutter from sdk
SLVR:                                         fact: vector_graphics 1.1.14 depends on http ^1.0.0
SLVR:                                         fact: vector_graphics 1.1.14 depends on vector_graphics_codec ^1.1.11+1
SLVR:                                           selecting vector_graphics 1.1.14
SLVR:                                           fact: http 1.2.2 depends on async ^2.5.0
SLVR:                                           fact: http 1.2.2 depends on http_parser ^4.0.0
SLVR:                                           fact: http 1.2.2 depends on meta ^1.3.0
SLVR:                                           fact: http 1.2.2 depends on web >=0.5.0 <2.0.0
SLVR:                                             selecting http 1.2.2
SLVR:                                             derived: web >=0.5.0 <2.0.0
SLVR:                                             derived: http_parser ^4.0.0
SLVR:                                             derived: async ^2.5.0
SLVR:                                               selecting sky_engine 0.0.99 from sdk
SLVR:                                                 selecting vector_math 2.1.4
SLVR:                                                   selecting meta 1.15.0
SLVR:                                                   fact: material_color_utilities 0.11.1 depends on collection ^1.15.0
SLVR:                                                     selecting material_color_utilities 0.11.1
SLVR:                                                       selecting characters 1.3.0
SLVR:                                                       fact: string_scanner 1.2.0 depends on source_span ^1.8.0
SLVR:                                                         selecting string_scanner 1.2.0
SLVR:                                                         fact: source_span 1.10.0 depends on collection ^1.15.0
SLVR:                                                         fact: source_span 1.10.0 depends on path ^1.8.0
SLVR:                                                         fact: source_span 1.10.0 depends on term_glyph ^1.2.0
SLVR:                                                           selecting source_span 1.10.0
SLVR:                                                           derived: term_glyph ^1.2.0
SLVR:                                                           fact: xml 6.5.0 depends on collection ^1.18.0
SLVR:                                                           fact: xml 6.5.0 depends on meta ^1.9.0
SLVR:                                                           fact: xml 6.5.0 depends on petitparser ^6.0.0
SLVR:                                                             selecting xml 6.5.0
SLVR:                                                             derived: petitparser ^6.0.0
SLVR:                                                             fact: archive 3.6.1 depends on crypto ^3.0.3
SLVR:                                                             fact: archive 3.6.1 depends on path ^1.8.0
SLVR:                                                               selecting archive 3.6.1
SLVR:                                                               derived: crypto ^3.0.3
SLVR:                                                               fact: path_parsing 1.1.0 depends on meta ^1.3.0
SLVR:                                                               fact: path_parsing 1.1.0 depends on vector_math ^2.1.0
SLVR:                                                                 selecting path_parsing 1.1.0
SLVR:                                                                   selecting web 1.1.0
SLVR:                                                                   fact: http_parser 4.0.2 depends on collection ^1.15.0
SLVR:                                                                   fact: http_parser 4.0.2 depends on source_span ^1.8.0
SLVR:                                                                   fact: http_parser 4.0.2 depends on string_scanner ^1.1.0
SLVR:                                                                   fact: http_parser 4.0.2 depends on typed_data ^1.3.0
SLVR:                                                                     selecting http_parser 4.0.2
SLVR:                                                                     derived: typed_data ^1.3.0
SLVR:                                                                     fact: async 2.12.0 depends on collection ^1.15.0
SLVR:                                                                     fact: async 2.12.0 depends on meta ^1.3.0
SLVR:                                                                       selecting async 2.12.0
SLVR:                                                                         selecting term_glyph 1.2.1
SLVR:                                                                         fact: petitparser 6.0.2 depends on meta ^1.9.0
SLVR:                                                                           selecting petitparser 6.0.2
SLVR:                                                                           fact: crypto 3.0.6 depends on typed_data ^1.3.0
SLVR:                                                                             selecting crypto 3.0.6
SLVR:                                                                             fact: typed_data 1.4.0 depends on collection ^1.15.0
SLVR:                                                                               selecting typed_data 1.4.0
SLVR: Version solving took 0:00:00.399466 seconds.
    | Tried 1 solutions.
FINE: Resolving dependencies finished (0.4s).
MSG : Downloading packages...
FINE: Downloading packages finished (0.0s).
IO  : Get versions from https://pub.dev/api/packages/archive.
IO  : HTTP GET https://pub.dev/api/packages/archive
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: windows
    | X-Pub-Command: get
    | X-Pub-Session-ID: 7337F511-BE17-40D7-B696-F99781A9282F
    | X-Pub-Environment: vscode.dart-code:flutter_cli:get
    | user-agent: Dart pub 3.5.4
IO  : Attempt #2 for fetching versions for "archive" from "https://pub.dev/api/packages/archive"
IO  : HTTP GET https://pub.dev/api/packages/archive
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: windows
    | X-Pub-Command: get
    | X-Pub-Session-ID: 7337F511-BE17-40D7-B696-F99781A9282F
    | X-Pub-Environment: vscode.dart-code:flutter_cli:get
    | user-agent: Dart pub 3.5.4
IO  : Attempt #3 for fetching versions for "archive" from "https://pub.dev/api/packages/archive"
IO  : HTTP GET https://pub.dev/api/packages/archive
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: windows
    | X-Pub-Command: get
    | X-Pub-Session-ID: 7337F511-BE17-40D7-B696-F99781A9282F
    | X-Pub-Environment: vscode.dart-code:flutter_cli:get
    | user-agent: Dart pub 3.5.4
IO  : Attempt #4 for fetching versions for "archive" from "https://pub.dev/api/packages/archive"
IO  : HTTP GET https://pub.dev/api/packages/archive
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: windows
    | X-Pub-Command: get
    | X-Pub-Session-ID: 7337F511-BE17-40D7-B696-F99781A9282F
    | X-Pub-Environment: vscode.dart-code:flutter_cli:get
    | user-agent: Dart pub 3.5.4
IO  : Attempt #5 for fetching versions for "archive" from "https://pub.dev/api/packages/archive"
IO  : HTTP GET https://pub.dev/api/packages/archive
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: windows
    | X-Pub-Command: get
    | X-Pub-Session-ID: 7337F511-BE17-40D7-B696-F99781A9282F
    | X-Pub-Environment: vscode.dart-code:flutter_cli:get
    | user-agent: Dart pub 3.5.4
IO  : Attempt #6 for fetching versions for "archive" from "https://pub.dev/api/packages/archive"
IO  : HTTP GET https://pub.dev/api/packages/archive
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: windows
    | X-Pub-Command: get
    | X-Pub-Session-ID: 7337F511-BE17-40D7-B696-F99781A9282F
    | X-Pub-Environment: vscode.dart-code:flutter_cli:get
    | user-agent: Dart pub 3.5.4
IO  : Attempt #7 for fetching versions for "archive" from "https://pub.dev/api/packages/archive"
IO  : HTTP GET https://pub.dev/api/packages/archive
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: windows
    | X-Pub-Command: get
    | X-Pub-Session-ID: 7337F511-BE17-40D7-B696-F99781A9282F
    | X-Pub-Environment: vscode.dart-code:flutter_cli:get
    | user-agent: Dart pub 3.5.4
ERR : Null check operator used on a null value
FINE: Exception type: _TypeError
ERR : package:pub/src/source/hosted.dart 778:33              HostedSource._getAdvisories.readAdvisoriesFromCache
    | ===== asynchronous gap ===========================
    | package:pub/src/source/hosted.dart 796:12              HostedSource._getAdvisories
    | ===== asynchronous gap ===========================
    | package:pub/src/source/hosted.dart 1084:24             HostedSource.getAdvisoriesForPackageVersion
    | ===== asynchronous gap ===========================
    | package:pub/src/solver/report.dart 416:26              SolveReport._reportPackage
    | ===== asynchronous gap ===========================
    | package:pub/src/solver/report.dart 220:18              SolveReport._reportChanges
    | ===== asynchronous gap ===========================
    | package:pub/src/solver/report.dart 75:21               SolveReport.show
    | ===== asynchronous gap ===========================
    | package:pub/src/entrypoint.dart 580:5                  Entrypoint.acquireDependencies
    | ===== asynchronous gap ===========================
    | package:pub/src/command/get.dart 76:5                  GetCommand.runProtected
    | ===== asynchronous gap ===========================
    | package:pub/src/command.dart 196:7                     PubCommand.run
    | ===== asynchronous gap ===========================
    | package:args/command_runner.dart 212:13                CommandRunner.runCommand
    | ===== asynchronous gap ===========================
    | package:dartdev/dartdev.dart 236:18                    DartdevRunner.runCommand
    | ===== asynchronous gap ===========================
    | package:dartdev/dartdev.dart 47:16                     runDartdev
    | ===== asynchronous gap ===========================
    | C:\b\s\w\ir\x\w\sdk\pkg\dartdev\bin\dartdev.dart 13:5  main
ERR : This is an unexpected error. The full log and other details are collected in:
    | 
    |     C:\Users\Xaria\AppData\Local\Pub\Cache\log\pub_log.txt
    | 
    | Consider creating an issue on https://github.com/dart-lang/pub/issues/new
    | and attaching the relevant parts of that log file.
---- End log transcript ----

**Comment by jonasfj** [comment] 2024-12-05 09:33
Closing as duplicate of https://github.com/dart-lang/pub/issues/4422

quick note: Please use [code fences](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) when posting logs, for large log files please use a [gist](https://gist.github.com/).

**Closed by jonasfj** 2024-12-05 09:33 UTC
