### ISSUE TITLE
Failed Dependency package:pub/src/http.dart 218:5                 _ThrowingClient.send

### ISSUE THREAD

**Issue by nobewp** [dart-lang/pub#2073] opened 2019-02-26 06:46 UTC
HTTP error 424: Failed Dependency
package:pub/src/http.dart 218:5                 _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 301:37       BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 196:13       BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 371:48          Entrypoint._get.<fn>
===== asynchronous gap ===========================
dart:async

**Comment by soloFZZ** [comment] 2019-02-26 09:49
me too, Who has a solution

**Comment by zoechi** [comment] 2019-02-26 10:07
Possible duplicate of https://github.com/flutter/flutter/issues/28498

**Comment by chenglu** [comment] 2019-02-26 14:44
It has been fixed, see my comments on [#28498](https://github.com/flutter/flutter/issues/28498#issuecomment-467462967) for more information.

**Closed** 2019-03-04 20:09 UTC
