### ISSUE TITLE
Bad state: Origin is only applicable schemes http and https:

### ISSUE THREAD

**Issue by abdulrahmam** [dart-lang/pub#2693] opened 2020-10-27 11:39 UTC

**Comment by sigurdm** [comment] 2020-10-27 12:08
I think this is a duplicate of: https://github.com/dart-lang/pub/issues/1941

@jonasfj we should consider if we can make a nicer error message here.

**Comment by jonasfj** [comment] 2020-10-27 14:08
**original title:**

> Bad state: Origin is only applicable schemes http and https: c:%5CUsers%5Ca9552%5CAppData%5CLocal%5CPub%5CCache/api/packages/cupertino_icons package:pub/src/source/hosted.dart 439:7 BoundHostedSource._throwFriendlyError package:pub/src/source/hosted.dart 190:7 BoundHostedSource._fetchVersions ===== asynchronous gap =========================== dart:async _CustomZone.runUnary package:pub/src/rate_limited_scheduler.dart 83:30 RateLimitedScheduler._processNextTask.runJob package:pub/src/rate_limited_scheduler.dart 86:30 RateLimitedScheduler._processNextTask package:pool/pool.dart 127:28 Pool.withResource ===== asynchronous gap =========================== package:pub/src/rate_limited_scheduler.dart 130:37 RateLimitedScheduler.schedule.<fn> This is an unexpected error. Please run pub --trace upgrade and include the logs in an issue on https://github.com/dart-lang/pub/issues/new Process finished with exit code 1

**Comment by jonasfj** [comment] 2020-10-27 14:17
Yes, quite likely this is similar to #1941, I'm going to close this because the issue is poorly written.

But filed https://github.com/dart-lang/pub/issues/2695 to print a prettier message.

**Closed by jonasfj** 2020-10-27 14:17 UTC
