### ISSUE TITLE
Get score test before publishing packages

### ISSUE THREAD

**Issue by amorenew** [dart-lang/pub#3699] opened 2022-12-15 17:26 UTC
I want to know pub points before publishing my packages
`dart pub publish --dry-run` doesn't return the points report even though I have no example folder
```
Package has 0 warnings.
The server may enforce additional checks.
```
https://pub.dev/packages/common_authentication/score

<img width="454" alt="Screenshot 2022-12-15 at 7 22 45 PM" src="https://user-images.githubusercontent.com/2842459/207926682-9223b0c5-f649-47a8-91f3-1b3dd4056bc1.png">

**Comment by sigurdm** [comment] 2022-12-22 10:08
I think this issue is more or less a duplicate of https://github.com/dart-lang/pub-dev/issues/4489 .

**Closed by sigurdm** 2022-12-22 10:08 UTC

**Comment by amorenew** [comment] 2022-12-22 11:28
@sigurdm "Staged publishing" is different than getting the full score before publishing
"Staged publishing" means your server will cost money to return the score while my case is local checking for additional checks "The server may enforce additional checks."

"Staged publishing" costs money vs the local "additional checks" are free

**Comment by sigurdm** [comment] 2022-12-22 11:47
Well you can run https://pub.dev/packages/pana on your package yourself. This will be the closest approximation to the checks that the pub.dev site runs on your package.

**Comment by amorenew** [comment] 2022-12-22 12:03
@sigurdm yes, this is what I was looking for, I wonder why publish --dry-run doesn't provide this detailed report too?

## ✓ Follow Dart file conventions (30 / 30)
### [*] 10/10 points: Provide a valid `pubspec.yaml`
### [*] 5/5 points: Provide a valid `README.md`
### [*] 5/5 points: Provide a valid `CHANGELOG.md`
### [*] 10/10 points: Use an OSI-approved license
Detected license: `BSD-3-Clause`.
## ✓ Provide documentation (10 / 10)
### [*] 10/10 points: Package has an example
## ✓ Platform support (20 / 20)
### [*] 20/20 points: Supports 3 of 6 possible platforms (**iOS**, **Android**, **Web**, Windows, MacOS, Linux)
* ✓ Android
* ✓ iOS
* ✓ Web
## ✓ Pass static analysis (30 / 30)
### [*] 30/30 points: code has no errors, warnings, lints, or formatting issue
## ✓ Support up-to-date dependencies (20 / 20)
### [*] 10/10 points: All of the package dependencies are supported in the latest version
### [*] 10/10 points: Package supports latest stable Dart and Flutter SDKs
## ✓ Support sound null safety (20 / 20)
### [*] 20/20 points: Package and dependencies are fully migrated to null safety!

Points: 130/130.

**Comment by sigurdm** [comment] 2022-12-22 12:08
In general the pub client is host agnostic - it just defaults to pub.dev.

Most of the checks in pana are specific requirements that pub.dev has - other repositories might not care about eg. formatting or length of the description field.

**Comment by amorenew** [comment] 2022-12-22 12:09
Thanks a lot for the clarification
