### ISSUE TITLE
`Invalid HTTP header field value` when publishing to private repo

### ISSUE THREAD

**Issue by Cacofonix6** [dart-lang/pub#3621] opened 2022-10-24 05:27 UTC
I am currently testing JFrog as a private package repo.

My package is just the default package that is generated with `flutter create --template=package repo_test`.

I have set up the auth token using `dart pub token add <URL>` which seems to be the correct token from my testing.

I have `publish_to: https://<myrepo>/artifactory/api/pub/repo_test/` in my pubspec.yaml.

When I run `dart pub publish` I recieve the following error after confirming the publish:

```FINE: Showing confirm message: 
    | Do you want to publish repo_test 0.0.1 to https://<myrepo>/artifactory/api/pub/repo_test/
MSG : Uploading...
IO  : HTTP GET https://<myrepo>/artifactory/api/pub/repo_test/api/packages/versions/new
    | Accept: application/vnd.pub.v2+json
    | authorization: <censored>
    | user-agent: Dart pub 2.18.2
FINE: Uploading finished (0.1s).
ERR : Invalid HTTP header field value: "Bearer \u0016" (at character 8)
    | Bearer 
    |        ^
FINE: Exception type: FormatException
ERR : dart:_http                                         _HttpHeaders.set
    | package:http/src/io_client.dart 63:27              IOClient.send.<fn>
    | dart:collection                                    _LinkedHashMapMixin.forEach
    | package:http/src/io_client.dart 62:23              IOClient.send
    | ===== asynchronous gap ===========================
    | package:pub/src/http.dart 68:30                    _PubHttpClient.send
    | ===== asynchronous gap ===========================
    | package:http/retry.dart 111:20                     RetryClient.send
    | ===== asynchronous gap ===========================
    | package:pub/src/http.dart 175:26                   _ThrowingClient.send
    | ===== asynchronous gap ===========================
    | package:pub/src/http.dart 379:18                   _ThrottleClient.send
    | ===== asynchronous gap ===========================
    | package:pub/src/authentication/client.dart 52:24   _AuthenticatedClient.send
    | ===== asynchronous gap ===========================
    | package:http/src/base_client.dart 93:32            BaseClient._sendUnstreamed
    | ===== asynchronous gap ===========================
    | package:pub/src/command/lish.dart 95:24            LishCommand._publishUsingClient.<fn>
    | ===== asynchronous gap ===========================
    | package:pub/src/command/lish.dart 93:7             LishCommand._publishUsingClient
    | ===== asynchronous gap ===========================
    | package:pub/src/authentication/client.dart 133:12  withAuthenticatedClient
    | ===== asynchronous gap ===========================
    | package:pub/src/command/lish.dart 186:9            LishCommand._publish
    | ===== asynchronous gap ===========================
    | package:pub/src/command/lish.dart 245:7            LishCommand.runProtected
```

I can't find any information about this issue anywhere so any help would be greatly appreciated.

**Comment by sigurdm** [comment] 2023-01-05 09:50
Our suspicion is that a DEL character has entered your token by you pressing backspace while typing the token.

This is likely a bug in our input handling.

I am not able to reproduce this right now.

What platform are you on?

If this is right, the workaround is to `dart pub token remove <URL>` and re-adding it, without pressing delete.

You can also try `echo <Token> | dart pub token add <URL>` - but note that will leave the token in your shell history.

**Comment by sigurdm** [comment] 2023-01-26 12:34
Closing assuming this is covered by https://github.com/dart-lang/pub/pull/3732.

Please reopen if this is still an issue and you can provide more information.

**Closed by sigurdm** 2023-01-26 12:34 UTC
Labels: bug, needs info
