### ISSUE TITLE
I get this error " flutter pub get "

### ISSUE THREAD

**Issue by ITApexGroup** [dart-lang/pub#4336] opened 2024-07-31 05:08 UTC
Downloading packages... 
Null check operator used on a null value
package:pub/src/source/hosted.dart 773:33                       HostedSource._getAdvisories.readAdvisoriesFromCache
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 791:12                       HostedSource._getAdvisories
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 1079:24                      HostedSource.getAdvisoriesForPackageVersion
===== asynchronous gap ===========================
package:pub/src/solver/report.dart 414:26                       SolveReport._reportPackage
===== asynchronous gap ===========================
package:pub/src/solver/report.dart 218:18                       SolveReport._reportChanges
===== asynchronous gap ===========================
package:pub/src/solver/report.dart 73:21                        SolveReport.show
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 568:5                           Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 77:5                           GetCommand.runProtected
===== asynchronous gap ===========================
package:pub/src/command.dart 196:7                              PubCommand.run
===== asynchronous gap ===========================
package:args/command_runner.dart 212:13                         CommandRunner.runCommand
===== asynchronous gap ===========================
package:dartdev/dartdev.dart 232:18                             DartdevRunner.runCommand
===== asynchronous gap ===========================
package:dartdev/dartdev.dart 46:16                              runDartdev
===== asynchronous gap ===========================
/Volumes/Work/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart 13:5  main
This is an unexpected error. The full log and other details are collected in:

    /Users/thurainhein/.pub-cache/log/pub_log.txt

**Comment by sigurdm** [comment] 2024-08-01 07:55
Duplicate of https://github.com/dart-lang/pub/issues/4335

Could you attach the log file?

**Comment by sigurdm** [comment] 2024-08-01 12:35
Closing this as duplicate. Please add any useful info to the linked issue!

**Closed by sigurdm** 2024-08-01 12:35 UTC
