### ISSUE TITLE
I can't pub get from git url

### ISSUE THREAD

**Issue by fingdo** [dart-lang/pub#3397] opened 2022-04-22 11:59 UTC
Running "flutter pub get" in flutter...                         
Illegal scheme character (at character 4)
git@git.hbkejin.com:appclient/flutter-core.git
   ^
dart:core                                           Uri.parse
package:path/src/context.dart 1077:33               _parseUri
package:path/src/context.dart 1052:22               Context.prettyUri
package:path/path.dart 461:34                       prettyUri
package:pub/src/source/git.dart 276:16              GitSource._describeUncached
===== asynchronous gap ===========================
package:pub/src/source/git.dart 224:11              GitSource.doGetVersions.<fn>
===== asynchronous gap ===========================
package:pool/pool.dart 127:14                       Pool.withResource
===== asynchronous gap ===========================
package:pub/src/source/git.dart 218:12              GitSource.doGetVersions
===== asynchronous gap ===========================
package:pub/src/system_cache.dart 186:20            SystemCache.getVersions
===== asynchronous gap ===========================
package:pub/src/solver/package_lister.dart 82:31    PackageLister._versions.<fn>
===== asynchronous gap ===========================
package:pub/src/solver/package_lister.dart 126:15   PackageLister.countVersions
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 336:14   VersionSolver._choosePackageVersion.<fn>
===== asynchronous gap ===========================
package:pub/src/utils.dart 281:26                   minByAsync
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 335:19   VersionSolver._choosePackageVersion
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 97:18    VersionSolver.solve.<fn>
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 954:14           HostedSource.withPrefetching.<fn>
===== asynchronous gap ===========================
package:pub/src/rate_limited_scheduler.dart 110:14  RateLimitedScheduler.withPrescheduling
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 953:12           HostedSource.withPrefetching
===== asynchronous gap ===========================
package:pub/src/solver/version_solver.dart 93:14    VersionSolver.solve
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 280:16              Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/get.dart 52:5               GetCommand.runProtected
This is an unexpected error. The full log and other details are collected in:

    /Users/fingdo/.pub-cache/log/pub_log.txt

Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.
pub get failed (65; and attaching the relevant parts of that log file.)
See it:[File](https://drive.google.com/file/d/1LBw635n-ZvkdhYsp7WN_0qdzrOVyLlOe/view?usp=sharing)

I try 
ssh -T git@git.hbkejin.com
It success~
Welcome to GitLab, XX!

**Comment by sigurdm** [comment] 2022-04-22 12:55
I believe this is a duplicate of https://github.com/dart-lang/pub/issues/3377 fixed in https://github.com/dart-lang/pub/pull/3381

**Closed by sigurdm** 2022-04-22 12:55 UTC
