### ISSUE TITLE
can't execute "pub global activate ..."

### ISSUE THREAD

**Issue by diocore** [dart-lang/pub#1630] opened 2017-06-03 19:40 UTC
When i try to use the command "pub global activate ...", for example 
"pub global activate aqueduct" or "pub global activate stagehand" the execution gets stuck while resolving dependencies. 
Here is the console contents after running "pub global activate -v aqueduct"
[pub global activate -v aqueduc.txt](https://github.com/dart-lang/pub/files/1049870/pub.global.activate.-v.aqueduc.txt)

I'm using the Windows 10 Ubuntu subsystem and I've got a clean windows installation (about a week old, but i tried it back then too).

**Comment by nex3** [comment] 2017-06-05 19:18
This looks like a duplicate of #1610. It should be fixed in the next dev release.

It looks like the underlying issue is that your connection is getting closed. Pub won't be able to download versions if it can't reliably connect to the package server, so you'll need to fix that even once pub handles those errors more gracefully.

**Closed by nex3** 2017-06-05 19:18 UTC

**Comment by diocore** [comment] 2017-06-05 19:23
Okay. I tried 1.23 stable and the 1.24 unstable version of dart. Or are you
referring to the upcoming version?

And you said I need to fix this. How would I be able to fix this? Any hints
on how do to that? Thanks for your response


On Jun 5, 2017 9:18 PM, "Natalie Weizenbaum" <notifications@github.com>
wrote:

Closed #1630 <https://github.com/dart-lang/pub/issues/1630>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dart-lang/pub/issues/1630#event-1110521408>, or mute
the thread

**Comment by diocore** [comment] 2017-06-05 19:28
And on further reading in the suggested thread, how is it the same issue?
He says it's completed but mine does not complete. And I disabled my
firewall and my connection is stable.
For reference, it works in powershell or cmd on the same machine, only the
windows ubderlying Ubuntu subsystems  bash shell can't resolve this command.
Everything else works without a problem with the sub system.

**Comment by nex3** [comment] 2017-06-05 19:34
The log you posted contains a number of connection errors. Connection errors cause #1610, and one of the potential symptoms of #1610 is package installation failing to terminate.

**Comment by diocore** [comment] 2017-06-05 19:54
Okay, but if I run it without the exteded "-v" i get the follwoing:

pub global activate aqueduct
Resolving dependencies... Class Id: 0
../../runtime/vm/raw_object.cc: 283: error: unreachable code
Dumping native stack trace for thread 5b
  [0x000000000090efc3] dart::Profiler::DumpStackTrace()
  [0x000000000090efc3] dart::Profiler::DumpStackTrace()
  [0x000000000068d1a1] dart::DynamicAssertionHelper::Fail(char const*, ...)
  [0x00000000009122a0]
dart::RawObject::VisitPointers(dart::ObjectPointerVisitor*)
  [0x0000000000951b18]
dart::Scavenger::ProcessToSpace(dart::ScavengerVisitor*)
  [0x000000000095212d] dart::Scavenger::Scavenge(bool)
  [0x0000000000768609] dart::Heap::CollectNewSpaceGarbage(dart::Thread*,
dart::Heap::ApiCallbacks, dart::Heap::GCReason)
  [0x0000000000767692] dart::Heap::AllocateNew(long)
  [0x00000000007e715e] dart::Object::Allocate(long, long, dart::Heap::Space)
  [0x00000000007ea9e6] dart::Array::New(long, dart::Heap::Space)
  [0x00000000009bd031] dart::DRT_AllocateArray(dart::NativeArguments)
  [0x00007f15c98e061b] [Stub] CallToRuntime
  [0x00007f15c98e16e2] [Stub] AllocateArray


So ' error: unreachable code' ?
I'm lost


2017-06-05 21:34 GMT+02:00 Natalie Weizenbaum <notifications@github.com>:

**Comment by nex3** [comment] 2017-06-05 19:55
That looks like a VM error. I'd suggest reporting it on [the SDK repo](https://github.com/dart-lang/sdk).
