### ISSUE TITLE
Pub upgrade pretents to succeed even though it didn't due to missing internet connection

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/pub#1610] opened 2017-05-18 17:27 UTC
On Windows, I unplugged my network connection and tried to use pub (PowerShell commands shown, problem also exists in regular CMD):

```ps1
C:\src\flutter\packages\flutter_tools> ..\..\bin\cache\dart-sdk\bin\pub.bat upgrade --verbosity=error --no-packages-dir
C:\src\flutter\packages\flutter_tools> $?
True
C:\src\flutter\packages\flutter_tools> ..\..\bin\cache\dart-sdk\bin\pub.bat upgrade --verbosity=error --no-packages-dir
C:\src\flutter\packages\flutter_tools> $LASTEXITCODE
0
```

Pub pretends to be successful. However, no `.packages` file is generated and calling `dart` on my program fails after that because it's missing the `.packages` file. If I run `pub` with the `-v` option, I get the reason for the error somewhere buried in an endless log (it still exits with exitcode 0 indicating success):
```
IO  : Get versions from https://pub.dartlang.org/api/packages/file.
FINE: HTTP GET https://pub.dartlang.org/api/packages/file
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: windows
    | X-Pub-Command: upgrade
    | X-Pub-Session-ID: 0AB55CAC-FDCA-43FB-9C00-66B2E9D70727
    | X-Pub-Reason: direct
    | user-agent: Dart pub 1.23.0-dev.11.11
SLVR: Could not get versions for file from hosted:
    | Could not resolve URL "https://pub.dartlang.org".
    |
    | package:pub/src/source/hosted.dart 329                    BoundHostedSource._throwFriendlyError
    | package:pub/src/source/hosted.dart 139                    BoundHostedSource.doGetVersions
```

Expected behavior: `pub --verbosity=error` should print a clear error message indicating the failure and exit with an exitcode indicating failure.

This bug is currently confusing many Windows users of Flutter because they get a confusing error message when trying to launch Flutter in the Dart VM due to a missing `.packages` file, see https://github.com/flutter/flutter/issues/10138 or https://github.com/flutter/flutter/issues/8786.

Note: Unplugging my network connection was only used to re-produce the failure. The Flutter users probably have a firewall installed blocking access to the internet or their internet connection is unreliable in other ways. Either way, there should be a clear error message from pub if it cannot connect to the internet.

**Comment by goderbauer** [comment] 2017-05-18 17:34
In case it is important, the real users are seeing a slightly different error in their `pub -v` on their restricted internet connection (I don't know what the restriction is, maybe a firewall?):
```
IO  : Get versions from https://pub.dartlang.org/api/packages/coverage.
FINE: HTTP GET https://pub.dartlang.org/api/packages/coverage
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: windows
    | X-Pub-Command: upgrade
    | X-Pub-Session-ID: F32DBB0F-D776-4993-8698-471F5E37AB02
    | X-Pub-Reason: direct
    | user-agent: Dart pub 1.23.0-dev.11.11
SLVR: Could not get versions for coverage from hosted:
    | Got socket error trying to find package coverage at https://pub.dartlang.org.
    | 
    | package:pub/src/utils.dart 810                                                      fail
    | package:pub/src/source/hosted.dart 324                                              BoundHostedSource._throwFriendlyError
    | package:pub/src/source/hosted.dart 139                                              BoundHostedSource.doGetVersions
    | package:pub/src/source.dart 165                                                     BoundSource.getVersions
```
Everything else is the same though: `pub` pretends to be successful without printing an error (unless you use `-v`) and no `.packages` file is written out.

**Comment by goderbauer** [comment] 2017-05-18 17:41
This error is happening on cutting edge Dart 1.24.0-dev.4.2 and also on some older versions I tested.

BTW, the same erroneous behavior can also be observed if `--verbosity=error` is dropped and I just execute `pub upgrade`.

**Comment by nex3** [comment] 2017-05-22 21:08
I can't reproduce this on Linux. If I force a `SocketException` for HTTP requests to the hosted server, I see that error printed as expected an an exit code of 69, indicating an unavailable service.

Could this have to do with the pub cache somehow? Does this reproduce on a clean Dart installation?

**Comment by goderbauer** [comment] 2017-05-23 09:04
As stated in the original post, I am observing this faulty behavior on **WINDOWS**. Linux seems fine. The issue also stays the same no matter if I blow away the pub cache or not.

**Comment by nex3** [comment] 2017-05-24 20:54
> As stated in the original post, I am observing this faulty behavior on **WINDOWS**.

Please be patient; you didn't mention whether you'd tested on other operating systems, and it's important for me to understand the scope of the bug.

I've tried reproducing on Windows using Dart 1.23.0 and pub f1e1e006768be366c85fdfe8f937d21b235af22 (the last revision compatible with 1.23.0) by forcing a `SocketException` for the HTTP request in question, but I was unsuccessful. It printed the error and produced an exit code of "false" as expected.

Can you provide me a set of reproduction steps that works on a clean Windows machine? To simulate the exception, just add `throw new io.SocketError("oh no")` above [this line](https://github.com/dart-lang/pub/blob/master/lib/src/source/hosted.dart#L136).

**Comment by goderbauer** [comment] 2017-05-25 01:43
Here  are the steps to reproduce on a clean Windows that has never seen Dart before:
* Download the latest dart from https://storage.googleapis.com/dart-archive/channels/dev/release/1.24.0-dev.6.0/sdk/dartsdk-windows-ia32-release.zip.
* Unzip it into a folder.
* In an empty folder create a `pubspec.yaml` with the following content:
```yaml
name: flutter_tools
description: Tools for building Flutter applications
homepage: http://flutter.io
author: Flutter Authors <flutter-dev@googlegroups.com>

environment:
  sdk: '>=1.19.0 <2.0.0'

dependencies:
  http: ^0.11.3+12
  intl: '>=0.14.0 <0.15.0'
  json_rpc_2: ^2.0.0
  json_schema: 1.0.6
  linter: 0.1.31
  meta: ^1.0.5
  mustache: ^0.2.5
  package_config: '>=0.1.5 <2.0.0'
  platform: 2.1.0
  process: 2.0.3
  quiver: ^0.24.0
  stack_trace: ^1.4.0
  usage: ^3.0.1
  vm_service_client: '0.2.2+4'
  web_socket_channel: ^1.0.4
  xml: ^2.4.1
  yaml: ^2.1.3
```
* Disconnect from the internet (e.g. disconnect from WiFi, remove Ethernet cord etc).
* Run `pub get` from the previously downloaded Dart sdk in the newly created folder with the `pubspec.yaml`
* See the following console output:
```
C:\Users\goderbauer\Downloads\foo> ..\dart-sdk\bin\pub.bat get
Resolving dependencies...
C:\Users\goderbauer\Downloads\foo> echo $LASTEXITCODE
0
```
* Notice the successful exit code above. However, no `.packages` file has been created.

That's the bug I am seeing. Now, here is where it gets interesting: When I actually remove one dependency (let's say `http`, but it doesn't seem to matter which one) from the `pubspec.yaml` it actually works as expected:

```
C:\Users\goderbauer\Downloads\foo> ..\dart-sdk\bin\pub.bat get
Resolving dependencies...
Could not resolve URL "https://pub.dartlang.org".
C:\Users\goderbauer\Downloads\foo> echo $LASTEXITCODE
69
C:\Users\goderbauer\Downloads\foo>
```

**Comment by goderbauer** [comment] 2017-05-25 02:18
FWIW, I just tried the same steps on a Mac (with the SDK downloaded from https://storage.googleapis.com/dart-archive/channels/stable/release/1.23.0/sdk/dartsdk-macos-x64-release.zip, the Mac had Dart installed before) and I am also getting strange behavior when I disconnect from the internet: 

If I leave the `pubspec.yaml` file as posted in the previous message, `pub get` gets stuck at the "Resolving dependencies..." stage without making progress (well, the timer is still counting up). I killed it after 5 minutes.

When I remove one dependency from the file (I removed `http`) it's working as expected:
```
~/Downloads/foo $ ../dart-sdk/bin/pub get
Resolving dependencies... 
Could not resolve URL "https://pub.dartlang.org".
~/Downloads/foo $
```

BTW, the `pubspec.yaml` I posted is a trimmed down version of what `flutter_tools` uses.

Makes me wonder if Linux actually does have a similar problem as well for this specific `pubspec.yaml`. Previously, I tested it with a dummy example on Linux which didn't show the problem.

**Comment by nex3** [comment] 2017-05-30 19:52
I need reproduction steps for the error case that don't involve physically disconnecting from the internet, if at all possible—I only have access to Windows as a remote VM, and if there's a way to disconnect it from the internet while remaining connected myself, I don't know it. Can you try forcing the issue by editing pub to manually throw the socket exception?

**Comment by goderbauer** [comment] 2017-05-30 22:44
Just disable the network adapter under Windows to disconnect it from the internet: http://internethelp.centurylink.com/internethelp/os-windows-10-network-adapter-enable.html

Also note that I've described above that a similar issue can be observed on Mac OS X. Can you reproduce that?

**Comment by goderbauer** [comment] 2017-05-30 22:58
I just tried the steps outlined above on my Linux workstation: It is showing the same faulty behavior  I documented above for Mac OS.

To summarize: The problem exists on all three platforms (Mac OS, Windows, and Linux) with the `pubspec.yaml` file quoted above. Just the faulty behavior is slightly different across the platforms: On Windows `pub get` pretends to succeed even though it doesn't. On Mac and Linux it never completes (well, I cancelled it after 2 minutes).

Can you reproduce the problem on one of these platforms with the steps I have given you in previous posts?

**Comment by nex3** [comment] 2017-06-01 01:49
Okay, I was able to reproduce on Linux, and it turns out this is actually a bug in [`http_throttle`](https://github.com/dart-lang/http_throttle). When an error occurs while *sending* a request, the throttle wrapper won't release its token. Once we get up 16 failed requests, future requests just stall out—hence your discovery that deleting any dependency makes the issue fail to reproduce.

I'm closing this issue, and I'll have a PR in `http_throttle` momentarily.

**Closed by nex3** 2017-06-01 01:49 UTC
Labels: bug, needs info

**Comment by goderbauer** [comment] 2017-06-01 02:53
Thanks for looking into it and fixing it!

**Comment by nex3** [comment] 2017-06-01 02:58
Thanks for working with me on repro instructions!
