### ISSUE TITLE
flutter create xxx

### ISSUE THREAD

**Issue by ZhangLiuCheng** [dart-lang/pub#2078] opened 2019-02-26 09:51 UTC
Running "flutter packages get" in f_test...                      
HTTP error 424: Failed Dependency
package:pub/src/http.dart 218:5                 _ThrowingClient.send
===== asynchronous gap ===========================
package:http_throttle/http_throttle.dart 33:31  ThrottleClient.send
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 301:37       BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 196:13       BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 371:48          Entrypoint._get.<fn>
===== asynchronous gap ===========================
package:pub/src/http.dart 271:51                withDependencyType
package:pub/src/entrypoint.dart 367:12          Entrypoint._get
dart:async                                      Future.wait
package:pub/src/entrypoint.dart 228:18          Entrypoint.acquireDependencies
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver.solve
dart:async                                      _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart      VersionSolver._result
This is an unexpected error. Please run
    pub --trace --verbosity=warning get --no-precompile
and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

./pub --trace --verbosity=warning get --no-precompile
Could not find a file named "pubspec.yaml" in "/Users/admin/zhangliucheng/software/flutter/bin/cache/dart-sdk/bin".
---- Log transcript ----
FINE: Pub 2.1.0-dev.9.4.flutter-f9ebf21297
ERR : Could not find a file named "pubspec.yaml" in "/Users/admin/zhangliucheng/software/flutter/bin/cache/dart-sdk/bin".
FINE: Exception type: FileException
FINE: package:pub/src/pubspec.dart 457:7       new Pubspec.load
    | package:pub/src/package.dart 127:27      new Package.load
    | package:pub/src/entrypoint.dart 153:24   new Entrypoint.current
    | package:pub/src/command.dart 31:59       PubCommand.entrypoint
    | package:pub/src/command/get.dart 41:12   GetCommand.run
    | package:args/command_runner.dart 194:27  CommandRunner.runCommand
    | ===== asynchronous gap ===========================
    | dart:async                               _AsyncAwaitCompleter.completeError
    | package:args/command_runner.dart         CommandRunner.runCommand
---- End log transcript ----

**Comment by zoechi** [comment] 2019-02-26 10:07
Possible duplicate of https://github.com/flutter/flutter/issues/28498

**Comment by jonasfj** [comment] 2019-03-04 20:11
Please reopen if this is still an issue, it looks like the issues that the Chinese community mirror had...

**Closed by jonasfj** 2019-03-04 20:11 UTC
