### ISSUE TITLE
allow to configure a transformer to only run for dart2js

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub#1338] opened 2015-10-01 08:29 UTC
> We currently don't have a way for the transformer to know if it is running for dartium (no need to transform) or for dart2js (need to transform). So currently to run with the mirror-based version you need to manually disable the transformer.
It would preferably work like the dart2js transformer, but I think that behavior is hardcoded into pub for that specific transformer. I would be happy to learn otherwise though.

https://github.com/dart-lang/polymer-dart/issues/600#issuecomment-144650654

**Comment by nex3** [comment] 2015-10-01 20:34
Duplicate of dart-lang/barback#50.

**Closed by nex3** 2015-10-01 20:34 UTC
