### ISSUE TITLE
[linux] pub global activateis not work

### ISSUE THREAD

**Issue by a-siva** [dart-lang/pub#2440] opened 2020-04-07 16:56 UTC
@godot0413301 commented on [Mon Apr 06 2020](https://github.com/dart-lang/sdk/issues/41364)

```bash
flutter@flutter-System-Product-Name:~$aqueduct
aqueduct：未找到命令
```
I input ```pub global activate aqueduct``` and input ```aqueduct``` do not work,I see this is no dir "$HOME/.pub-cache/bin" in "$HOME/.pub-cache"
but in project,run ```pub run  aqueduct``` is work

My os is ubuntu1804, the ~/.profile is like this
```bash
export PATH="$PATH:/home/flutter/development/flutter/bin"
export PATH="$PATH:/home/flutter/development/flutter/bin/cache/dart-sdk/bin"
export PUB_HOSTED_URL=https://mirrors.tuna.tsinghua.edu.cn/dart-pub
export FLUTTER_STORAGE_BASE_URL=https://mirrors.tuna.tsinghua.edu.cn/flutter
```
This tracker is for issues related to:

Dart VM

Flutter: https://github.com/flutter/flutter

 Dart SDK Version (`dart --version`):
Dart VM version: 2.7.0 (Fri Dec 6 16:26:51 2019 +0100) on "linux_x64"
I am using ubuntu18.04lts

**Comment by natebosch** [comment] 2020-04-07 17:41
What output do you get after `pub global activate aqueduct`?

**Comment by godot0413301** [comment] 2020-04-08 01:23
```flutter@flutter-System-Product-Name:~$ pub global activate aqueduct
Package aqueduct is currently active at version 3.2.1.
Resolving dependencies... (6.9s)
+ analyzer 0.35.4 (0.39.6 available)
+ aqueduct 3.2.1
+ args 1.6.0
+ async 2.4.1
+ charcode 1.1.3
+ codable 1.0.0
+ collection 1.14.12
+ convert 2.1.1
+ crypto 2.1.4
+ front_end 0.1.14 (0.1.29 available)
+ glob 1.2.0
+ isolate_executor 2.0.2+3
+ js 0.6.1+1
+ kernel 0.3.14 (0.3.29 available)
+ logging 0.11.4
+ meta 1.1.8
+ node_interop 1.0.3
+ node_io 1.0.1+2
+ open_api 2.0.1
+ package_config 1.9.3
+ password_hash 2.0.0
+ path 1.6.4
+ pedantic 1.9.0
+ postgres 1.0.2 (2.1.0 available)
+ pub_cache 0.2.3
+ pub_semver 1.4.4
+ safe_config 2.0.2 (3.0.0-b2 available)
+ source_span 1.7.0
+ string_scanner 1.0.5
+ term_glyph 1.1.0
+ typed_data 1.1.6
+ watcher 0.9.7+14
+ yaml 2.2.0
Precompiling executables... (9.9s)
Precompiled aqueduct:aqueduct.
Activated aqueduct 3.2.1.
```
It is very strange.Because I saw dart.cn,it says 
```
平台 | 缓存位置
macOS or Linux | $HOME/.pub-cache/bin
```
I also saw the issues [#33256](https://github.com/dart-lang/pub/pull/1911) .It says  ```export PATH="$PATH:$HOME/.pub-cache/bin"```.They are the same,but I cannot find ```~/.pub-cache/bin``` in my ubuntu18.04lts

**Comment by natebosch** [comment] 2020-04-08 04:01
Yes I would expect `~/.pub-cache/bin` to exist after running that command. I'm not sure why that directory wouldn't be created.

**Comment by godot0413301** [comment] 2020-04-08 04:04
I think even I created ``` ~/.pub-cache/bin``` ,other developer also will meat this bug

**Comment by godot0413301** [comment] 2020-07-02 12:06
I tried dart.cn,It works.

**Comment by sigurdm** [comment] 2023-01-26 10:03
Closing as duplicate of: https://github.com/dart-lang/pub/issues/2296 (I believe this is fixed in new dart sdks)

**Closed by sigurdm** 2023-01-26 10:03 UTC
Labels: needs info
