### ISSUE TITLE
Issue with pub publish 

### ISSUE THREAD

**Issue by eernstg** [dart-lang/pub#2410] opened 2020-03-27 12:38 UTC
While publishing a new version of reflectable, the following issue arose:

```
The method 'toList' was called on null.
Receiver: null
Tried calling: toList()
dart:core                                                         Object.noSuchMethod
package:analyzer/src/dart/analysis/file_state.dart 936:51         FileSystemState.getFilesForPath
package:analyzer/src/dart/analysis/file_tracker.dart 232:40       FileTracker.verifyApiSignature.<fn>
package:analyzer/src/dart/analysis/performance_logger.dart 34:15  PerformanceLog.run
package:analyzer/src/dart/analysis/file_tracker.dart 223:20       FileTracker.verifyApiSignature
package:analyzer/src/dart/analysis/driver.dart 924:35             AnalysisDriver.parseFileSync
package:analyzer/src/dart/analysis/session.dart 153:20            AnalysisSessionImpl.getParsedUnit
```

[pub-publish.log](https://github.com/dart-lang/pub/files/4393502/pub-publish.log)

**Comment by eernstg** [comment] 2020-03-27 12:47
The same issue exists in a completely fresh clone of the repository, as well as in a fresh clone where `pub get` was executed.

**Comment by lrhn** [comment] 2020-03-27 12:51
Try removing your pubspec.lock.

**Comment by eernstg** [comment] 2020-03-27 12:51
In the first run in the fresh clone of the repo there was no pubspec.lock.

**Comment by eernstg** [comment] 2020-03-27 12:54
Ironically, the fact that this `publish` operation is motivated by the need to eliminate the dependency on `package_resolver` may be connected: It's all about new ways to handle packages, so now we can't handle packages. ;-)

**Comment by sigurdm** [comment] 2020-03-27 12:56
I'm on this.

In the interim you can try publishing with pub from 2.7 it should work.

**Comment by sigurdm** [comment] 2020-03-27 12:57
Seems to be a duplicate of https://github.com/dart-lang/pub/issues/2407

**Closed** 2020-03-27 12:57 UTC

**Comment by eernstg** [comment] 2020-03-27 13:02
Indeed, it worked to publish using a `pub` version 2.7-dev.2.1. Thanks!
