### ISSUE TITLE
Unclear message for missing dependencies in pubspec

### ISSUE THREAD

**Issue by icatalud** [dart-lang/pub#2170] opened 2019-07-12 22:26 UTC
- Pub 2.4.0
- OS version: Windows 10 Home

pub gives a wrong suggestion, which I suspect occurs because the internals that detect which packages are being used or not does not take into account annotations. In this particular case I'm using annotations from the package meta.

> Suggestions:
> * line 1, column 1 of lib\src\mixins.dart: This package doesn't depend on meta.
>     ╷
>   1 │ import 'package:meta/meta.dart';
>     │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by natebosch** [comment] 2019-07-17 00:08
The suggestion is not to remove the import, it's to add a dependency in `pubspec.yaml`. If anything we can make the message more clear here. It's not a bug.

**Comment by natebosch** [comment] 2019-07-17 00:09
@icatalud - the immediate solution to your problem is to add `meta` in the `dependencies` section of your `pubspec.yaml`

**Comment by icatalud** [comment] 2019-07-17 01:06
you are right, that worked. Thanks.

**Comment by jonasfj** [comment] 2019-07-17 09:35
> If anything we can make the message more clear here. It's not a bug.

Good catch :)

**Comment by sigurdm** [comment] 2024-03-12 14:39
This was fixed in https://github.com/dart-lang/pub/pull/2203

**Closed by sigurdm** 2024-03-12 14:39 UTC
Labels: type-enhancement
