### ISSUE TITLE
Authentication error (403)

### ISSUE THREAD

**Issue by mrsaeedi** [dart-lang/pub#3726] opened 2023-01-06 18:56 UTC
_Hi, 
I recently got this error when running_ **`flutter pub get`** _when the two packages I marked in the image are present in_ **pubspec.yaml**
_This error did not exist when I was adding these packages, this error appeared when I recently used_ **flutter clean**.
_Also, I used vpn but it still didn't work_

![Screenshot (45)](https://user-images.githubusercontent.com/84645441/211077746-7e1d200b-0d78-454b-ac55-8c361d82f3cb.png)

_the_ **pubspec.yaml** _image and the two packages that caused the error._ (I need these two packages and I have used them in the program and I cannot delete them)

![Screenshot (44)](https://user-images.githubusercontent.com/84645441/211076971-41b53aa4-2774-46df-9458-87bdd2be8428.jpg)

**Comment by sigurdm** [comment] 2023-01-12 10:16
Closing as duplicate of https://github.com/dart-lang/pub/issues/3712

**Closed by sigurdm** 2023-01-12 10:16 UTC
