### ISSUE TITLE
When publishing flutter library, I get Bad state: Unable to find the context

### ISSUE THREAD

**Issue by luanpotter** [dart-lang/pub#2087] opened 2019-02-28 14:19 UTC
I'm having a very weird error when trying to publish (dry run) my package in the latest versions of flutter. This error occurs on `beta`, `dev` and `master` channels, and only `stable` works (for now). So far I've been switching to `stable` to deploy, and then switching back, but I'm afraid stable will move on and this error will be then omnipresent.

The error is on my example folder files: `Bad state: Unable to find the context to /home/luan/projects/flutter/audioplayers/example/lib/player_widget.dart`.

I get this error on several machines I tested, all running Arch (up to date). Sometimes, though, the error is on the other file in the example folder (could not find a pattern, but seems to be consistent within the same machine).

If I remove the example folder entirely, the dry run works flawlessly. But then I don't want to remove the dry-run and actually deploy missing the example!

I have little idea of what is causing this, but the full log follows bellow.

The project is the [audioplayers plugin](https://github.com/luanpotter/audioplayers), you can reproduce by simply cloning and trying to dry-run the deploy. It's been like that for several versions now.

By dry-running the deploy I mean the following command: `flutter packages pub publish --dry-run`.

The logs:

```
[luan@aurora audioplayers]$ flutter packages pub publish --dry-run
Publishing audioplayers 0.10.0 to https://pub.dartlang.org:
|-- .gitignore
|-- CHANGELOG.md
|-- LICENSE.md
|-- README.md
|-- analysis_options.yaml
|-- android
|   |-- .gitignore
|   |-- build.gradle
|   |-- gradle.properties
|   |-- settings.gradle
|   '-- src
|       '-- main
|           |-- AndroidManifest.xml
|           '-- java
|               '-- xyz
|                   '-- luan
|                       '-- audioplayers
|                           |-- AudioplayersPlugin.java
|                           |-- Player.java
|                           |-- ReleaseMode.java
|                           |-- WrappedMediaPlayer.java
|                           '-- WrappedSoundPool.java
|-- doc
|   |-- .gitignore
|   '-- audio_cache.md
|-- example
|   |-- .gitignore
|   |-- README.md
|   |-- android
|   |   |-- .gitignore
|   |   |-- app
|   |   |   |-- build.gradle
|   |   |   '-- src
|   |   |       '-- main
|   |   |           |-- AndroidManifest.xml
|   |   |           |-- java
|   |   |           |   '-- xyz
|   |   |           |       '-- luan
|   |   |           |           '-- audioplayers_example
|   |   |           |               '-- MainActivity.java
|   |   |           '-- res
|   |   |               |-- mipmap-hdpi
|   |   |               |   '-- ic_launcher.png
|   |   |               |-- mipmap-mdpi
|   |   |               |   '-- ic_launcher.png
|   |   |               |-- mipmap-xhdpi
|   |   |               |   '-- ic_launcher.png
|   |   |               |-- mipmap-xxhdpi
|   |   |               |   '-- ic_launcher.png
|   |   |               '-- mipmap-xxxhdpi
|   |   |                   '-- ic_launcher.png
|   |   |-- build.gradle
|   |   |-- gradle.properties
|   |   '-- settings.gradle
|   | (9 more...)
|   |-- tab2s.jpg
|   |-- tab3.jpg
|   '-- tab3s.jpg
|-- ios
|   |-- .gitignore
|   |-- Classes
|   |   |-- AudioplayersPlugin.h
|   |   '-- AudioplayersPlugin.m
|   '-- audioplayers.podspec
|-- lib
|   |-- audio_cache.dart
|   '-- audioplayers.dart
|-- pubspec.yaml
|-- scripts
|   '-- build.sh
'-- test
    |-- assets
    |   '-- audio.mp3
    |-- audio_cache_test.dart
    '-- audioplayers_test.dart
Bad state: Unable to find the context to /home/luan/projects/flutter/audioplayers/example/lib/player_widget.dart
package:pub/src/dart.dart 146:5                            AnalysisContextManager._getExistingSession
package:pub/src/dart.dart 112:23                           AnalysisContextManager.parse
package:pub/src/dart.dart 127:16                           AnalysisContextManager.parseImportsAndExports
package:pub/src/validator/strict_dependencies.dart 40:36   StrictDependenciesValidator._findPackages
dart:core                                                  _SyncIterator.moveNext
package:pub/src/validator/strict_dependencies.dart 102:12  StrictDependenciesValidator._validateBenchmarkExampleTestTool
package:pub/src/validator/strict_dependencies.dart 77:5    StrictDependenciesValidator.validate
===== asynchronous gap ===========================
package:pub/src/validator.dart 130:64                      Validator.runAll.<fn>
dart:async                                                 Future.wait
package:pub/src/validator.dart 130:19                      Validator.runAll
package:pub/src/command/lish.dart 157:32                   LishCommand._validate
dart:async                                                 _AsyncAwaitCompleter.start
package:pub/src/command/lish.dart 156:25                   LishCommand._validate
package:pub/src/command/lish.dart 137:15                   LishCommand.run
dart:async                                                 _AsyncAwaitCompleter.start
package:pub/src/command/lish.dart 113:13                   LishCommand.run
package:args/command_runner.dart 194:27                    CommandRunner.runCommand
dart:async                                                 _AsyncAwaitCompleter.start
package:args/command_runner.dart 142:23                    CommandRunner.runCommand
package:pub/src/command_runner.dart 168:39                 PubCommandRunner.runCommand.<fn>
dart:async                                                 new Future.sync
package:pub/src/utils.dart 109:12                          captureErrors.<fn>
dart:async                                                 runZoned
package:pub/src/utils.dart 126:5                           captureErrors
package:pub/src/command_runner.dart 168:13                 PubCommandRunner.runCommand
This is an unexpected error. Please run

    pub --trace publish --dry-run

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub finished with exit code 1
```

**Comment by jonasfj** [comment] 2019-03-04 11:54
Thanks for the report, this seems like something that should be fixed :)

Based on the stack trace it's thrown somewhere in here:
 https://github.com/dart-lang/pub/blob/master/lib/src/validator/strict_dependencies.dart#L97-L107

We run a series of validations before publishing. It's one of these that has a bug. This should be investigated further, there's probably a simple fix for this.

**Comment by jonasfj** [comment] 2019-03-04 11:58
@kevmoo, I see you had a hand in writing `_validateBenchmarkExampleTestTool`, what is the motivation here?
Are examples not allowed to use packages that aren't dependencies of the top-level package?

I could imagine that `example/` contained it's own `pubspec.yaml`. In some cases a package is designed to work with other packages without those being dependencies.

**Comment by kevmoo** [comment] 2019-03-04 15:23
In general, we expect these dirs to use packages that are dev dependencies. The example dir is a special case, certainly.

**Comment by jonasfj** [comment] 2019-03-04 22:47
Closed as duplicate of https://github.com/dart-lang/pub/issues/2032.

**Comment by jonasfj** [comment] 2019-03-04 22:48
Please, re-open if I got the stack trace interpretation wrong :)

**Closed by jonasfj** 2019-03-04 22:47 UTC
Labels: bug
