### ISSUE TITLE
Feature request - pub init, install

### ISSUE THREAD

**Issue by lessonteacher** [dart-lang/pub#1413] opened 2016-04-27 03:13 UTC
Hello, 

**pub init**
I am aware that discussions have been had around the `pub init` possibility in #1110 and #1135 and probably more. However, I think the point was lost in those issues. I do not think that `pub init` should scaffold an application folder structure. The command should just create the pubspec with prompts for the minimum required fields. It should be as simple as possible for a new developer to whip out some dart file with maybe some package and run it without any need to go searching for `stagehand` or knowing all the ins and outs of the directory structure. Whilst it is understandable to promote the correct structure, I think it is more important to make the experience as quick and friendly as possible to get more interest in the language.

A user should be able to literally:

```sh
mkdir test
pub init
touch filename.dart
# add their code into it
dart filename.dart
```
Another issue argued that pub is not about scaffolding, that sounds good to me but initializing this pubspec? why not i mean it can run tests, serve files and all the rest at least it can create the file that is 
required for using any additional `pub` packages. That seems actually more appropriate than `serve`

And, I know that actually you can just run the dart file without the pubspec but this would be nice and lead to:

**pub install[--save|--save-dev]**
It would be good to be able to just run `pub install` and save the dependencies into the pubspec just like.... `npm`. 

**Finally**, I am aware that these features are just sugary changes to simplify already relatively simple steps needed to do it manually but the reason I am posting this is because I think Dart is fantastic and it needs more exposure and a larger community. Simple things like these can make all the difference so why not?

**Comment by zoechi** [comment] 2016-04-27 09:13
`pub` doesn't run tests. `pub` runs scripts from dependency or global activated packages which can be the `test` package which contains a test runner.

The creator of #1135 created https://pub.dartlang.org/packages/den which does what you want from `pub` (creating and updating `pubspec.yaml` instead of creating full project like stagehand)

**Comment by lessonteacher** [comment] 2016-04-27 09:19
Well the thing is that I won't know anything about the package without having posted this issue or reading your response. It might be true that it does that sure but why is it better for a new user to need to search and find a random package to perform functions on the `pubspec.yaml` that is used by `pub` .

**Comment by nex3** [comment] 2016-04-27 19:15
This is a duplicate of existing issues, and my opinion hasn't changed: scaffolding and pubspec modification are better handled by third-party tools.

**Closed by nex3** 2016-04-27 19:15 UTC
