### ISSUE TITLE
pub get hangs while retrieving dependecies

### ISSUE THREAD

**Issue by PStoner3** [dart-lang/pub#2262] opened 2019-11-18 18:34 UTC
# Environment

- `pub version` or `flutter pub version`: pub --version = Pub 2.5.0
- OS version: Microsoft Windows [Version 10.0.17134.1069]
- Are you using the Chinese community mirror or a corporate firewall?
I am behind a corporate firewall, but I use a local http proxy, cntlm, and I have the HTTP_PROXY, HTTPS_PROXY, and NO_PROXY environment variables set. I am not locate in China, or using a Chinese mirror

# Problem
Running pub get or flutter pub get either from the command line or from Android Studio
```
Android Studio 3.5.2
Build #AI-191.8026.42.35.5977832, built on October 30, 2019
JRE: 1.8.0_202-release-1483-b03 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```
it stalls and hangs while resolving dependencies. I am starting a new project, so my pubspec.yml file is the basic, standard version (comments have been removed):

```
name: encryption_test
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
```

Flutter doctor out put:
```
$ flutter doctor -v
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.17134.1069], locale en-US)
    • Flutter version 1.9.1+hotfix.6 at C:\Users\aa99988\development\SDKs\flutter
    • Framework revision 68587a0916 (9 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\\Users\\aa99988\\development\\SDKs\\Android\\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Users\aa99988\development\IDE\Android\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Users\aa99988\development\IDE\Android\AndroidStudio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is 127.0.0.1,localhost
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[√] Connected device (1 available)
    • SM G920V • 06157df621aa3031 • android-arm64 • Android 7.0 (API 24)

• No issues found!
```

The output of `pub get -v` is located [here](https://github.com/dart-lang/pub/files/3860058/pub_get_stall.txt)

The process seems to stall on the async package. I see there is a newer version of async (2.4.0) and I have version 2.3.0 in my cache. Running pub get --trace shows nothing. It sits on "Resolving dependencies"

```
$ ~/development/SDKs/Dart/dart-sdk/bin/pub.bat get --trace
Resolving dependencies...
```

**Comment by jonasfj** [comment] 2019-11-18 19:07
Please check if you've configured the right environment variables for your proxy:
https://dart.dev/tools/pub/troubleshoot#pub-get-fails-from-behind-a-corporate-firewall

**Comment by PStoner3** [comment] 2019-11-18 19:19
@jonasfj I stated in the initial write up that I have the required environment variables set and the flutter doctor output shows the proxy settings are correct.

**Comment by PStoner3** [comment] 2019-11-18 19:21
As an updated, I closed all instances of Android Studio (1 instance), Git for Windows (my bash command line 1 instance), and the windows command line (1 instance). I re-opened git for windows and ran the command again and it completed normally.

**Comment by jonasfj** [comment] 2019-11-18 19:26
@PStoner3, sorry, I didn't know environment variables are case-insensitive on Windows (Just did a little googling).

Still it might be worth trying lowercase `http_proxy`, etc... as `dart:io` might not know about case insensitivity on Windows (and I'm just guessing here, but the OS level APIs might be case-preserving).

**Comment by CoreyCole** [comment] 2020-01-10 01:06
I'm running pug get from hitting cmd+save in my pubspec.yaml in an AngularDart project
```yaml
name: ngdart_webrtc_demo
description: Ngdart Webrtc Demo
version: 0.0.1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  angular: 5.3.1
  firebase: 7.1.0
dev_dependencies:
  angular_test:
  build_runner:
  build_test:
  build_web_compilers:
  pageloader:
  test:
```
The pub get never finishes and I see two "dart" processes in my activity monitor with memory usage that continues to climb if I don't stop the processes. Right now one is at 2.3 GB and the other at 1.95 GB.

- MacOS 10.14.6
- Dart VM version: 2.7.0 (Fri Dec 6 16:26:51 2019 +0100) on "macos_x64"
- Pub 2.7.0

**Comment by jonasfj** [comment] 2020-01-10 17:37
@CoreyCole is this a related issue? You're on a different platform, does `pub get -v` have similar output and errors? if not please file a separate issue.

**Comment by CoreyCole** [comment] 2020-01-10 18:40
@jonasfj I think you're right it is unrelated. Mine was an infinite version solving issue. I solved it by copy pasting the pubspec versions from the AngularDart hackernews pwa.

I'm trying to reproduce what was going on but it is working fine now.

I will open another issue if it comes up again :) thank you

**Comment by u007** [comment] 2020-04-04 08:55
got infinite loop with pub 2.7.2

```
tream_channel ^1.6.0 or analyzer >=0.36.0 <0.39.0 or test_core 0.2.3 or 0.2.4 or 0.2.5 or 0.2.6 or 0.2.7
SLVR:                                                                                                                                     ! not test_core 0.2.3 or 0.2.4 or 0.2.5 or 0.2.6 or 0.2.7 is partially satisfied by not test_core <0.2.3-∞
SLVR:                                                                                                                                     ! which is caused by "test_core <0.2.3-∞ depends on stream_channel ^1.6.0"
SLVR:                                                                                                                                     ! thus: test >=0.12.0-beta.3 <1.9.3-∞ requires stream_channel ^1.6.0 or analyzer >=0.36.0 <0.39.0 or test_core 0.2.3 or 0.2.4 or 0.2.5 or 0.2.6 or 0.2.7
SLVR:                                                                                                                                     ! not test_core 0.2.3 or 0.2.4 or 0.2.5 or 0.2.6 or 0.2.7 is partially satisfied by not test_core <0.2.3-∞
SLVR:                                                                                                                                     ! which is caused by "test_core <0.2.3-∞ depends on stream_channel ^1.6.0"
SLVR:                                                                                                                                     ! thus: test >=0.12.0-beta.3 <1.9.3-∞ requires stream_channel ^1.6.0 or analyzer >=0.36.0 <0.39.0 or test_core 0.2.3 or 0.2.4 or 0.2.5 or 0.2.6 or 0.2.7
SLVR:                                                                                                                                     ! not test_core 0.2.3 or 0.2.4 or 0.2.5 or 0.2.6 or 0.2.7 is partially satisfied by not test_core <0.2.3-∞
SLVR:                                                                                                                                     ! which is caused by "test_core <0.2.3-∞ depends on stream_channel ^1.6.0"
SLVR:                                                                                                                                     ! thus: test >=0.12.0-beta.3 <1.9.3-∞ requires stream_channel ^1.6.0 or analyzer >=0.36.0 <0.39.0 or test_core 0.2.3 or 0.2.4 or 0.2.5 or 0.2.6 or 0.2.7
SLVR:                                                                                                                                     ! not test_core 0.2.3 or 0.2.4 or 0.2.5 or 0.2.6 or 0.2.7 is partially satisfied by not test_core <0.2.3-∞
SLVR:                                                                                                                                     ! which is caused by "test_core <0.2.3-∞ depends on stream_channel ^1.6.0"
SLVR:                                                                                                                                     ! thus: test >=0.12.0-beta.3 <1.9.3-∞ requires stream_channel ^1.6.0 or analyzer >=0.36.0 <0.39.0 or test_core 0.2.3 or 0.2.4 or 0.2.5 or 0.2.6 or 0.2.7
SLVR:                                                                                                                                     ! not test_core 0.2.3 or 0.2.4 or 0.2.5 or 0.2.6 or 0.2.7 is partially satisfied by not test_core <0.2.3-∞
SLVR:                                                                                                                                     ! which is caused by "test_core <0.2.3-∞ depends on stream_channel ^1.6.0"
SLVR:                                                                                                                                     ! thus: test >=0.12.0-beta.3 <1.9.3-∞ requires stream_channel ^1.6.0 or analyzer >=0.36.0 <0.39.0 or test_core 0.2.3 or 0.2.4 or 0.2.5 or 0.2.6 or 0.2.7
...
```

pubspec.yaml

```
tream_channel ^1.6.0 or analyzer >=0.36.0 <0.39.0 or test_core 0.2.3 or 0.2.4 or 0.2.5 or 0.2.6 or 0.2.7
SLVR:                                                                                                                                     ! not test_core 0.2.3 or 0.2.4 or 0.2.5 or 0.2.6 or 0.2.7 is partially satisfied by not test_core <0.2.3-∞
SLVR:                                                                                                                                     ! which is caused by "test_core <0.2.3-∞ depends on stream_channel ^1.6.0"
SLVR:                                                                                                                                     ! thus: test >=0.12.0-beta.3 <1.9.3-∞ requires stream_channel ^1.6.0 or analyzer >=0.36.0 <0.39.0 or test_core 0.2.3 or 0.2.4 or 0.2.5 or 0.2.6 or 0.2.7
SLVR:                                                                                                                                     ! not test_core 0.2.3 or 0.2.4 or 0.2.5 or 0.2.6 or 0.2.7 is partially satisfied by not test_core <0.2.3-∞
SLVR:                                                                                                                                     ! which is caused by "test_core <0.2.3-∞ depends on stream_channel ^1.6.0"
SLVR:                                                                                                                                     ! thus: test >=0.12.0-beta.3 <1.9.3-∞ requires stream_channel ^1.6.0 or analyzer >=0.36.0 <0.39.0 or test_core 0.2.3 or 0.2.4 or 0.2.5 or 0.2.6 or 0.2.7
SLVR:                                                                                                                                     ! not test_core 0.2.3 or 0.2.4 or 0.2.5 or 0.2.6 or 0.2.7 is partially satisfied by not test_core <0.2.3-∞
SLVR:                                                                                                                                     ! which is caused by "test_core <0.2.3-∞ depends on stream_channel ^1.6.0"
SLVR:                                                                                                                                     ! thus: test >=0.12.0-beta.3 <1.9.3-∞ requires stream_channel ^1.6.0 or analyzer >=0.36.0 <0.39.0 or test_core 0.2.3 or 0.2.4 or 0.2.5 or 0.2.6 or 0.2.7
SLVR:                                                                                                                                     ! not test_core 0.2.3 or 0.2.4 or 0.2.5 or 0.2.6 or 0.2.7 is partially satisfied by not test_core <0.2.3-∞
SLVR:                                                                                                                                     ! which is caused by "test_core <0.2.3-∞ depends on stream_channel ^1.6.0"
SLVR:                                                                                                                                     ! thus: test >=0.12.0-beta.3 <1.9.3-∞ requires stream_channel ^1.6.0 or analyzer >=0.36.0 <0.39.0 or test_core 0.2.3 or 0.2.4 or 0.2.5 or 0.2.6 or 0.2.7
SLVR:                                                                                                                                     ! not test_core 0.2.3 or 0.2.4 or 0.2.5 or 0.2.6 or 0.2.7 is partially satisfied by not test_core <0.2.3-∞
SLVR:                                                                                                                                     ! which is caused by "test_core <0.2.3-∞ depends on stream_channel ^1.6.0"
SLVR:                                                                                                                                     ! thus: test >=0.12.0-beta.3 <1.9.3-∞ requires stream_channel ^1.6.0 or analyzer >=0.36.0 <0.39.0 or test_core 0.2.3 or 0.2.4 or 0.2.5 or 0.2.6 or 0.2.7
```

**Comment by u007** [comment] 2020-04-04 09:02
removing build_test seems to work,
and also i found out my runner package is outdated
these works:
```
dev_dependencies:
  angel_hot: ^2.0.0
  angel_serialize_generator: ^2.5.0
  build_runner: ^1.6.2
  build_web_compilers: ^2.6.1
  angel_test: ^2.0.1
  io: ^0.3.2 # For pretty printing.
  pedantic: ^1.0.0 # Enforces Dart style conventions.
  args: ^1.5.2
```

**Comment by jonasfj** [comment] 2020-04-07 17:40
@u007 please file you concern as a separate issue. It doesn't appear relevant. Also please try Dart 2.8 dev release before filing an infinite looping bug.

**Comment by kika** [comment] 2020-08-07 16:54
@jonasfj 

I've upgraded to latest stable (1.20.1) and run into this issue too. `flutter pub get -v` outputs a gazillion lines of text from solver, then reports conflict and then it just sits there doing nothing. 
<details>
  <summary>conflict</summary>

```
[        ] SLVR:   conflict: every version of flutter_driver from sdk depends on meta 1.1.8
[        ] SLVR:   ! not meta 1.1.8 is satisfied by meta >=1.1.6 <=1.1.7
[        ] SLVR:   ! which is caused by "every version of flutter_gherkin requires meta >=1.1.6 <=1.1.7 or test_core 0.3.8 or
0.3.9 or 0.3.10 or 0.3.11 or boolean_selector ^1.0.0 or test_api 0.2.14 or 0.2.15 or 0.2.16"
[        ] SLVR:   ! thus: if flutter_driver any from sdk and flutter_gherkin any then test_core 0.3.8 or 0.3.9 or 0.3.10 or
0.3.11 or boolean_selector ^1.0.0 or test_api 0.2.14 or 0.2.15 or 0.2.16
[        ] SLVR:   ! not boolean_selector ^1.0.0 is satisfied by boolean_selector 2.0.0
[        ] SLVR:   ! which is caused by "every version of flutter_driver from sdk depends on boolean_selector 2.0.0"
[        ] SLVR:   ! thus: if flutter_driver any from sdk and flutter_gherkin any then test_core 0.3.8 or 0.3.9 or 0.3.10 or
0.3.11 or test_api 0.2.14 or 0.2.15 or 0.2.16
[        ] SLVR:   ! not test_core 0.3.8 or 0.3.9 or 0.3.10 or 0.3.11 is satisfied by not test_core >=0.3.8 <0.3.12-nullsafety
[        ] SLVR:   ! which is caused by "test_core >=0.3.8 <0.3.12-nullsafety depends on analyzer ^0.39.5"
[        ] SLVR:   ! thus: if flutter_driver any from sdk and flutter_gherkin any then test_api 0.2.14 or 0.2.15 or 0.2.16 or
analyzer ^0.39.5
[        ] SLVR:   ! not analyzer ^0.39.5 is satisfied by analyzer >=0.34.0 <0.37.0 or ^0.38.1
[        ] SLVR:   ! which is caused by "every version of functional_data_generator requires analyzer >=0.34.0 <0.37.0 or
^0.38.1"
[        ] SLVR:   ! thus: if flutter_driver any from sdk and flutter_gherkin any and functional_data_generator any then
test_api 0.2.14 or 0.2.15 or 0.2.16
[        ] SLVR:   ! not test_api 0.2.14 or 0.2.15 or 0.2.16 is satisfied by test_api 0.2.17
[        ] SLVR:   ! which is caused by "every version of flutter_driver from sdk depends on test_api 0.2.17"
[        ] SLVR:   ! thus: one of flutter_driver any from sdk or flutter_gherkin any or functional_data_generator any must be
false
[        ] SLVR:   ! flutter_driver any from sdk is satisfied by flutter_driver any from sdk
[        ] SLVR:   ! which is caused by "cuida depends on flutter_driver any from sdk"
[        ] SLVR:   ! thus: flutter_gherkin is incompatible with functional_data_generator
[        ] SLVR:   ! flutter_gherkin any is satisfied by flutter_gherkin any
[        ] SLVR:   ! which is caused by "cuida depends on flutter_gherkin any"
[        ] SLVR:   ! thus: functional_data_generator is forbidden
[        ] SLVR:   ! functional_data_generator any is satisfied by functional_data_generator any
[        ] SLVR:   ! which is caused by "cuida depends on functional_data_generator any"
[        ] SLVR:   ! thus: version solving failed
```  
</details>

Without `-v` it just silently using my CPU to heat up the room without any visible artifacts on the screen (except for the shuffling dots indicator).

`flutter pub get --trace` is no longer supported it seems.

<details>
  <summary>flutter doctor -v</summary>

[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G73, locale en-US)
    • Flutter version 1.20.1 at /Volumes/ExtStripe/Scratch/flutter
    • Framework revision 2ae34518b8 (2 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/kika/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86 • Android 5.1.1 (API 22) (emulator)
    • iPhone 5s (mobile)                 • 0B3D73C5-1448-4647-A42E-5D37434D3126 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-11-4 (simulator)

• No issues found!  
</details>

**Comment by kika** [comment] 2020-08-07 17:19
@jonasfj And it appears I can even produce a minimal repro case

<details>
  <summary>This one hangs</summary>

```yaml
name: myproject
description: MyProject

version: 1.0.1+60

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  meta: ^1.1.6
  functional_data: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  flutter_gherkin: any
  functional_data_generator: ^0.3.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
```  
</details>

<details>
  <summary>This one errors out with conflict (as expected)</summary>

```yaml
name: myproject
description: MyProject

version: 1.0.1+60

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  meta: ^1.2.2
  functional_data: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  flutter_gherkin: any
  functional_data_generator: ^0.3.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
```  
</details>

**Comment by jonasfj** [comment] 2020-08-12 11:06
@kika, I think this unrelated to this issue.

I'm going to close this issue, as we are not making progress. I suspect @PStoner3 had issues with proxy configuration, or issues with interaction between proxy and `pub`. That might be reproducible using a small `dart` program that uses `dart:io` to fetching something through the proxy. But until someone can prove that, grant access to the proxy server or similar, then I don't see us making more progress.

In the mean time, this issue has been collected unrelated comments that are better filed a separate issues. hence, I'm closing.

@PStoner3, please feel free to reopen or file a new issue if this is still a problem with latest Dart SDK. I saw some fixes go into the HTTP client a while back. Note. it might be easier to debug using a dart-sdk download, if it is some interaction between `dart:io` and the proxy server.
(also we've reworked some the HTTP logic in `pub` since this issue was filed).

**Closed by jonasfj** 2020-08-12 11:06 UTC
