### ISSUE TITLE
Command for listing packages with upgrades

### ISSUE THREAD

**Issue by feinstein** [dart-lang/pub#2350] opened 2020-03-04 01:00 UTC
Let's say my pubspec.yaml has something like this:

```yaml
...
dependencies
  my_package: ^1.0
...
```

And I want to know if `my_package` has a new version available, then it would be very nice to have a tool that would print all packages that have newer versions, maybe something like:
```
pub upgrade --show-newer-versions

-my_package: 1.0 -> 1.4
```

This output could even be used by IDEs to make suggestions, just like IntelliJ IDEA does for Maven and Gradle package versions with Alt+Enter to fill the new version number automatically.

**Comment by jakemac53** [comment] 2020-03-04 14:39
This is currently being worked on here https://github.com/dart-lang/pub/pull/2315

**Comment by jakemac53** [comment] 2020-03-04 14:39
closing as a dupe of https://github.com/dart-lang/pub/issues/2140

**Closed by jakemac53** 2020-03-04 14:39 UTC

**Comment by feinstein** [comment] 2020-03-04 14:42
Thanks
