### ISSUE TITLE
This is an unexpected error. on flutter 

### ISSUE THREAD

**Issue by RNeel06** [dart-lang/pub#2910] opened 2021-03-11 06:12 UTC
Receiver: null
Tried calling: source
dart:core                                                                         Object.noSuchMethod
package:pub/src/global_packages.dart 287:21                                       GlobalPackages._describeActive
package:pub/src/global_packages.dart 179:7                                        GlobalPackages._installInCache
package:pub/src/global_packages.dart 120:11                                       GlobalPackages.activateHosted
package:pub/src/command/global_activate.dart 118:24                               GlobalActivateCommand.runProtected
dart:async                                                                        new Future.sync
package:pub/src/utils.dart 113:12                                                 captureErrors.wrappedCallback
dart:async                                                                        runZonedGuarded
package:pub/src/utils.dart 130:5                                                  captureErrors
package:pub/src/command.dart 164:13                                               PubCommand.run
package:args/command_runner.dart 196:27                                           CommandRunner.runCommand
package:dartdev/dartdev.dart 199:30                                               DartdevRunner.runCommand
package:args/command_runner.dart 112:25                                           CommandRunner.run.<fn>
dart:async                                                                        new Future.sync
package:args/command_runner.dart 112:14                                           CommandRunner.run
package:dartdev/dartdev.dart 53:29                                                runDartdev
C:\b\s\w\ir\cache\builder\src\third_party\dart\pkg\dartdev\bin\dartdev.dart 11:9  main

**Comment by sigurdm** [comment] 2021-03-11 09:35
What version of flutter are you on? (output of `flutter doctor`)

**Comment by sigurdm** [comment] 2021-03-19 13:13
Closing as a duplicate of: https://github.com/dart-lang/pub/issues/2750

We still need a good way to replicate.

**Closed by sigurdm** 2021-03-19 13:13 UTC
