### ISSUE TITLE
403 in pub get

### ISSUE THREAD

**Issue by F-shariat** [dart-lang/pub#3712] opened 2022-12-22 09:26 UTC
[pub_log.txt](https://github.com/dart-lang/pub/files/10285591/pub_log.txt)

**Comment by sigurdm** [comment] 2022-12-22 09:49
I believe this error could be related to location-based internet blocking.

We will have a better error message for this in coming releases.

You can consider trying the chinese community mirror: https://docs.flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site .

Closing as a duplicate of https://github.com/dart-lang/pub/issues/3662

**Closed by sigurdm** 2022-12-22 09:49 UTC
