### ISSUE TITLE
Fastest way to check if we need to run `pub get` ?

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub#1357] opened 2015-11-11 04:19 UTC
From our customer: "if i want to tell programmatically whether i need to run pub get, do i just compare pubspec.yaml to pubspec.lock and run pub get if the lock file is older?"

Thanks for your insight here!

**Comment by sethladd** [comment] 2015-11-11 04:19
cc @hixie

**Comment by zoechi** [comment] 2015-11-11 06:13
This might result in false positives. To be sure you would need to check if the versions in pubspec.lock still fulfill all constraints in pubspec.yaml and if all dependencies in pubspec.yaml are listed in pubspec.lock. Probably also if the package name didn't change. 
pubspec.yaml changes could be only spaces or transformer config,... which wouldn't require to rerun pub get.

**Comment by Hixie** [comment] 2015-11-11 18:08
False positives are fine for this use case, it's false negatives I'm worried about.

**Comment by zoechi** [comment] 2015-11-11 18:16
You also might check if the `.packages` file exists.
Otherwise the check mentioned by @sethladd should work fine. This is what `pub serve` did until recently (then it was changed because false positives caused issues).
`pub upgrade` is another story but I assume this isn't relevant here.

**Comment by nex3** [comment] 2015-11-16 22:28
To do this in a 100% accurate way, you really have to just run `pub get`. A full version resolution is the only way to know for sure whether the current constraints are still valid, especially given that external factors like the SDK version may have changed.

If you just want something very fast, you could use a simpler form of [the logic pub uses](https://github.com/dart-lang/pub/blob/master/lib/src/entrypoint.dart#L412-L450) to determine whether to print an out-of-date error for `pub run` and similar commands:

* If `pubspec.lock` or `.packages` don't exist, you're definitely not up-to-date.
* If `pubspec.lock` was modified more recently than `pubspec.yaml`, you may not be up-to-date.
* If `.packages` was modified more recently than `pubspec.lock`, you may not be up-to-date.

This will provide *a lot* of false positives, though—when we just had the logic above, users had a lot of pain when they made non-dependency changes to their pubspecs.

We could theoretically add a flag to `pub get` to do this, but that would also be pretty slow. The overhead of starting pub is around 250ms on my machine, and there would be more on top of that for parsing and checking a bunch of files.

**Comment by Hixie** [comment] 2015-11-17 00:04
What I'm trying to do is avoid the 250ms pub start overhead when you haven't changed anything, but run pub get whenever there's something to update. We have pubspec.yaml files with path dependencies (it's the Flutter repository), so at a minimum we'd have to follow all the local links in the current .packages file to see if they're up to date as well.

The problem is that when you haven't run pub get but should have, the failure modes are really unpredictable and confusing (all the way from immediate but very confusing error messages, up to things appearing to run but having bugs that have already been fixed).

Currently we've gone the route of just not bothering to try to catch this. When we get weird errors, our first response is "have you tried running `dart flutter/dev/update_packages.dart`" (that's our script that runs pub get in every directory we have a pubspec.yaml in -- it takes a while to run).

**Comment by nex3** [comment] 2015-12-04 22:13
Sorry we don't have a more reliable way of doing this :-/. I'm closing this out, though, since I don't really have a better answer to the question than the one I've provided.

**Closed by nex3** 2015-12-04 22:13 UTC
Labels: question
