### ISSUE TITLE
Confusing error message if JS was also compiled manually, after pub build

### ISSUE THREAD

**Issue by sethladd** [dart-lang/pub#1315] opened 2015-08-17 18:29 UTC
_From @alan-knight on August 17, 2015 16:30_

If I have an index.html that refers to main.dart, and at some point for debugging purposes I just ran dart2js manually and named the output main.dart.js, then if I later try to run pub build, I get the error

Build error:
Transforms {Dart2JS on BasicWeb|web/main.dart} all emitted asset BasicWeb|web/main.dart.js.

which is not very clear.

_Copied from original issue: dart-lang/sdk#24108_

**Comment by nex3** [comment] 2015-08-17 20:21
Duplicate of dart-lang/barback#18.

**Closed by nex3** 2015-08-17 20:21 UTC
