### ISSUE TITLE
cant get packages from pub.dev (server is not accessible from Egypt ) 

### ISSUE THREAD

**Issue by maxzod** [dart-lang/pub#3849] opened 2023-03-26 10:24 UTC
# Environment

- Dart version (run `dart --version`):
Dart SDK version: 2.19.4 (stable) (Tue Mar 7 09:58:46 2023 +0000) on "macos_arm64"
- OS kind and version (e.g. "Windows 10, version 1809" or "macOS 12.4"):
macos 13.2.1
- Are you using the Chinese community mirror or a corporate firewall?
- no

# Problem
it started a week ago or more 
running `flutter pub get`
```
Running "flutter pub get" in XXXXXX...
Resolving dependencies... (15.9s)
Connection closed before full header was received
pub get failed
command: "/Users/XX/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --color --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "/Users/XX/flutter",
  "PUB_ENVIRONMENT": "flutter_cli:get",
  "PUB_CACHE": "/Users/XX/.pub-cache",
}
exit code: 69
```

## Expected behavior

it load packages 
 
it might be related to https://github.com/flutter/website/issues/8446

**Comment by bonaparta13** [comment] 2023-03-26 10:32
Same here

**Comment by hatemragab** [comment] 2023-03-26 11:30
It only related to Egypt

**Comment by MosaadIbrahimB** [comment] 2023-03-26 12:16
Egypt

**Comment by KhaledElmetwaly** [comment] 2023-03-26 13:31
same here

**Comment by BaselAmin1** [comment] 2023-03-26 14:01
I have same problem

**Comment by smgr9** [comment] 2023-03-26 14:10
Please, stop this farce 
we cant resume our work

**Comment by webeasystep** [comment] 2023-03-26 14:11
The same here

**Comment by ahmedwaleed3378** [comment] 2023-03-26 14:12
🤍🙏

**Comment by moshkla** [comment] 2023-03-26 16:08
https://medium.com/@anasabdelazim602/fixed-flutter-pub-get-took-long-time-and-finished-with-b25a96714c77

**Comment by moazelsawaf** [comment] 2023-03-26 17:30
The issue has been solved and all the services are normally accessible since a couple of hours.

**Comment by sigurdm** [comment] 2023-03-27 08:56
Closing this tentatively.

Not sure we can do a lot here, and it seems to be working again now (at least for some).

**Closed by sigurdm** 2023-03-27 08:56 UTC

**Comment by minamax1994** [comment] 2023-04-03 12:02
The issue is not solved yet

**Comment by sigurdm** [comment] 2023-04-11 07:59
> The issue is not solved yet

Unfortunately there doesn't seem to be much we can do from our side to solve this. Seems to be an ISP issue.

We can only suggest trying a mirror or using a VPN.

**Comment by TeXniKK** [comment] 2023-09-21 21:05
> > The issue is not solved yet
> 
> Unfortunately there doesn't seem to be much we can do from our side to solve this. Seems to be an ISP issue.
> 
> We can only suggest trying a mirror or using a VPN.

Same happens when trying to build from Austria with probability around 60%. Host MacOS 13.4.1, no VPN, command is running from Docker Ubuntu 18.04
