### ISSUE TITLE
'pub get' with proxy gives an error for Angular2 package

### ISSUE THREAD

**Issue by iraj-jelo** [dart-lang/pub#1406] opened 2016-04-15 11:05 UTC
I have a `pubspec.yaml` with below content:
```
# #docregion
name: angular2_tour_of_heroes
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.15
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- angular2:
    platform_directives:
    - package:angular2/common.dart#COMMON_DIRECTIVES
    platform_pipes:
     - package:angular2/common.dart#COMMON_PIPES
    entry_points: web/main.dart
```
When I run `pub get` (I use proxy) in command line, get below error:
```
Resolving dependencies... 
Got dependencies!
Precompiling dependencies... 
Loading source assets... 
Loading angular2/transform/codegen, dart_to_js_script_rewriter, observe and smokLoading angular2/transform/codegen, dart_to_js_script_rewriter, observe and smokLoading angular2/transform/codegen, dart_to_js_script_rewriter, observe and smoke/src/default_transformer transformers... 
Transformer library "package:angular2/transform/codegen.dart" not found.
```
How do I fix it?

**Comment by zoechi** [comment] 2016-04-15 11:11
See also http://stackoverflow.com/questions/36643048

**Comment by nex3** [comment] 2016-04-15 19:07
Duplicate of #1397.

**Closed by nex3** 2016-04-15 19:07 UTC

**Comment by sinkevichmm** [comment] 2016-09-27 03:32
I had a similar error (Proxy with authentication).

in [quickstart](https://github.com/angular-examples/quickstart)

`Resolving dependencies...
Got dependencies!
Precompiling dependencies...
Loading source assets...
Loading angular2/transform/codegen, dart_to_js_script_rewriter, observe and smoke/src/default_transformer transformers...
Transformer library "package:angular2/transform/codegen.dart" not found.`

how to fix this?
