### ISSUE TITLE
Activating Dart DevTools

### ISSUE THREAD

**Issue by AhmedElmagdob** [dart-lang/pub#2966] opened 2021-04-20 10:46 UTC
Error running `pub global activate devtools`:
Bad state: Could not find 7zip.
package:pub/src/io.dart 885:3                _pathTo7zip.<fn>
package:pub/src/io.dart 886:3                _pathTo7zip
package:pub/src/io.dart                      _pathTo7zip
package:pub/src/io.dart 827:22               extractTarGz.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 773:12               withTempDir
===== asynchronous gap ===========================
package:pub/src/io.dart 818:25               extractTarGz
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 531:5     BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 381:7     BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/global_packages.dart 224:37  GlobalPackages._installInCache.<fn>.<fn>
===== asynchronous gap ===========================
package:pub/src/global_packages.dart 219:5   GlobalPackages._installInCache
===== asynchronous gap ===========================
package:pub/src/global_packages.dart 120:5   GlobalPackages.activateHosted
This is an unexpected error. Please run

    dart pub --trace global activate devtools

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

**Comment by sigurdm** [comment] 2021-09-16 08:44
Closing as duplicate of https://github.com/dart-lang/pub/issues/3068

**Closed by sigurdm** 2021-09-16 08:44 UTC
