### ISSUE TITLE
pub downgrade takes impossibly long for non-trivial packages

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/pub#1745] opened 2017-11-28 03:32 UTC
For example, clone and navigate to https://github.com/dart-lang/build/tree/master/build_barback

`pub downgrade` has yet to complete for me.

In a perfect world we'd want to run CI @ `pub downgrade` & `pub upgrade` to at least check the upper and lower bounds, but it doesn't seem feasible to use `pub downgrade` for any real package.

**Comment by kevmoo** [comment] 2017-11-28 03:35
Curious if @nex3 solver work will help here...

**Comment by nex3** [comment] 2017-11-28 20:12
Yeah, this is a symptom of the current solver algorithm's tendency to re-explore a bunch of the solution space when the context has changed. When you're downgrading, the oldest versions of almost every package aren't going to match your version constraints, but the solver isn't clever enough to figure out that they're hopeless so it keeps trying to slightly tweak dependencies to find one that works. I believe the new solver should help considerably here, so I'm going to mark this as a duplicate of #912.

It is worth noting that downgrading is generally harder than upgrading, though. Package authors are highly motivated to make sure the latest versions of their packages work with the latest versions of other packages in the ecosystem, but there's no similar motivation for a given package's lower bounds. Using `build_barback` as an example, it's totally possible that there are dozens of versions of `code_transformers` around the lower bound, 0.5.1, that are just totally incompatible with `analyzer` >=0.27.1.

**Closed by nex3** 2017-11-28 20:12 UTC
