### ISSUE TITLE
`pub get` ignores `packages.lock`

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub#1555] opened 2017-04-04 09:41 UTC
I updated some dependencies today but that caused my Angular2 application to fail,
therefore I reverted the change in `pubspec.yaml`, but that didn't help.

I got a lot of new errors about missing  that still `http` and `collection` 
like `boundary_characters.dart` from `http` and  `packages/collection/src/combined_wrappers/combined_map.dart` (which were added with the latest package updates which I reverted)

I then set the previous versions for these packages in  `pubspec.lock` 
and run `pub get --packages-dir` which told me that no dependencies were changed
and the symbolic link in `packages` still points to the newer version.

**Comment by nex3** [comment] 2017-05-15 22:45
I'm having a hard time understanding what's going on here. Can you provide a set of instructions that consistently causes this to reproduce?

**Comment by natebosch** [comment] 2018-08-22 23:55
Closing since this isn't reproducible. Please add a comment with repro instructions in the latest SDK if this is still a problem.

**Closed by natebosch** 2018-08-22 23:55 UTC
Labels: bug, needs info
