### ISSUE TITLE
support pub get <package>

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/pub#1466] opened 2016-11-06 00:15 UTC
I know there exists `den`, but I think it would be great if `pub` itself would support this functionality.

Having worked with `npm` and ` yarn` for the last couple of months, I just assumed that this would work:

`pub get over_react`

Having to manually check what the latest version of the package is, feels meh to me.

**Comment by sandrobilbeisi** [comment] 2016-11-06 18:27
try "pub cache add"

> pub cache add \<package> [--version \<constraint>] [--all]

reference : https://www.dartlang.org/tools/pub/cmd/pub-cache

example:

> pub cache add over_react: --version "^1.2.0"

**Comment by zoechi** [comment] 2016-11-06 20:47
That just downloads it to the cache but doesn't add it to the pubspec.yaml. 
@kasperpeulen I think there was as similar request already but declined. Did you search the issues?

**Comment by nex3** [comment] 2016-11-07 22:11
Duplicate of #1413, among others.

**Closed by nex3** 2016-11-07 22:11 UTC
