### ISSUE TITLE
Pub fails to obey https_proxy 

### ISSUE THREAD

**Issue by Colton127** [dart-lang/pub#3437] opened 2022-05-26 22:20 UTC
Environment

- Version: 2.17.1
- OS version: Windows 11
- Are you using the Chinese community mirror or a corporate firewall? No

Problem: "Pub Get" ignores http_proxy and https_proxy environment variables on Windows 11.

I am following this tutorial: https://dart.dev/tools/pub/troubleshoot

For troubleshooting purposes, I have setup a HTTP/HTTPS proxy on an Android device using an app called "Every Proxy". The HTTP/HTTPS proxy has been tested in Mozilla Firefox. The app accurately updates received and sent data usage. 

I ran the following command in PowerShell with administrator privileges:
`$Env:https_proxy="192.168.99.167:8080"`

I then ran flutter pub get (tried numerous projects).

There is no connection made to the HTTP/HTTPS proxy at all, meaning pub get is outright ignoring it.

**Comment by sigurdm** [comment] 2022-05-31 12:02
Duplicate of https://github.com/dart-lang/pub/issues/3437

**Closed by sigurdm** 2022-05-31 12:02 UTC
