### ISSUE TITLE
pub global activate fails if path passed

### ISSUE THREAD

**Issue by bsutton** [dart-lang/pub#3583] opened 2022-10-01 22:37 UTC
# Environment
dart --version
Dart SDK version: 2.18.2 (stable) (Tue Sep 27 13:24:11 2022 +0200) on "linux_x64"

So probably not a critical issue but.

I've just tried to globally activate a package from source.

What I meant to type was:

dart pub global activate -spath ~/git/dcli/dcli

What I actually typed was:

dart pub global activate  ~/git/dcli/dcli

Note the missing -spath

The result was:

```
dart pub global activate ~/git/dcli/dcli
Null check operator used on a null value
package:pub/src/global_packages.dart 294:37                    GlobalPackages._describeActive
package:pub/src/global_packages.dart 198:34                    GlobalPackages._installInCache
package:pub/src/global_packages.dart 141:11                    GlobalPackages.activateHosted
package:pub/src/command/global_activate.dart 129:24            GlobalActivateCommand.runProtected
package:pub/src/command.dart 189:45                            PubCommand.run.<fn>
dart:async                                                     new Future.sync
package:pub/src/utils.dart 109:12                              captureErrors.wrappedCallback
dart:async                                                     runZonedGuarded
package:pub/src/utils.dart 126:5                               captureErrors
package:pub/src/command.dart 189:13                            PubCommand.run
package:args/command_runner.dart 209:27                        CommandRunner.runCommand
package:dartdev/dartdev.dart 231:30                            DartdevRunner.runCommand
package:args/command_runner.dart 119:25                        CommandRunner.run.<fn>
dart:async                                                     new Future.sync
package:args/command_runner.dart 119:14                        CommandRunner.run
package:dartdev/dartdev.dart 66:29                             runDartdev
/b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart 11:9  main
This is an unexpected error. The full log and other details are collected in:

    /home/bsutton/.pub-cache/log/pub_log.txt

Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.
```

The log file is attached.
[pub_log.txt](https://github.com/dart-lang/pub/files/9691301/pub_log.txt)

**Comment by sigurdm** [comment] 2023-09-15 08:22
Seeing now, this is a duplicate of https://github.com/dart-lang/pub/issues/2125 which has been fixed.

**Closed by sigurdm** 2023-09-15 08:22 UTC
Labels: type-bug
