### ISSUE TITLE
Authentication error (403)

### ISSUE THREAD

**Issue by Parisa67** [dart-lang/pub#3748] opened 2023-01-25 06:56 UTC
when I want get package  time_change_detector: ^0.0.2,
but for another ackage is ok
I see this Error:
Authentication error (403)
package:pub/src/authentication/client.dart 95:5    _AuthenticatedClient._throwAuthException
package:pub/src/authentication/client.dart 60:9    _AuthenticatedClient.send
===== asynchronous gap ===========================
package:pub/src/authentication/client.dart 133:12  withAuthenticatedClient
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 862:22          HostedSource._download.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 886:12                     withTempDir
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 859:5           HostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 669:7           HostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/solver/result.dart 86:9            SolveResult.downloadCachedPackages.<fn>.<fn>
===== asynchronous gap ===========================
package:pub/src/solver/result.dart 85:14           SolveResult.downloadCachedPackages.<fn>
===== asynchronous gap ===========================
package:pub/src/solver/result.dart 82:5            SolveResult.downloadCachedPackages
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 332:7              Entrypoint.acquireDependencies
===== asynchronous gap ===========================
package:pub/src/command/add.dart 182:7             AddCommand.runProtected
This is an unexpected error. The full log and other details are collected in:

    C:\src\flutter\.pub-cache\log\pub_log.txt

Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.
pub finished with exit code 1

**Comment by aghilsobhan** [comment] 2023-01-25 07:36
you need vpn

**Comment by Parisa67** [comment] 2023-01-25 08:07
> you need vpn

I have vpn,I get another package easily

**Comment by sigurdm** [comment] 2023-01-26 09:45
Closing as duplicate of https://github.com/dart-lang/pub/issues/3712

**Closed by sigurdm** 2023-01-26 09:45 UTC
