### ISSUE TITLE
flutter packages get cause such issue.

### ISSUE THREAD

**Issue by edenAbdisa** [dart-lang/pub#3386] opened 2022-04-10 11:14 UTC
Resolving dependencies...
Class 'String' has no instance method 'containsKey'.
Receiver: ">=2.16.0 <3.0.0"
Tried calling: containsKey("version")
dart:core                                                        Object.noSuchMethod
package:pub/src/lock_file.dart 131:24                            LockFile._parse.<fn>
dart:collection                                                  MapMixin.forEach
package:pub/src/lock_file.dart 129:22                            LockFile._parse
package:pub/src/lock_file.dart 81:21                             new LockFile.load
package:pub/src/entrypoint.dart 96:35                            Entrypoint._loadLockFile
package:pub/src/entrypoint.dart 90:42                            Entrypoint.lockFile
package:pub/src/entrypoint.dart 259:21                           Entrypoint.acquireDependencies.<fn>
package:pub/src/entrypoint.dart 252:68                           Entrypoint.acquireDependencies.<fn>
package:pub/src/log.dart 362:18                                  progress
package:pub/src/entrypoint.dart 252:26                           Entrypoint.acquireDependencies
package:pub/src/command/get.dart 52:22                           GetCommand.runProtected
package:pub/src/command.dart 180:45                              PubCommand.run.<fn>
package:pub/src/command.dart 180:33                              PubCommand.run.<fn>
dart:async                                                       new Future.sync
package:pub/src/utils.dart 109:12                                captureErrors.wrappedCallback
dart:async                                                       runZonedGuarded
package:pub/src/utils.dart 126:5                                 captureErrors
package:pub/src/command.dart 180:13                              PubCommand.run
package:args/command_runner.dart 209:27                          CommandRunner.runCommand
package:dartdev/dartdev.dart 232:30                              DartdevRunner.runCommand
package:args/command_runner.dart 119:25                          CommandRunner.run.<fn>
dart:async                                                       new Future.sync
package:args/command_runner.dart 119:14                          CommandRunner.run
package:dartdev/dartdev.dart 67:29                               runDartdev
C:\b\s\w\ir\cache\builder\sdk\pkg\dartdev\bin\dartdev.dart 11:9  main
This is an unexpected error. Please run

    dart pub --trace pub --trace get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new

**Comment by sigurdm** [comment] 2022-05-05 09:06
I think this is a duplicate of https://github.com/dart-lang/pub/issues/3398

**Closed by sigurdm** 2022-05-05 09:06 UTC
