### ISSUE TITLE
Dry run recommended me include this logs in an issue [package djalmautil]

### ISSUE THREAD

**Issue by d-apps** [dart-lang/pub#2569] opened 2020-07-20 18:12 UTC
I just built this version on master channel and I had this error.

```
D:\Documentos\FlutterProjects\djalma_util> pub --trace publish --dry-run
Publishing djalmautil 1.0.8 to https://pub.dartlang.org:
|-- .gitignore
|-- .metadata
|-- CHANGELOG.md
|-- LICENSE
|-- README.md
|-- example
|   |-- .gitignore
|   |-- .metadata
|   |-- README.md
|   |-- android
|   |   |-- .gitignore
|   |   |-- app
|   |   |   |-- build.gradle
|   |   |   '-- src
|   |   |       |-- debug
|   |   |       |   '-- AndroidManifest.xml
|   |   |       |-- main
|   |   |       |   |-- AndroidManifest.xml
|   |   |       |   |-- kotlin
|   |   |       |   |   '-- com
|   |   |       |   |       '-- example
|   |   |       |   |           '-- example
|   |   |       |   |               '-- MainActivity.kt
|   |   |       |   '-- res
|   |   |       |       |-- drawable
|   |   |       |       |   '-- launch_background.xml
|   |   |       |       |-- mipmap-hdpi
|   |   |       |       |   '-- ic_launcher.png
|   |   |       |       |-- mipmap-mdpi
|   |   |       |       |   '-- ic_launcher.png
|   |   |       |       |-- mipmap-xhdpi
|   |   |       |       |   '-- ic_launcher.png
|   |   |       |       |-- mipmap-xxhdpi
|   |   |       |       |   '-- ic_launcher.png
|   |   |       |       |-- mipmap-xxxhdpi
|   |   |       |       |   '-- ic_launcher.png
|   |   |       |       '-- values
|   |   |       |           '-- styles.xml
|   |   |       '-- profile
|   |   |           '-- AndroidManifest.xml
|   |   |-- build.gradle
|   |   |-- gradle
|   |   |   '-- wrapper
|   |   |       '-- gradle-wrapper.properties
|   |   |-- gradle.properties
|   |   '-- settings.gradle
|   |-- ios
|   |   |-- .gitignore
|   |   |-- Flutter
|   |   |   |-- AppFrameworkInfo.plist
|   |   |   |-- Debug.xcconfig
|   |   |   '-- Release.xcconfig
|   |   |-- Runner
|   |   |   |-- AppDelegate.swift
|   |   |   |-- Assets.xcassets
|   |   |   |   |-- AppIcon.appiconset
|   |   |   |   |   |-- Contents.json
|   |   |   |   |   |-- Icon-App-1024x1024@1x.png
|   |   |   |   |   |-- Icon-App-20x20@1x.png
|   |   |   |   |   | (10 more...)
|   |   |   |   |   |-- Icon-App-76x76@1x.png
|   |   |   |   |   |-- Icon-App-76x76@2x.png
|   |   |   |   |   '-- Icon-App-83.5x83.5@2x.png
|   |   |   |   '-- LaunchImage.imageset
|   |   |   |       |-- Contents.json
|   |   |   |       |-- LaunchImage.png
|   |   |   |       |-- LaunchImage@2x.png
|   |   |   |       |-- LaunchImage@3x.png
|   |   |   |       '-- README.md
|   |   |   |-- Base.lproj
|   |   |   |   |-- LaunchScreen.storyboard
|   |   |   |   '-- Main.storyboard
|   |   |   |-- Info.plist
|   |   |   '-- Runner-Bridging-Header.h
|   |   |-- Runner.xcodeproj
|   |   |   |-- project.pbxproj
|   |   |   |-- project.xcworkspace
|   |   |   |   |-- contents.xcworkspacedata
|   |   |   |   '-- xcshareddata
|   |   |   |       |-- IDEWorkspaceChecks.plist
|   |   |   |       '-- WorkspaceSettings.xcsettings
|   |   |   '-- xcshareddata
|   |   |       '-- xcschemes
|   |   |           '-- Runner.xcscheme
|   |   '-- Runner.xcworkspace
|   |       |-- contents.xcworkspacedata
|   |       '-- xcshareddata
|   |           |-- IDEWorkspaceChecks.plist
|   |           '-- WorkspaceSettings.xcsettings
|   |-- lib
|   |   '-- main.dart
|   |-- pubspec.yaml
|   |-- test
|   |   '-- widget_test.dart
|   |-- web
|   |   |-- favicon.png
|   |   |-- icons
|   |   |   |-- Icon-192.png
|   |   |   '-- Icon-512.png
|   |   |-- index.html
|   |   '-- manifest.json
|   '-- windows
|       |-- .gitignore
|       |-- CMakeLists.txt
|       |-- flutter
|       |   |-- .template_version
|       |   |-- CMakeLists.txt
|       |   |-- generated_plugin_registrant.cc
|       |   |-- generated_plugin_registrant.h
|       |   '-- generated_plugins.cmake
|       '-- runner
|           |-- CMakeLists.txt
|           |-- Runner.rc
|           |-- flutter_window.cpp
|           | (10 more...)
|           |-- win32_window.h
|           |-- window_configuration.cpp
|           '-- window_configuration.h
|-- lib
|   |-- djalmautil.dart
|   '-- src
|       |-- color_to_materialcolor.dart
|       |-- column_builder.dart
|       |-- custom_snackbar.dart
|       |-- date_formatter.dart
|       |-- firebase_error_check.dart
|       |-- get_address.dart
|       |-- onesignal_helper.dart
|       |-- price_formatter.dart
|       |-- remove_special_characters.dart
|       '-- wrap_builder.dart
|-- pubspec.yaml
'-- test
    '-- djalmautil_test.dart
Invalid argument(s) (sdkPath): Must not be null
dart:core                                                      ArgumentError.checkNotNull
package:analyzer/src/dart/analysis/context_builder.dart 49:19  ContextBuilderImpl.createContext
package:pub/src/dart.dart 115:36                               AnalysisContextManager.createContextsForDirectory
package:pub/src/validator/strict_dependencies.dart 27:28       new StrictDependenciesValidator
package:pub/src/validator.dart 135:7                           Validator.runAll
package:pub/src/command/lish.dart 165:21                       LishCommand._validate
package:pub/src/command/lish.dart 141:15                       LishCommand.run
package:args/command_runner.dart 197:27                        CommandRunner.runCommand
package:pub/src/command_runner.dart 193:39                     PubCommandRunner.runCommand.<fn>
dart:async                                                     new Future.sync
package:pub/src/utils.dart 113:12                              captureErrors.wrappedCallback
package:stack_trace                                            Chain.capture
package:pub/src/utils.dart 126:11                              captureErrors
package:pub/src/command_runner.dart 193:13                     PubCommandRunner.runCommand
dart:async                                                     _completeOnAsyncReturn
package:pub/src/command_runner.dart                            PubCommandRunner._validatePlatform
dart:async                                                     _completeOnAsyncReturn
package:pool/pool.dart                                         Pool.withResource
dart:async                                                     _completeOnAsyncReturn
package:pub/src/io.dart                                        runProcess.<fn>
===== asynchronous gap ===========================
dart:async                                                     Future.catchError
package:pub/src/utils.dart 113:52                              captureErrors.wrappedCallback
package:stack_trace                                            Chain.capture
package:pub/src/utils.dart 126:11                              captureErrors
package:pub/src/command_runner.dart 193:13                     PubCommandRunner.runCommand
dart:async                                                     _completeOnAsyncReturn
package:pub/src/command_runner.dart                            PubCommandRunner._validatePlatform
dart:async                                                     _completeOnAsyncReturn
package:pool/pool.dart                                         Pool.withResource
dart:async                                                     _completeOnAsyncReturn
package:pub/src/io.dart                                        runProcess.<fn>
---- Log transcript ----
FINE: Pub 2.9.0-21.0.dev.flutter-9dca49e71e
IO  : Spawning "cmd /c ver" in D:\Documentos\FlutterProjects\djalma_util\.
IO  : Finished ver. Exit code 0.
    | stdout:
    | |
    | | Microsoft Windows [versÃ£o 10.0.18363.959]
    | Nothing output on stderr.
IO  : Spawning "cmd /c git --version" in D:\Documentos\FlutterProjects\djalma_util\.
IO  : Finished git. Exit code 0.
    | stdout:
    | | git version 2.22.0.windows.1
    | Nothing output on stderr.
FINE: Determined git command git.
IO  : Spawning "cmd /c git check-ignore --quiet ." in D:\Documentos\FlutterProjects\djalma_util\.
IO  : Finished git. Exit code 1.
    | Nothing output on stdout.
    | Nothing output on stderr.
IO  : Spawning "cmd /c git ls-files --cached --others --exclude-standard" in D:\Documentos\FlutterProjects\djalma_util\.
IO  : Finished git. Exit code 0.
    | stdout:
    | | .gitignore
    | | .metadata
    | | CHANGELOG.md
    | | LICENSE
    | | README.md
    | | example/.gitignore
    | | example/.metadata
    | | example/README.md
    | | example/android/.gitignore
    | | example/android/app/build.gradle
    | | example/android/app/src/debug/AndroidManifest.xml
    | | example/android/app/src/main/AndroidManifest.xml
    | | example/android/app/src/main/kotlin/com/example/example/MainActivity.kt
    | | example/android/app/src/main/res/drawable/launch_background.xml
    | | example/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
    | | example/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
    | | example/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
    | | example/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
    | | example/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
    | | example/android/app/src/main/res/values/styles.xml
    | | example/android/app/src/profile/AndroidManifest.xml
    | | example/android/build.gradle
    | | example/android/gradle.properties
    | | example/android/gradle/wrapper/gradle-wrapper.properties
    | | example/android/settings.gradle
    | | example/ios/.gitignore
    | | example/ios/Flutter/AppFrameworkInfo.plist
    | | example/ios/Flutter/Debug.xcconfig
    | | example/ios/Flutter/Release.xcconfig
    | | example/ios/Runner.xcodeproj/project.pbxproj
    | | example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
    | | example/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
    | | example/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
    | | example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
    | | example/ios/Runner.xcworkspace/contents.xcworkspacedata
    | | example/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
    | | example/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
    | | example/ios/Runner/AppDelegate.swift
    | | example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
    | | example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
    | | example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
    | | example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
    | | example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
    | | example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
    | | example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
    | | example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
    | | example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
    | | example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
    | | example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
    | | example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
    | | example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
    | | example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
    | | example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
    | | example/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
    | | example/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json
    | | example/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png
    | | example/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
    | | example/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png
    | | example/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md
    | | example/ios/Runner/Base.lproj/LaunchScreen.storyboard
    | | example/ios/Runner/Base.lproj/Main.storyboard
    | | example/ios/Runner/Info.plist
    | | example/ios/Runner/Runner-Bridging-Header.h
    | | example/lib/main.dart
    | | example/pubspec.lock
    | | example/pubspec.yaml
    | | example/test/widget_test.dart
    | | example/web/favicon.png
    | | example/web/icons/Icon-192.png
    | | example/web/icons/Icon-512.png
    | | example/web/index.html
    | | example/web/manifest.json
    | | example/windows/.gitignore
    | | example/windows/CMakeLists.txt
    | | example/windows/flutter/.template_version
    | | example/windows/flutter/CMakeLists.txt
    | | example/windows/flutter/generated_plugin_registrant.cc
    | | example/windows/flutter/generated_plugin_registrant.h
    | | example/windows/flutter/generated_plugins.cmake
    | | example/windows/runner/CMakeLists.txt
    | | example/windows/runner/Runner.rc
    | | example/windows/runner/flutter_window.cpp
    | | example/windows/runner/flutter_window.h
    | | example/windows/runner/main.cpp
    | | example/windows/runner/resource.h
    | | example/windows/runner/resources/app_icon.ico
    | | example/windows/runner/run_loop.cpp
    | | example/windows/runner/run_loop.h
    | | example/windows/runner/runner.exe.manifest
    | | example/windows/runner/utils.cpp
    | | example/windows/runner/utils.h
    | | example/windows/runner/win32_window.cpp
    | | example/windows/runner/win32_window.h
    | | example/windows/runner/window_configuration.cpp
    | | example/windows/runner/window_configuration.h
    | | lib/djalmautil.dart
    | | lib/src/color_to_materialcolor.dart
    | | lib/src/column_builder.dart
    | | lib/src/custom_snackbar.dart
    | | lib/src/date_formatter.dart
    | | lib/src/firebase_error_check.dart
    | | lib/src/get_address.dart
    | | lib/src/onesignal_helper.dart
    | | lib/src/price_formatter.dart
    | | lib/src/remove_special_characters.dart
    | | lib/src/wrap_builder.dart
    | | pubspec.lock
    | | pubspec.yaml
    | | test/djalmautil_test.dart
    | Nothing output on stderr.
FINE: Archiving and publishing djalmautil 1.0.8 (.).
MSG : Publishing djalmautil 1.0.8 to https://pub.dartlang.org:
    | |-- .gitignore
    | |-- .metadata
    | |-- CHANGELOG.md
    | |-- LICENSE
    | |-- README.md
    | |-- example
    | |   |-- .gitignore
    | |   |-- .metadata
    | |   |-- README.md
    | |   |-- android
    | |   |   |-- .gitignore
    | |   |   |-- app
    | |   |   |   |-- build.gradle
    | |   |   |   '-- src
    | |   |   |       |-- debug
    | |   |   |       |   '-- AndroidManifest.xml
    | |   |   |       |-- main
    | |   |   |       |   |-- AndroidManifest.xml
    | |   |   |       |   |-- kotlin
    | |   |   |       |   |   '-- com
    | |   |   |       |   |       '-- example
    | |   |   |       |   |           '-- example
    | |   |   |       |   |               '-- MainActivity.kt
    | |   |   |       |   '-- res
    | |   |   |       |       |-- drawable
    | |   |   |       |       |   '-- launch_background.xml
    | |   |   |       |       |-- mipmap-hdpi
    | |   |   |       |       |   '-- ic_launcher.png
    | |   |   |       |       |-- mipmap-mdpi
    | |   |   |       |       |   '-- ic_launcher.png
    | |   |   |       |       |-- mipmap-xhdpi
    | |   |   |       |       |   '-- ic_launcher.png
    | |   |   |       |       |-- mipmap-xxhdpi
    | |   |   |       |       |   '-- ic_launcher.png
    | |   |   |       |       |-- mipmap-xxxhdpi
    | |   |   |       |       |   '-- ic_launcher.png
    | |   |   |       |       '-- values
    | |   |   |       |           '-- styles.xml
    | |   |   |       '-- profile
    | |   |   |           '-- AndroidManifest.xml
    | |   |   |-- build.gradle
    | |   |   |-- gradle
    | |   |   |   '-- wrapper
    | |   |   |       '-- gradle-wrapper.properties
    | |   |   |-- gradle.properties
    | |   |   '-- settings.gradle
    | |   |-- ios
    | |   |   |-- .gitignore
    | |   |   |-- Flutter
    | |   |   |   |-- AppFrameworkInfo.plist
    | |   |   |   |-- Debug.xcconfig
    | |   |   |   '-- Release.xcconfig
    | |   |   |-- Runner
    | |   |   |   |-- AppDelegate.swift
    | |   |   |   |-- Assets.xcassets
    | |   |   |   |   |-- AppIcon.appiconset
    | |   |   |   |   |   |-- Contents.json
    | |   |   |   |   |   |-- Icon-App-1024x1024@1x.png
    | |   |   |   |   |   |-- Icon-App-20x20@1x.png
    | |   |   |   |   |   | (10 more...)
    | |   |   |   |   |   |-- Icon-App-76x76@1x.png
    | |   |   |   |   |   |-- Icon-App-76x76@2x.png
    | |   |   |   |   |   '-- Icon-App-83.5x83.5@2x.png
    | |   |   |   |   '-- LaunchImage.imageset
    | |   |   |   |       |-- Contents.json
    | |   |   |   |       |-- LaunchImage.png
    | |   |   |   |       |-- LaunchImage@2x.png
    | |   |   |   |       |-- LaunchImage@3x.png
    | |   |   |   |       '-- README.md
    | |   |   |   |-- Base.lproj
    | |   |   |   |   |-- LaunchScreen.storyboard
    | |   |   |   |   '-- Main.storyboard
    | |   |   |   |-- Info.plist
    | |   |   |   '-- Runner-Bridging-Header.h
    | |   |   |-- Runner.xcodeproj
    | |   |   |   |-- project.pbxproj
    | |   |   |   |-- project.xcworkspace
    | |   |   |   |   |-- contents.xcworkspacedata
    | |   |   |   |   '-- xcshareddata
    | |   |   |   |       |-- IDEWorkspaceChecks.plist
    | |   |   |   |       '-- WorkspaceSettings.xcsettings
    | |   |   |   '-- xcshareddata
    | |   |   |       '-- xcschemes
    | |   |   |           '-- Runner.xcscheme
    | |   |   '-- Runner.xcworkspace
    | |   |       |-- contents.xcworkspacedata
    | |   |       '-- xcshareddata
    | |   |           |-- IDEWorkspaceChecks.plist
    | |   |           '-- WorkspaceSettings.xcsettings
    | |   |-- lib
    | |   |   '-- main.dart
    | |   |-- pubspec.yaml
    | |   |-- test
    | |   |   '-- widget_test.dart
    | |   |-- web
    | |   |   |-- favicon.png
    | |   |   |-- icons
    | |   |   |   |-- Icon-192.png
    | |   |   |   '-- Icon-512.png
    | |   |   |-- index.html
    | |   |   '-- manifest.json
    | |   '-- windows
    | |       |-- .gitignore
    | |       |-- CMakeLists.txt
    | |       |-- flutter
    | |       |   |-- .template_version
    | |       |   |-- CMakeLists.txt
    | |       |   |-- generated_plugin_registrant.cc
    | |       |   |-- generated_plugin_registrant.h
    | |       |   '-- generated_plugins.cmake
    | |       '-- runner
    | |           |-- CMakeLists.txt
    | |           |-- Runner.rc
    | |           |-- flutter_window.cpp
    | |           | (10 more...)
    | |           |-- win32_window.h
    | |           |-- window_configuration.cpp
    | |           '-- window_configuration.h
    | |-- lib
    | |   |-- djalmautil.dart
    | |   '-- src
    | |       |-- color_to_materialcolor.dart
    | |       |-- column_builder.dart
    | |       |-- custom_snackbar.dart
    | |       |-- date_formatter.dart
    | |       |-- firebase_error_check.dart
    | |       |-- get_address.dart
    | |       |-- onesignal_helper.dart
    | |       |-- price_formatter.dart
    | |       |-- remove_special_characters.dart
    | |       '-- wrap_builder.dart
    | |-- pubspec.yaml
    | '-- test
    |     '-- djalmautil_test.dart
FINE: Creating .tar.gz stream containing:
    | .\.gitignore
    | .\.metadata
    | .\CHANGELOG.md
    | .\LICENSE
    | .\README.md
    | .\example\.gitignore
    | .\example\.metadata
    | .\example\README.md
    | .\example\android\.gitignore
    | .\example\android\app\build.gradle
    | .\example\android\app\src\debug\AndroidManifest.xml
    | .\example\android\app\src\main\AndroidManifest.xml
    | .\example\android\app\src\main\kotlin\com\example\example\MainActivity.kt
    | .\example\android\app\src\main\res\drawable\launch_background.xml
    | .\example\android\app\src\main\res\mipmap-hdpi\ic_launcher.png
    | .\example\android\app\src\main\res\mipmap-mdpi\ic_launcher.png
    | .\example\android\app\src\main\res\mipmap-xhdpi\ic_launcher.png
    | .\example\android\app\src\main\res\mipmap-xxhdpi\ic_launcher.png
    | .\example\android\app\src\main\res\mipmap-xxxhdpi\ic_launcher.png
    | .\example\android\app\src\main\res\values\styles.xml
    | .\example\android\app\src\profile\AndroidManifest.xml
    | .\example\android\build.gradle
    | .\example\android\gradle.properties
    | .\example\android\gradle\wrapper\gradle-wrapper.properties
    | .\example\android\settings.gradle
    | .\example\ios\.gitignore
    | .\example\ios\Flutter\AppFrameworkInfo.plist
    | .\example\ios\Flutter\Debug.xcconfig
    | .\example\ios\Flutter\Release.xcconfig
    | .\example\ios\Runner.xcodeproj\project.pbxproj
    | .\example\ios\Runner.xcodeproj\project.xcworkspace\contents.xcworkspacedata
    | .\example\ios\Runner.xcodeproj\project.xcworkspace\xcshareddata\IDEWorkspaceChecks.plist
    | .\example\ios\Runner.xcodeproj\project.xcworkspace\xcshareddata\WorkspaceSettings.xcsettings
    | .\example\ios\Runner.xcodeproj\xcshareddata\xcschemes\Runner.xcscheme
    | .\example\ios\Runner.xcworkspace\contents.xcworkspacedata
    | .\example\ios\Runner.xcworkspace\xcshareddata\IDEWorkspaceChecks.plist
    | .\example\ios\Runner.xcworkspace\xcshareddata\WorkspaceSettings.xcsettings
    | .\example\ios\Runner\AppDelegate.swift
    | .\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Contents.json
    | .\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-1024x1024@1x.png
    | .\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@1x.png
    | .\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@2x.png
    | .\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@3x.png
    | .\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@1x.png
    | .\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@2x.png
    | .\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@3x.png
    | .\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@1x.png
    | .\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@2x.png
    | .\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@3x.png
    | .\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@2x.png
    | .\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@3x.png
    | .\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@1x.png
    | .\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@2x.png
    | .\example\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-83.5x83.5@2x.png
    | .\example\ios\Runner\Assets.xcassets\LaunchImage.imageset\Contents.json
    | .\example\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage.png
    | .\example\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@2x.png
    | .\example\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@3x.png
    | .\example\ios\Runner\Assets.xcassets\LaunchImage.imageset\README.md
    | .\example\ios\Runner\Base.lproj\LaunchScreen.storyboard
    | .\example\ios\Runner\Base.lproj\Main.storyboard
    | .\example\ios\Runner\Info.plist
    | .\example\ios\Runner\Runner-Bridging-Header.h
    | .\example\lib\main.dart
    | .\example\pubspec.yaml
    | .\example\test\widget_test.dart
    | .\example\web\favicon.png
    | .\example\web\icons\Icon-192.png
    | .\example\web\icons\Icon-512.png
    | .\example\web\index.html
    | .\example\web\manifest.json
    | .\example\windows\.gitignore
    | .\example\windows\CMakeLists.txt
    | .\example\windows\flutter\.template_version
    | .\example\windows\flutter\CMakeLists.txt
    | .\example\windows\flutter\generated_plugin_registrant.cc
    | .\example\windows\flutter\generated_plugin_registrant.h
    | .\example\windows\flutter\generated_plugins.cmake
    | .\example\windows\runner\CMakeLists.txt
    | .\example\windows\runner\Runner.rc
    | .\example\windows\runner\flutter_window.cpp
    | .\example\windows\runner\flutter_window.h
    | .\example\windows\runner\main.cpp
    | .\example\windows\runner\resource.h
    | .\example\windows\runner\resources\app_icon.ico
    | .\example\windows\runner\run_loop.cpp
    | .\example\windows\runner\run_loop.h
    | .\example\windows\runner\runner.exe.manifest
    | .\example\windows\runner\utils.cpp
    | .\example\windows\runner\utils.h
    | .\example\windows\runner\win32_window.cpp
    | .\example\windows\runner\win32_window.h
    | .\example\windows\runner\window_configuration.cpp
    | .\example\windows\runner\window_configuration.h
    | .\lib\djalmautil.dart
    | .\lib\src\color_to_materialcolor.dart
    | .\lib\src\column_builder.dart
    | .\lib\src\custom_snackbar.dart
    | .\lib\src\date_formatter.dart
    | .\lib\src\firebase_error_check.dart
    | .\lib\src\get_address.dart
    | .\lib\src\onesignal_helper.dart
    | .\lib\src\price_formatter.dart
    | .\lib\src\remove_special_characters.dart
    | .\lib\src\wrap_builder.dart
    | .\pubspec.yaml
    | .\test\djalmautil_test.dart
ERR : Invalid argument(s) (sdkPath): Must not be null
FINE: Exception type: ArgumentError
ERR : dart:core                                                      ArgumentError.checkNotNull
    | package:analyzer/src/dart/analysis/context_builder.dart 49:19  ContextBuilderImpl.createContext
    | package:pub/src/dart.dart 115:36                               AnalysisContextManager.createContextsForDirectory
    | package:pub/src/validator/strict_dependencies.dart 27:28       new StrictDependenciesValidator
    | package:pub/src/validator.dart 135:7                           Validator.runAll
    | package:pub/src/command/lish.dart 165:21                       LishCommand._validate
    | package:pub/src/command/lish.dart 141:15                       LishCommand.run
    | package:args/command_runner.dart 197:27                        CommandRunner.runCommand
    | package:pub/src/command_runner.dart 193:39                     PubCommandRunner.runCommand.<fn>
    | dart:async                                                     new Future.sync
    | package:pub/src/utils.dart 113:12                              captureErrors.wrappedCallback
    | package:stack_trace                                            Chain.capture
    | package:pub/src/utils.dart 126:11                              captureErrors
    | package:pub/src/command_runner.dart 193:13                     PubCommandRunner.runCommand
    | dart:async                                                     _completeOnAsyncReturn
    | package:pub/src/command_runner.dart                            PubCommandRunner._validatePlatform
    | dart:async                                                     _completeOnAsyncReturn
    | package:pool/pool.dart                                         Pool.withResource
    | dart:async                                                     _completeOnAsyncReturn
    | package:pub/src/io.dart                                        runProcess.<fn>
    | ===== asynchronous gap ===========================
    | dart:async                                                     Future.catchError
    | package:pub/src/utils.dart 113:52                              captureErrors.wrappedCallback
    | package:stack_trace                                            Chain.capture
    | package:pub/src/utils.dart 126:11                              captureErrors
    | package:pub/src/command_runner.dart 193:13                     PubCommandRunner.runCommand
    | dart:async                                                     _completeOnAsyncReturn
    | package:pub/src/command_runner.dart                            PubCommandRunner._validatePlatform
    | dart:async                                                     _completeOnAsyncReturn
    | package:pool/pool.dart                                         Pool.withResource
    | dart:async                                                     _completeOnAsyncReturn
    | package:pub/src/io.dart                                        runProcess.<fn>
---- End log transcript ----
```

**Comment by sigurdm** [comment] 2020-07-21 08:00
Thanks for reporting!

This is a duplicate of https://github.com/dart-lang/pub/issues/2563 that was fixed yesterday.

**Closed by sigurdm** 2020-07-21 08:00 UTC
