### ISSUE TITLE
Help devs avoid circular dependencies

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/pub#1408] opened 2016-04-19 16:24 UTC
It seems that pub can hang if two generated files are depending on each other. (See https://github.com/angular/angular.io/issues/1122.)

When pub hangs, it should let you know why. It might also be good to warn the user when 2+ packages have a circular dependency on each other (even when pub doesn't hang).

Also see https://github.com/dart-lang/www.dartlang.org/issues/1567.

cc @jakemac53

**Comment by nex3** [comment] 2016-04-21 19:00
If a transformer hangs on this, it's an issue internal to that transformer; it doesn't involve the barback APIs. From barback's perspective, all transformations happen in phases, and when a transform requests an asset it gets the version of that asset produced by the previous phase. This means that if a transformer is running on two circular files in the same phase, and each file requests the other, they'll both complete quickly with the result from the previous phase.

This gets more complex with analysis resolution, but that's handled entirely outside of the barback APIs and pub has no visibility into it with which to provide warnings. This is something the angular transformers themselves will have to handle.

**Comment by jakemac53** [comment] 2016-04-21 19:19
How do transforms which are ran on different packages (which depend on each other) interact though?

For instance, if `package:a/a.generated.dart` requires `package:b/b.generated.dart` in order to be generated, but `package:b/b.generated.dart` also requires `package:a/a.generated.dart`, then wouldn't that deadlock? I think this is why the angular transformer hangs today with cyclic package dependencies.

**Comment by nex3** [comment] 2016-04-21 19:23
For that case, we do have logic to detect it and throw an error; see the two instance of `throw new CycleException()` in [`dependency_computer.dart`](https://github.com/dart-lang/pub/blob/master/lib/src/barback/dependency_computer.dart).

**Comment by jakemac53** [comment] 2016-04-21 19:34
From a quick look it appears that just detects when the transformer code itself has a dependency on a file which it itself transforms. However in the angular case the deadlock is (presumably) being caused by calls to `transform.readInputAsString` from the angular transformer in each package.

**Comment by nex3** [comment] 2016-04-21 19:56
Oh, right, sorry—I'm still foggy from my cold. That isn't something we detect right now.

**Comment by matanlurey** [comment] 2018-03-24 18:13
We are no longer supporting transformers or `pub serve/build` going forward (this tooling has moved elsewhere into the https://github.com/dart-lang/build repository and https://github.com/dart-lang/webdev CLI) so a fix for this is not planned. 

We'll be updating the tooling section of the Dart website in the coming weeks with more formal documentation on how to get started.

**Closed by matanlurey** 2018-03-24 18:13 UTC
Labels: enhancement, not planned, transformer
