### ISSUE TITLE
hello some some with flutter

### ISSUE THREAD

**Issue by KstefK** [dart-lang/pub#3508] opened 2022-08-02 13:47 UTC
pub get failed (255; .)
exit code 255

**Comment by KstefK** [comment] 2022-08-02 13:49
That comes from Visual Studio Code last stable version
My set up is MacBook Pro M1

**Comment by sigurdm** [comment] 2022-08-04 08:35
I think this is a duplicate of https://github.com/dart-lang/pub/issues/3508 .

**Closed by sigurdm** 2022-08-04 08:35 UTC
