### ISSUE TITLE
Pub global activate for dartdoc breaks on 2.0 dev SDKs

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/pub#1771] opened 2018-01-03 19:04 UTC
If I run `pub global activate dartdoc 0.15.0+1` on a recent SDK (tested on dev.8.0 and dev.14.0) it blows up with an "unexpected error".  Short error message included here, full log attached.  
[dartdoc-activate-log.txt](https://github.com/dart-lang/pub/files/1601393/dartdoc-activate-log.txt)

```
Resolving dependencies... (2.3s)
Invalid argument(s): Minimum version ("2.0.0-dev.15.0") must be less than maximum ("2.0.0-dev.8.0").
package:pub_semver/src/version_range.dart 59         new VersionRange
package:pub/src/pubspec.dart 380                     Pubspec._ensureEnvironment
package:pub/src/pubspec.dart 345                     Pubspec.dartSdkConstraint
package:pub/src/solver/backtracking_solver.dart 511  BacktrackingSolver._checkPubspecMatchesSdkConstraint
package:pub/src/solver/backtracking_solver.dart 474  BacktrackingSolver._checkVersion
===== asynchronous gap ===========================
package:pub/src/solver/backtracking_solver.dart 432  BacktrackingSolver._findValidVersion.<fn>
===== asynchronous gap ===========================
dart:async                                           Future.doWhile
package:pub/src/solver/backtracking_solver.dart 430  BacktrackingSolver._findValidVersion
package:pub/src/solver/backtracking_solver.dart 337  BacktrackingSolver._versionQueueFor
===== asynchronous gap ===========================
package:pub/src/solver/backtracking_solver.dart 290  BacktrackingSolver._solve.<fn>
===== asynchronous gap ===========================
dart:async                                           _completeOnAsyncReturn
package:pub/src/solver/backtracking_solver.dart 315  BacktrackingSolver._solve.<fn>
dart:async                                           _completeOnAsyncReturn
package:pub/src/solver/version_selection.dart 64     VersionSelection.select
dart:async                                           _completeOnAsyncReturn
package:pub/src/solver/version_selection.dart 91     VersionSelection._addDependencies
dart:async                                           _completeOnAsyncReturn
package:pub/src/solver/version_selection.dart 91     VersionSelection._addDependencies
This is an unexpected error. Please run

    pub --trace global activate dartdoc 0.15.0+1
```

cc @nex3 @munificent @devoncarew

**Comment by nex3** [comment] 2018-01-03 21:52
Duplicate of #1770.

**Closed by nex3** 2018-01-03 21:52 UTC
