### ISSUE TITLE
flutter doctor dosent work.

### ISSUE THREAD

**Issue by MahmoudQassass** [dart-lang/pub#3029] opened 2021-06-08 00:32 UTC
I remove pub cache folder then i get this error when try to do flutter doctor 

```
Bad state: Could not find 7zip.
package:pub/src/io.dart 885:3             _pathTo7zip.<fn>
package:pub/src/io.dart 886:3             _pathTo7zip
package:pub/src/io.dart                   _pathTo7zip
package:pub/src/io.dart 827:22            extractTarGz.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 773:12            withTempDir
===== asynchronous gap ===========================
package:pub/src/io.dart 818:25            extractTarGz
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 531:5  BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 381:7  BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 436:35    Entrypoint._get.<fn>
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 431:12    Entrypoint._get
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 265:7     Entrypoint.acquireDependencies
This is an unexpected error. Please run

    dart pub --trace get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Running "flutter pub get" in flutter_tools...
pub get failed (1; and include the logs in an issue on https://github.com/dart-lang/pub/issues/new)
```

**Comment by jonasfj** [comment] 2021-06-08 13:44
What channel are you on? did you just install? Did you change channels `master` -> `stable` ?

--------------------

quick note: Please use [code fences](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) when posting logs, for large log files please use a [gist](https://gist.github.com/).

**Comment by jonasfj** [comment] 2021-06-08 13:53
I can't reproduce this by upgrading / downgrading channels. It's correct that `7zip` has been removed from Flutter, but we have also stopped using it in the Dart SDK.

Ofcourse if somehow these got out of sync, something bad could possibly happen... like trying to use a newer version of Flutter SDK with an old version of Dart SDK. However, these should be linked in the Flutter SDK.

Hmm, so what exact version of Flutter SDK are you on, can you reproduce this in a new install?

**Comment by MahmoudQassass** [comment] 2021-06-08 16:23
> I can't reproduce this by upgrading / downgrading channels. It's correct that `7zip` has been removed from Flutter, but we have also stopped using it in the Dart SDK.
> 
> Ofcourse if somehow these got out of sync, something bad could possibly happen... like trying to use a newer version of Flutter SDK with an old version of Dart SDK. However, these should be linked in the Flutter SDK.
> 
> @MahmoudQassass
> What exact version of Flutter SDK are you on, can you reproduce this in a new install?

Thank you for replay.
I am using stable channel, I solve this issue by removing cache folder in C:\src\flutter\bin then run dart.bat

**Comment by jonasfj** [comment] 2021-06-08 16:45
@MahmoudQassass

Can you tell me how you got into this situation? are there some steps that will cause users to end up in this state?

**Comment by sigurdm** [comment] 2021-09-16 08:45
Closing as duplicate of https://github.com/dart-lang/pub/issues/3068

**Closed by sigurdm** 2021-09-16 08:45 UTC
Labels: needs info
