### ISSUE TITLE
Pub should attempt to locate Flutter SDK when FLUTTER_ROOT is not set

### ISSUE THREAD

**Issue by cbracken** [dart-lang/pub#1649] opened 2017-06-28 19:50 UTC
Running pub in a Flutter project results in the following error message if the `FLUTTER_ROOT` environment variable is not set:
```
Flutter is not available. If this is a Flutter project, make sure to always run
pub through the "flutter" executable.
```

There are legitimate use cases for directly running `pub run` in a Flutter project; e.g., i18n:
```
pub run intl_translation:extract_to_arb --output-dir=lib lib/messages.dart
```

Since we don't require (or expect) users to set `FLUTTER_ROOT`, if it's not set, it would be useful to make a best-effort attempt to locate the SDK. One potential solution would be an ordered iteration through the components of PATH looking for a file named `flutter`, resolve the symlink if it is one, get the parent dir of that, then check for the existence of a  'version' file there.

**Comment by cbracken** [comment] 2017-06-28 19:50
Filed based on report found here: http://qiita.com/konifar/items/d93e20ac0461e58a5247

**Comment by nex3** [comment] 2017-06-28 20:09
My understanding is that users are always expected to run pub through the `flutter` executable, which supported running arbitrary commands in a Flutter context.

As a general principle, I'd like to keep pub's SDK-specific logic to a minimum. Back when the Dart SDK was distributed more haphazardly, we ran into many bugs and bad user experiences trying to add heuristics for finding it. Imagine, for example, if `pub run` found a *different* Flutter than the one other commands used! I think it'll cause a lot less friction in the long run to teach Flutter users to always invoke pub through `flutter`.

**Comment by cbracken** [comment] 2017-06-28 20:40
> My understanding is that users are always expected to run pub through the flutter executable

I'm not convinced that's a good assumption. For example, the above use-case is entirely unrelated to Flutter, other than the fact that they happen to be invoking the tool in a project that is a Flutter project.

We don't currently expose `pub run` via the `flutter` tool. We *could* do so, but it seems preferable to support `pub run` directly. It seems unrealistic to expect Flutter users to know to mentally amend all instructions they find online about using `pub` to be something else (e.g., `flutter pub run`) and we don't expect Flutter users to know or care that the `flutter` tool is using `pub` under the hood.

Perhaps the issue isn't that pub should be cleverer about locating the SDK, but that it should support pub invocations that aren't dependent on Flutter.

**Comment by nex3** [comment] 2017-06-28 20:44
> Perhaps the issue isn't that pub should be cleverer about locating the SDK, but that it should support pub invocations that aren't dependent on Flutter.

We do; if you run something like `pub cache repair` in a Flutter package, it'll work fine. The issue is that once you start dealing with dependencies, you need to know where those dependencies are. `pub run`, for example, includes logic to verify that dependencies are up-to-date as well as logic to load them into a virtual environment if you're using transformers. That logic isn't possible without an understanding of where dependencies that come from the Flutter SDK exist, and it's not *reliable* unless we can ensure that those dependencies are going to be resolved the same way no matter how pub is invoked.

**Comment by sigurdm** [comment] 2022-02-24 09:51
The flutter/bin/dart executable today sets FLUTTER_ROOT, and the top-level pub command is going away. So I don't think there is anything more to do here.

Closing.

**Closed by sigurdm** 2022-02-24 09:51 UTC
