### ISSUE TITLE
pub upgrade shouldn't use different path styles in `pubspec.lock` for path dependencies

### ISSUE THREAD

**Issue by zoechi** [dart-lang/pub#1715] opened 2017-10-01 13:10 UTC
![image](https://user-images.githubusercontent.com/405837/31054762-41a8fcd8-a6ba-11e7-99d0-58695e4c43eb.png)

One seems to be from Windows, while the other is from OSX.

I'm not entirely sure this is possible everywhere, like with absolute paths containing Windows drive letters.
Perhaps it should just take the path from `pubspec.yaml`.

**Comment by nex3** [comment] 2017-10-02 19:39
Duplicate of #950.

**Closed by nex3** 2017-10-02 19:39 UTC
