### ISSUE TITLE
<Summarize your issues here>

### ISSUE THREAD

**Issue by thetwobear** [dart-lang/pub#2287] opened 2020-01-02 03:09 UTC
URL: https://pub.flutter-io.cn/help

******  B A T C H   R E C U R S I O N  exceeds STACK limits ******

Recursion Count=317, Stack Usage=90 percent

******       B A T C H   PROCESSING IS   A B O R T E D      ******
pub get failed (255; ******       B A T C H   PROCESSING IS   A B O R T E D      ******)

**Comment by jonasfj** [comment] 2020-01-02 10:04
Looks like a duplicate of https://github.com/dart-lang/pub/issues/2258

Please reopen with more details if that's not the case.

**Closed by jonasfj** 2020-01-02 10:04 UTC
