### ISSUE TITLE
    dart pub --trace get --no-precompile

### ISSUE THREAD

**Issue by rnvrsinghyadav** [dart-lang/pub#2965] opened 2021-04-20 10:12 UTC
this is an unexpected error. Please run

    dart pub --trace get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub get failed (1; and include the logs in an issue on https://github.com/dart-lang/pub/issues/new)
exit code 1

[shopee_clone-master] flutter pub get
Running "flutter pub get" in shopee_clone-master...             
Bad state: Could not find 7zip.

package:pub/src/io.dart 885:3             _pathTo7zip.<fn>
package:pub/src/io.dart 886:3             _pathTo7zip

package:pub/src/io.dart                   _pathTo7zip
package:pub/src/io.dart 827:22            extractTarGz.<fn>
===== asynchronous gap ===========================

package:pub/src/io.dart 773:12            withTempDir
===== asynchronous gap ===========================
package:pub/src/io.dart 818:25            extractTarGz

===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 531:5  BoundHostedSource._download
===== asynchronous gap ===========================

package:pub/src/source/hosted.dart 381:7  BoundHostedSource.downloadToSystemCache
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 436:35    Entrypoint._get.<fn>

===== asynchronous gap ===========================

package:pub/src/entrypoint.dart 431:12    Entrypoint._get
===== asynchronous gap ===========================
package:pub/src/entrypoint.dart 265:7     Entrypoint.acquireDependencies

This is an unexpected error. Please run

    dart pub --trace get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
pub get failed (1; and include the logs in an issue on https://github.com/dart-lang/pub/issues/new)
exit code 1

**Comment by sigurdm** [comment] 2021-09-16 08:44
Closing as duplicate of https://github.com/dart-lang/pub/issues/3068

**Closed by sigurdm** 2021-09-16 08:44 UTC
