### ISSUE TITLE
Unable to 'pub upgrade' flutter too

### ISSUE THREAD

**Issue by yeminliu2010** [dart-lang/pub#2075] opened 2019-02-26 08:00 UTC

**Comment by zoechi** [comment] 2019-02-26 10:21
Possible duplicate of https://github.com/flutter/flutter/issues/28498

**Comment by chenglu** [comment] 2019-02-26 14:45
It has been fixed, see my comments on [#28498](https://github.com/flutter/flutter/issues/28498#issuecomment-467462967) for more information.

**Comment by jonasfj** [comment] 2019-03-04 20:06
Please open a new issue with more details if this is still a problem..

**Closed by jonasfj** 2019-03-04 20:06 UTC
