### ISSUE TITLE
`pub get` on a commit that's not on a branch

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/pub#2543] opened 2020-06-29 08:51 UTC
See https://github.com/flutter/flutter/pull/60504.

`pub get` on a commit that's not on a branch (in this case after history was rewritten on purpose).

Should pub support commits that are not on a branch and might be GCed?

**Comment by sigurdm** [comment] 2020-07-28 11:31
Not sure I fully understand the issue.

Why should pub get not support a commit that is not a branch? I would imagine that makes `git bisect` next-to-impossible.
And how would that work if you are not using git?

...Or is this about git dependencies? Even those I would be highly annoyed if not everything supported by git as a valid ref was supported.

**Comment by dcharkes** [comment] 2020-07-28 12:15
https://github.com/flutter/flutter/pull/60507.

Maybe it should be documented that `pub` requires to be on a valid branch, due to some internal logic that is required to do pub stuff.

**Comment by sigurdm** [comment] 2020-07-28 13:45
How would pub know if a ref is on a branch?

**Comment by sigurdm** [comment] 2020-07-28 13:48
> due to some internal logic that is required to do pub stuff.

Still not sure I follow. Pub has (or should have) exactly the same requirements for git refs as git itself.
if you can `git co` it, you can have a dependency on it.

If a commit gets garbage collected that is the same issue as for all of git.

**Comment by dcharkes** [comment] 2020-07-28 13:56
Yes, so it is not supported to have a non-branch commit checked out and run `pub get`.

But this happens in the wild, e.g. people rewrite their histories. And then `pub get` retries forever. Maybe we should improve the error message in that situation instead of retrying forever: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8876208526460077424/+/steps/flutter_update-packages/0/stdout

**Comment by sigurdm** [comment] 2020-07-28 14:02
> Maybe we should improve the error message in that situation instead of retrying forever:

Ah - I had not understood that it would retry forever.
Yes, that should be fixed! Probably it is a duplicate of: https://github.com/dart-lang/pub/issues/2242 and the retry is actually a hack in the flutter tool, not in pub itself.

**Closed** 2023-01-26 10:03 UTC
Labels: needs info
