### ISSUE TITLE
Error when pubspec.yaml contain chinese

### ISSUE THREAD

**Issue by fengqiangboy** [dart-lang/pub#2028] opened 2019-01-16 06:38 UTC
## Steps to Reproduce
1、Edit pubspec.yaml description with chinese, like :

```
name: bbq

#here have some chinese
description: flutter项目

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

```

2、use flutter_launcher_icons plugin

3、run flutter_launcher_icons flutter packages pub run flutter_launcher_icons:main

4、If I delete chinese character in pubspec.yaml, It fixed.

## Logs

```
Unhandled exception:
Error on line 2, column 25: Unexpected character.
description: flutteré¡¹ç�®
                        ^
#0      Parser.parse (package:yaml/src/parser.dart:50:7)
#1      Loader._loadMapping (package:yaml/src/loader.dart:171:23)
#2      Loader._loadNode (package:yaml/src/loader.dart:86:16)
#3      Loader._loadDocument (package:yaml/src/loader.dart:62:20)
#4      Loader.load (package:yaml/src/loader.dart:54:20)
#5      loadYamlDocument (package:yaml/yaml.dart:51:25)
#6      loadYamlNode (package:yaml/yaml.dart:42:5)
#7      loadYaml (package:yaml/yaml.dart:34:5)
#8      YamlConfigParser.parse (package:dart_config/parsers/config_parser_yaml.dart:12:15)
#9      Config.readConfig.<anonymous closure> (package:dart_config/config.dart:44:25)
#10     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:486:5)
#15     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#18     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
pub finished with exit code 255
```

**Comment by sigurdm** [comment] 2019-01-17 14:25
I believe the problem is in https://github.com/chrisbu/dart_config/blob/master/lib/loaders/config_loader_filesystem.dart#L27 that does not do correct unicode decoding.

flutter_launcher_icons depends on a modified version from git (that supports dart2): https://github.com/MarkOSullivan94/dart_config

I made a pull request there for an update. But I think the whole setup with using a git-dependency seems very fragile and I would be careful using flutter_launcher_icons until they fix that.

You can temporarily insert a `dependency_overrides` in your pubspec.yaml:
```yaml
dependency_overrides:
  dart_config:
    git:
      url: https://github.com/MarkOSullivan94/dart_config
      ref: 59bfc92dbb4fddf9d694149ff2d60b537ffb408d
```

This has nothing to do with pub itself though. Therefore I will close this issue.

**Closed by sigurdm** 2019-01-17 14:25 UTC

**Comment by MarkOSullivan94** [comment] 2019-01-17 14:35
Appreciate the PR @sigurdm!

As for using a git-dependency, it's actually because the original dependency we had broke Flutter Launcher Icons and hadn't been updated since 2013.

I tested out a forked version of it which worked fine but was uncomfortable using someone else's Git repo so forked it to ensure it wouldn't be changed without me knowing.

Really the dart_config package needs to be taken over and kept up to date. If that happened, I would no longer use my forked version as a dependency. 

Do you know if there's any chance that can be done?

**Comment by sigurdm** [comment] 2019-01-17 14:58
I have no control over the dart_config package. But you are right it is unmaintained.
I have not looked into how you are using dart_config, but if you are mainly using it to parse a yaml file, perhaps use: https://pub.dartlang.org/packages/yaml directly or if it is pubspec specific use: https://pub.dartlang.org/packages/pubspec_parse

**Comment by Rickylin888** [comment] 2023-05-31 04:16
> I believe the problem is in https://github.com/chrisbu/dart_config/blob/master/lib/loaders/config_loader_filesystem.dart#L27 that does not do correct unicode decoding.
> 
> flutter_launcher_icons depends on a modified version from git (that supports dart2): https://github.com/MarkOSullivan94/dart_config
> 
> I made a pull request there for an update. But I think the whole setup with using a git-dependency seems very fragile and I would be careful using flutter_launcher_icons until they fix that.
> 
> You can temporarily insert a `dependency_overrides` in your pubspec.yaml:
> 
> ```yaml
> dependency_overrides:
>   dart_config:
>     git:
>       url: https://github.com/MarkOSullivan94/dart_config
>       ref: 59bfc92dbb4fddf9d694149ff2d60b537ffb408d
> ```
> 
> This has nothing to do with pub itself though. Therefore I will close this issue.

there something wrong with the url, it can't be access.
