### ISSUE TITLE
Pub/Publish: Warn when you are using an import transitively

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/pub#1480] opened 2016-12-01 20:27 UTC
I'd be OK with this an optional flag, but I really think it should be the default.

i.e., if I have in my pubspec:

```yaml
dependencies:
    angular2:
```

I will get a `.packages` resolution that includes many things, like `source_span`.

If I try to use `source_span` without relying on it, I'd like to see this become a warning/error:

```dart
// Hehe! I can use this because Angular does!
import 'package:source_span/source_span.dart';
```

**Comment by nex3** [comment] 2016-12-01 21:11
Duplicate of #343.

**Closed by nex3** 2016-12-01 21:11 UTC
